### DISCUSSION TITLE
Add new pipeline events

### DISCUSSION THREAD

**Discussion by anbraten** [woodpecker-ci/woodpecker#2174] [General]
We plan to add new pipeline events in the future:

Possible events:
- [x] PR close #286
- [x] Release (type: draft, pre, stable; action: created, updated, deleted) #764 
- [x] Cron #8 #934 
- [x] Support manually triggering a pipeline #83 #240 
- [ ] comments (create, delete, update) / #814 

- [ ] issue / pr_meta (include milestone, labels, description, comments as env vars)
  - [ ] created / re-openend
  - [ ] updated (also on milestone changed, label added, label removed, description, title updated)
  - [ ] closed

Adding a `when.event` filter for each pipeline or step would be quite complex and having a default value like skipping crons should probably be avoided as it can not easily be expected by an user:

![image](https://user-images.githubusercontent.com/6918444/204105571-072cace7-4855-4618-9344-9fff7d95909a.png)

Maybe we can add a new `on` / `trigger` keyword instead. By default a pipeline would not be executed at all. The linter could throw an error if no "trigger" is set at all. If a user adds one or multiple "trigger" events the pipeline will be executed for those events and contained steps can be filtered by `when.event`.

originally from https://github.com/woodpecker-ci/woodpecker/issues/286#issuecomment-1116699790

**Comment by gapodo** [comment]
A global `triggered_by` or `on` taking events could make sense, else I'd go with "if it's not filtered, it's a free for all".

Either explicitly specify or take all current and future events. Basically, when using wildcards or not filtering at all, I'd expect that as the default behavior THB.

Also, since some discussions on the Pipeline structure are still open (IIRC), are we currently completely non-breaking or should the new format get a version attribute anyway, which would then let us handle events based on config version (I believe once new keywords are added versioning will somewhat need to enter the picture anyway).

**Comment by anbraten** [comment]
> Either explicitly specify or take all current and future events. Basically, when using wildcards or not filtering at all, I'd expect that as the default behavior THB.

I am totally with you on that point. Already got kicked by that default filter for crons a few times 🙈 

We are trying to keep the config changes as minimal as possible, but if it is a needed change we would break things before releasing `1.0`. That's why we think and try to get all possible breaking changes https://github.com/woodpecker-ci/woodpecker/issues/869#issue-1191452845 done before releasing `1.0` so we do not break again and again.

There was the idea to have a completely separated code unit for the config compiling which would allow to add config version, but honestly that's pretty complicated and would probably require quite some effort to support old compilers in the long term.

**Comment by gapodo** [comment]
> There was the idea to have a completely separated code unit for the config compiling which would allow to add config version, but honestly that's pretty complicated and would probably require quite some effort to support old compilers in the long term.

Jep, that would be some effort, what I would take into consideration would be to have the version in the file at least from 1.0 upwards, so if there ever arises a need, it would be easy to differentiate. Also having versions would allow showing deprecation notices (failing a build until `deprecation_know` is set to `true`?), so that a switchover would only mean maintaining 2 compilers/versions for a limited amount of time or potentially handle the changes longer if they are easy to maintain.

An example would be this issues base idea, if we don't find a `on`, `trigger` `triggered_by` or what ever in the definition assume it's old and only trigger on the old events.

**Comment by smainz** [comment]
Maybe I do not get it, but what would be the difference between (on a pipeline / workflow level):

```
when:
  - event:
    - push
    - pull_request
  
pipeline:
  - name: First step
 
...
```
and
```
on:
  - push
  - pull_request
 
pipeline:
  - name: First step
```

If possible I would not introduce new keywords for already existing concepts. You have twice the time to document it and users need to learn twice.


In the end (#745, #567) It could be something like this:

```
pipeline:
  when:
    - event: 
      - push
      - pull_request
    - cron
     
  workflows:
    - name: Build pipeline
      when:
        - push
        - branch: master
      steps:
       - name: Prepare build
         image: alpine
         commands:
           ...

    - name: PR pipeline
      when:
        - event: pull_request
      steps:
        - name: Prepare PR
          image: alpine
```

The further down a condition is, the smaller the scope.
