### DISCUSSION TITLE
Global defaults for some keywords

### DISCUSSION THREAD

**Discussion by x80486** [woodpecker-ci/woodpecker#2294] [Request a Feature]
### Clear and concise description of the problem

`Woodpecker CI` could benefit from using some defaults to avoid repetitive blocks and/or references to anchors.

This is something I used to use in `GitLab CI` and it makes the pipeline really compact. For instance, they have a `default` keyword to configure some "default" values that apply to all subsequent steps — when relevant.

### Suggested solution

```yaml
default:
  image: docker.io/library/rust:1.61-slim-bullseye

pipeline:
  format:
    commands:
      - rustup component add rustfmt
      - cargo fmt -- --check
    environment:
      CARGO_HOME: .cargo/
    group: verify
    # No need to specify image here since it's inferred by "default"
  assemble:
    commands:
      - cargo build
    environment:
      CARGO_HOME: .cargo/
    group: assemble
    # No need to specify image here since it's inferred by "default"
  publish:
    commands:
      - cargo blah
    environment:
      CARGO_HOME: .cargo/
    group: publish
    image: docker.io/library/rust:1.62-slim-bullseye # ...if defined, overwrites what's in default
```

### Alternative

YAML aliases and anchors :unamused:

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.
