### DISCUSSION TITLE
Pipeline caching

### DISCUSSION THREAD

**Discussion by fnetX** [woodpecker-ci/woodpecker#2295] [Request a Feature]
### Clear and concise description of the problem

Caching is a issue often talked about. It would save a lot of resources if dependencies for projects are not built every time, but only run from a certain point on.

### Suggested solution

There is already a feature request in #758 that might try to achieve something similar, but it sounds focused on results, not prepare steps.

My proposal is the following: For every pipeline stage, there is an optional "refresh: " parameter, that defines how often this needs to be rebuilt. For example, when dependencies change frequently, you can specifiy "refresh: 1d". If your prepare step is used seldom, you can rebuilt it every 14d.

If you install some system requirements (e.g. git, nodejs, your compiler, ...), you could specifiy to rebuild it every 30d, but the next pipeline that pulls your specific dependencies (npm, go packages etc) is refreshed every 12h.

The container state that is created at this point is than cached for the maximum specified time, maybe by simply tagging the docker image, just like Docker builds are cached when the context and the Dockerfile doesn't change.

The big question is how the clone is supposed to work there. Probably by defining prepare steps and clone the project afterwards. Or clone into a mount at the beginning and keep it even with different containers.

### Alternative

The 

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by reivilibre** [comment]
This proposal makes some kind of sense to me.

I find myself having to create special-purpose Docker containers with base dependencies for CI to run faster.
I've always felt a wish that I could just keep the instructions written in the CI YAML file but have the stages 'cached'.

There is another wish to have a way to cache package downloads/compilations (for e.g. Cargo), since that takes a long time on my CI and outweighs the build time of my project (also wasting energy/time/...). I tried setting up MinIO and sccache but it was pretty clunky and didn't work that well. I wish there was a nicely-integrated built-in method.

**Comment by anbraten** [comment]
# Proposal

As caching needs to work for different backends (docker, kubernetes, local, ssh, ...) it would probably be the best to allow the backends to internally map the cache volume to their supported system.

## config

```yml
steps:
  restore-cache:
    image: awesome-volume-cacher
    settings:
      cache_key: 123
    volumes:
      - name: cache
        path: /cache
  build:
    image: node
    commands:
      - npm install
    volumes:
      - name: cache
        path: /cache
  save-cache:
    image: awesome-volume-cacher
    settings:
      cache_key: 123
    volumes:
      - name: cache
        path: /cache
volumes:
  - name: cache
```

## backend support

### docker & kubernetes
- using container volumes (as suggested by #2272) 
- with a prefix to restrict access to projects & prevent name colision with existing volumes

### local & ssh
- maybe some `ln` (restricted to specific directories) pointing to a folder

## problems & open questions

### multiple agents support
There could be an issue that the volume doesn't exists on the agent. We could therefore add logic to the cache plugin or the backend directly to download non existing volume data from a s3 bucket.

### space qutoas
There need to be a way to restrict volume sizes

### cache cleanup / expiration
How can we easily define a volume expiration date

**Reply by zc-devs** [reply]
> We could therefore add logic to the cache plugin or the backend directly to download non existing volume data from a s3 bucket.

To the cache plugin, please. It is deep implementation: S3, FTP, SCP, encryption (?) This is not Agent responsible for. Let Agent deal with volumes stuff.

**Comment by dvjn** [comment]
I have implemented a lot of caching for my woodpecker pipelines at work.

I feel, most of the cache requirements can be solved by a plugin, a volume mount, and a shared storage across agents (using an NFS server, or maybe S3FS?).

The only annoying thing that I encountered throughout the caching journey is that I have to mark all the pipelines trusted in which I want to mount the cache volume.

Just a thought: can the problem statement be reduced to "finding a better way to allow mounting cache volumes in caching plugins without needing to be trusted?"

**Reply by qwerty287** [reply]
> Just a thought: can the problem statement be reduced to "finding a better way to allow mounting cache volumes in caching plugins without needing to be privileged?"

I actually wrote a basic proposal some time ago which is doing this: https://github.com/woodpecker-ci/woodpecker/pull/1353
In the end, I didn't follow this, but I still think it's the best approach.

However, you must note some things for security. Especially, it shouldn't be possible to change the cache from a pull request.

**Reply by dvjn** [reply]
My idea was to implement something like this:

```yaml
steps:
  - name: pull cache
    image: cache-pull
    settings:
      local_dirs:
        - node_modules
        - .vite
      cache_dir: /woodpecker-cache/my-repo/my-cache
    mount_cache_directory: true

  - name: Build
    image: node:lts
    commands:
      - npm install
      - npm run build
    - ...

  - name: push cache
    image: cache-push
    settings:
      local_dirs:
        - node_modules
        - .vite
      cache_dir: /woodpecker-cache/my-repo/my-cache
    mount_cache_directory: true
```

1. Agents responsible to mount a shared directory across all agents (using NFS, S3FS, etc).
2. Make cache directory path configurable on each agent.
3. Add admin settings to allow mounting cache directory to specific plugins (like secrets) or to everyone (on a private and trusted instance).
4. A setting like `mount_cache_directory` which will mount the agent's configured cache directory to a predefined location like `/woodpecker-cache` in the container.
