### DISCUSSION TITLE
Consider having some DSL to store artifacts between steps

### DISCUSSION THREAD

**Discussion by x80486** [woodpecker-ci/woodpecker#2301] [Request a Feature]
### Clear and concise description of the problem

Pipelines do many things, but most of the times there is always a resultant _artifact_. This could be a release, some file(s) to be used by subsequent steps, and so on.

Woodpecker CI could be enhanced to allow storing these artifacts between steps.

> Notice this could look like a cache, but it's intended for something completely different.

### Suggested solution

```yaml
pipeline:
  assemble:
    artifacts:
      expire_in: 1 year # 3 months, 7 days, 1 week
      paths:
        - ${CI_PROJECT_DIR}/target/
    ...
```

### Alternative

N/A

### Additional context

This could be also a way to persist some other files for doing reporting, code coverage reports, etc.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.
