### DISCUSSION TITLE
Are steps without any matrix variable executed as a single run?

### DISCUSSION THREAD

**Discussion by Andre601** [woodpecker-ci/woodpecker#2318] [Ask a Question] [answered]
Right now do I have a workflow file with a Matrix setup which does the following:

- Obtain release ID from a Codeberg repository's release based on the tag pushed.
- Generate files to then upload to the release using the previously obtained ID.

The issue I see right now with this is, that the first action is executed within each matrix run, meaning I would in this case do 3 individual calls to the API, which is just wasteful.

I would like to only obtain the ID once, preferably in a step before the one creating the files, to then reuse in the later steps, but I'm not sure if woodpecker works the way I expect it to...

If I would define a step that doesn't use any matrix variables defined, would woodpecker assume it's a single step or would it create individual ones for each matrix variable?
How would I be able to only execute a certain thing once while using the matrix for other steps?

Help is greatly apreciated as I'm not too experienced yet with woodpecker.
If it is of any importance am I using a woodpecker CI instanced offered by Codeberg (Not self-hosting one), so I may not have access to every possible feature of woodpecker...

My current setup:
```yaml
when:
  event: tag

matrix:
  include:
    - PLATFORM: Bukkit
      DIRECTORY: bukkit
    - PLATFORM: BungeeCord
      DIRECTORY: bungeecord
    - PLATFORM: Velocity
      DIRECTORY: velocity

steps:
  createFiles:
    image: eclipse-temurin
    secrets:
      - cb_token
    commands:
      # Build the jar files
      - mvn --projects :core,:${DIRECTORY} clean install
      # Obtain release ID
      - |-
        export RELEASE_ID=`curl --locatiion "https://codeberg.org/api/v1/repos/Andre601/AdvancedServerList/releases?limit=10" \
        --header 'Authorization: token $CB_TOKEN' \
        --header 'Accept: application/json' -s -S \
        --fail-with-body | jq -r ".[] | select (.tag_name==\"$CI_COMMIT_TAG\").id"`
      # Upload release assets to Codeberg release
      - |-
        curl --location "https://codeberg.org/api/v1/repos/Andre601/AdvancedServerList/releases/$RELEASE_ID/assets" \
        --header "Authorization: token $CB_TOKEN" \
        --header "Content-Type: multipart/form-data" -s -S \
        --form "attachment=@${DIRECTORY}/target/AdvancedServerList-${PLATFORM}-${CI_COMMIT_TAG##v}.jar;type=application/octet-stream" \
        --fail-with-body
```
