### DISCUSSION TITLE
Specify resource constraints for step containers inside step config

### DISCUSSION THREAD

**Discussion by lonix1** [woodpecker-ci/woodpecker#2328] [Request a Feature]
There are some resource limiting settings we can apply to step containers, e.g. `WOODPECKER_LIMIT_MEM`, which must be set in the woodpecker server's `docker-compose.yml`.

So those settings apply to ALL step containers in ALL pipelines for ALL repos.... not scalable at all.

(I must set those limits to match the most memory and cpu intensive containers in my server - in other words all containers get as much resources as the container which is the biggest pig. There are no big pigs and small pigs... they're all big. :pig: So I must provision much more memory than I actually need, and as you know memory is not cheap.)

It would be nice to specify the resource limits for a step, inside the step, e.g.:
```yml
steps:
  build:
    image: foo
    environment:
      - WOODPECKER_LIMIT_MEM=209715200        # 200MiB
      - WOODPECKER_LIMIT_CPU=0.25             # 25%
  test:
    image: bar
    environment:
      - WOODPECKER_LIMIT_MEM=524288000        # 500MiB
      - WOODPECKER_LIMIT_CPU=0.5              # 50%
```

There is already discussion about a [file-based config](https://github.com/woodpecker-ci/woodpecker/discussions/2317) feature. It would be good to include this.
