### DISCUSSION TITLE
Unify step list definition

### DISCUSSION THREAD

**Discussion by qwerty287** [woodpecker-ci/woodpecker#2475] [Request a Feature]
Currently, you can either use:
```yaml
steps:
    - name: step
      image: xyz
```

or

```yaml
steps:
    step:
      image: xyz
```

Unify this, the arrray-syntax is probably better as it's more powerful.
