### DISCUSSION TITLE
Git clone based on branch

### DISCUSSION THREAD

**Discussion by amino-8** [woodpecker-ci/woodpecker#2528] [Ask a Question] [answered]
I'm trying to trigger the clone for a pipeline only if there's a commit to the main branch. I have other actions in the pipeline that trigger if I commit to another branch that do not require a clone operation.
If I try to put a when clause in the clone part of the pipeline I get an error - failed to parse pipeline: yaml: unmarshal errors: line 7: cannot unmarshal !!seq into types.Container
e.g.:
```
clone:
    git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: true
  when:
    - branch: main    
```

Can someone point me in the right direction for how to achieve conditional cloning in a pipeline?

**Comment by qwerty287** [comment, marked as answer]
Your indentation is wrong:
```yaml
clone:
    git:
        image: woodpeckerci/plugin-git
        settings:
            recursive: true
        when:
          - branch: main
```
