### DISCUSSION TITLE
Woodpecker is only responding to manual trigger.

### DISCUSSION THREAD

**Discussion by micash545** [woodpecker-ci/woodpecker#2667] [General]
workflow file:
```yml
when:
  - event: pull_request
  - event: push
    branch: main
  - event: manual

steps:
  build:
    image: node
    pull: true
    commands:
      - yarn
      - yarn build
  check:
    image: debian
    pull: true
    commands:
      - ls -la
```
