### DISCUSSION TITLE
Kubernetes: how to call a service / name it?

### DISCUSSION THREAD

**Discussion by zc-devs** [woodpecker-ci/woodpecker#2721] [General]
From [Matrix](https://matrix.to/#/!ElrAiHCaPpSDVVcayj:obermui.de/$tx9c8lCxBE4CFZMcKhTwSn9EsfvvGiOXRHVQ6ZxnhMw?via=matrix.org&via=t2bot.io&via=obermui.de):

https://github.com/woodpecker-ci/woodpecker/pull/2656#issuecomment-1790002865

> could you report if we can check the "services" part of #1513 now ?

Apart from [#2709](https://github.com/woodpecker-ci/woodpecker/issues/2709), it works technically speaking. But is it useful? I think no.

```
mysql -uroot -hdatabase test -pexample
```

There is no `database` service . There is `wp-01he8bebctabr3kgk0qj36d2me-0-services-0` service for example. So, we have to connect to it:

```
mysql -uroot -hwp-01he8bebctabr3kgk0qj36d2me-0-services-0 test -pexample
```

It should work:

```
# nslookup wp-01he8bebctabr3kgk0qj36d2me-0-services-0.woodpecker-runtime.svc.cluster.local
Server:         10.43.0.10
Address:        10.43.0.10#53

Name:   wp-01he8bebctabr3kgk0qj36d2me-0-services-0.woodpecker-runtime.svc.cluster.local
Address: 10.43.181.50
```

This name is generated. So, we cannot know it when writing pipeline. Also, AFAIK there is no way to know it inside step.

Solutions I see now:

1. Use `step.alias` (`database` in the example). Service name have to be unique. Otherwise we can't run pipelines simultaneously with the same service name (in the same Kube namespace).
2. Kubernetes uses env vars for [service discovery](https://stackoverflow.com/questions/45759205/what-environment-variables-are-created-in-kubernetes-by-default) (`WP_01HE8BEBCTABR3KGK0QJ36D2ME_0_SERVICES_0_SERVICE_HOST=10.43.181.50` for example). We can supply some map/dict in our env var: `WOODPECKER_SERVICES="database=wp-01he8bebctabr3kgk0qj36d2me-0-services-0,cache=..."`. Or use variable for each service: `WOODPECKER_SERVICE_DATABASE=wp-01he8bebctabr3kgk0qj36d2me-0-services-0`, `WOODPECKER\_SERVICE_CACHE=...`.
Then use it like `mysql -uroot -h$WOODPECKER_SERVICE_DATABASE test -pexample`.

**Comment by J-Ha** [comment]
the connection problem itself would be fixed by the correct label selector
for this example, there is a hostalias in the Step pod with the name  `Database` that points to the IP Address of the service for the Database (10.43.181.50)
the problem is in this case, that the service has no target to forward to the running database container, because the label selector doesn't match any pod within the namespace. 

here a small example from my side and and a quick and dirty proof: 

.woodpecker.yaml:
```
 steps:
   build:
     image: docker
     environment:
       - DOCKER_HOST=tcp://docker:2375
     commands:
       - sleep 10
       - docker version || true
       - echo "sleep for 60 seconds, while changing service label selector"
       - sleep 60
       - docker version


 services:
   docker:
     image: docker:dind
     environment:
       - DOCKER_HOST=tcp://docker:2375
     ports:
     - 2375
     commands: dockerd --storage-driver=vfs --tls=false --host=tcp://0.0.0.0:2375
     privileged: true
```
part of the woodpecker wp-1hearh2xfzy85kdyaa0p5zgy0-0-step-0 while the normal creation is: 

```
  hostAliases:
  - hostnames:
    - docker
    ip: 100.70.178.234
```

changed service from:

```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-11-03T14:13:56Z"
  name: wp-01hearh2xfzy85kdyaa0p5zgy0-0-services-0
  namespace: woodpecker
  resourceVersion: "32993376"
  uid: 94a4bb9b-ac59-4f51-8c53-9e8a3688c122
spec:
  clusterIP: 100.70.178.234
  clusterIPs:
  - 100.70.178.234
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 2375
    protocol: TCP
    targetPort: 2375
  selector:
    step: docker 
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
which results into no attached endpoint

to:

```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-11-03T14:13:56Z"
  name: wp-01hearh2xfzy85kdyaa0p5zgy0-0-services-0
  namespace: woodpecker
  resourceVersion: "32993376"
  uid: 94a4bb9b-ac59-4f51-8c53-9e8a3688c122
spec:
  clusterIP: 100.70.178.234
  clusterIPs:
  - 100.70.178.234
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 2375
    protocol: TCP
    targetPort: 2375
  selector:
    step: wp-01hearh2xfzy85kdyaa0p5zgy0-0-services-0
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
which attaches the service to the `wp-01hearh2xfzy85kdyaa0p5zgy0-0-services-0` pod

pipelinelog:

```
+ sleep 10
+ docker version || true
Client:
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:06:50 2023
 OS/Arch:           linux/arm64
 Context:           default
Get "http://docker:2375/v1.24/version": dial tcp 100.70.178.234:2375: i/o timeout
+ echo "sleep for 60 seconds, while changing service label selector"
sleep for 60 seconds, while changing service label selector
+ sleep 60
+ docker version
Client:
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:06:50 2023
 OS/Arch:           linux/arm64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:08:17 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          v1.7.6
  GitCommit:        091922f03c2762540fd057fba91260237ff86acb
 runc:
  Version:          1.1.9
  GitCommit:        v1.1.9-0-gccaecfc
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Reply by J-Ha** [reply]
this also works fine with multiple services within the same pipeline:
```

 steps:
   build:
     image: docker
     environment:
       - DOCKER_HOST=tcp://docker:2375
     commands:
       - sleep 10
       - docker version || true
       - cat /etc/hosts
       - echo "sleep for 60 seconds, while changing service label selector"
       - sleep 60
       - docker version
       - sleep 500

 services:
   docker:
     image: docker:dind
     environment:
       - DOCKER_HOST=tcp://docker:2375
     ports:
     - 2375
     commands: dockerd --storage-driver=vfs --tls=false --host=tcp://0.0.0.0:2375
     privileged: true
   cache:
     image: redis
     ports:
     - 6379
   database:
    image: mysql
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=example
    ports:
    - 3306
```
the step-0 container gets created with this host aliases:
```
  hostAliases:
  - hostnames:
    - docker
    ip: 100.69.4.41
  - hostnames:
    - cache
    ip: 100.65.21.154
  - hostnames:
    - database
    ip: 100.64.66.160
```

the pipeline creates 3 services:
```
wp-01heat4pjqfp1c75jr97bhfmg8-0-services-0   ClusterIP   100.69.4.41      <none>        2375/TCP          2m58s
wp-01heat4pjqfp1c75jr97bhfmg8-0-services-1   ClusterIP   100.65.21.154    <none>        6379/TCP          2m58s
wp-01heat4pjqfp1c75jr97bhfmg8-0-services-2   ClusterIP   100.64.66.160    <none>        3306/TCP          2m58s
```

and here is a smiple cat of the step-0 container in the pipeline:
```
+ cat /etc/hosts
# Kubernetes-managed hosts file.
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
fe00::0	ip6-mcastprefix
fe00::1	ip6-allnodes
fe00::2	ip6-allrouters
100.96.6.242	wp-01heat4pjqfp1c7[5](https://woodpecker.uploadfilter24.eu/repos/10/pipeline/30/6#L5)jr97bhfmg8-0-step-0

# Entries added by HostAliases.
100.69.4.41	docker
100.65.21.154	cache
100.64.66.160	database
```
