### DISCUSSION TITLE
'Available for following steps' secrets filter

### DISCUSSION THREAD

**Discussion by zc-devs** [woodpecker-ci/woodpecker#2834] [Request a Feature]
Follow up of #2832.

1. Naming is confusing. Should be plugins then:
![Screenshot 2023-11-16 183127](https://github.com/woodpecker-ci/woodpecker/assets/127358482/cc67ea10-0b5b-4b04-84fe-e6e873310747)

2. I, personally, use it for general commands and have not used some plugin yet (except `clone`, of course). While making secrets pipeline-wide by default is good thing, getting rid of functionality is step back, I think.
Consider pipeline:
```yaml
steps:
  package:
    image: python:3.11.4-alpine3.18
    commands:
      - python -m build
      - python -m twine upload --repository pypi dist/*
    secrets:
      - twine_username
      - twine_password
  image:
    image: gcr.io/kaniko-project/executor:v1.12.1-debug
    commands:
      - executor --context ./ \
        --dockerfile Dockerfile \
        --destination "my-registry/project:latest"
    secrets:
      - docker_usr
      - docker_pwd
```
There can be much more steps with dedicated function, custom image and their own secrets. So, filtering by steps would be appreciated.
