### DISCUSSION TITLE
Podman-in-Podman image builds

### DISCUSSION THREAD

**Discussion by handlebargh** [woodpecker-ci/woodpecker#2932] [Show and tell]
I run Woodpecker CI with podman backend instead of docker and just figured out how to build images with buildah. Since I couldn't find this anywhere documented I thought I might as well just share it here.

It's actually pretty straight forward. Here's what my repository structure looks like:

```
.
├── roundcube
│   ├── Containerfile
│   ├── docker-entrypoint.sh
│   └── php.ini
└── .woodpecker
    └── .build_roundcube.yml
```

As you can see I'm building a roundcube mail image.

This is the `.woodpecker/.build_roundcube.yml`

```
when:
  event: [cron, manual]
  cron: build_roundcube

steps:
  build-image:
    image: quay.io/buildah/stable:latest
    pull: true
    privileged: true
    commands:
      - echo $REGISTRY_LOGIN_TOKEN | buildah login -u <username> --password-stdin registry.gitlab.com
      - cd roundcube
      - buildah build --tag registry.gitlab.com/<namespace>/<repository_name>/roundcube:latest .
      - buildah push registry.gitlab.com/<namespace>/<repository_name>/roundcube:latest

    secrets: [registry_login_token]
```

As you can see I'm using this workflow over at gitlab.com. It should work with GitHub as well with adjusting the registry login.

You may have to adjust the `when:` to your needs. Furthermore, you must check the `trusted` checkbox in project settings. Therefore be sure to run trusted code only in this setup.

This seems to work fine so far. I wonder if anybody else made this work a different way.

EDIT: Removed the additional step that would run buildah in a podman container. I didn't know it could be that easy to be honest.

**Comment by handlebargh** [comment]
I just figured that running the buildah container in the podman container is unnecessary. I'm going to update the inital post.

**Comment by qwerty287** [comment]
We can add this (and whatever else too of course, see e.g. #2019) to #316 once we added this initially.

**Reply by anbraten** [reply]
Or we post such things in our blog with a tag like: `guide`.

**Reply by anbraten** [reply]
But would definitely be cool to have such guides on the homepage somewhere.

**Reply by qwerty287** [reply]
I don't think that's a good idea, I'd only use blog posts for announcements and similar.

**Reply by anbraten** [reply]
The benefit of blog posts is that they have dates (so a user can consider old posts as outdated without us needing to keep them up-to-date all the time). In addition we could use them to make users aware about Woodpecker and how it could solve their daily issues. Maybe we could even post on social-media about interesting and pretty posts.

**Reply by qwerty287** [reply]
Is it possible to have multiple blogs (or just categories) with different lists in docusaurus? Then it would be fine

**Reply by anbraten** [reply]
Seems like from this config page: https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-blog

**Reply by anbraten** [reply]
https://docusaurus.io/docs/blog#multiple-blogs

**Reply by handlebargh** [reply]
That sounds good. Either way, if it's gonna be a blog or something else, I'd happily contribute some config examples to these docs (or even an entire blog post for that matter).

However, meanwhile I wrote another workflow that allows image signing at push and image signature verification at pull. Both with sigstore signtaures and natively in podman. Hope you don't mind if I reuse this thread. I think it's close enough related.

**Comment by handlebargh** [comment]
## Example: Podman image build with sigstore signature checking and signing

This example shows how to build a container image with podman while verifying the base image and signing the resulting image.

The image being pulled uses a keyless signature while the image being built will be signed by a pre-generated private key.

## Prerequisites

### Generate signing keypair

You can use cosing or skopeo to generate the keypair.

Using skopeo:
```
skopeo generate-sigstore-key --output-prefix myKey
```
This command will generate a `myKey.private` and a `myKey.pub` keyfile.

Store the `myKey.private` as secret in Woodpecker. In the example below the secret is called `sigstore_private_key`

### Configure hosts pulling the resulting image

See [here](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/building_running_and_managing_containers/assembly_signing-container-images_building-running-and-managing-containers#proc_verifying-sigstore-image-signatures-using-a-public-key_assembly_signing-container-images) on how to configure the hosts pulling the built and signed image.

## Repository structure

Consider the `Makefile` having a `build` target that will be used in the following workflow.
This target yields a Go binary with the filename `app` that will be placed in the root directory.

```
.
├── Containerfile
├── main.go
├── go.mod
├── go.sum
├── .woodpecker.yml
└── Makefile
```

### Containerfile

The Containerfile refers to the base image that will be verified when pulled.

```
FROM gcr.io/distroless/static-debian12:nonroot
COPY app /app
CMD ["/app"]
```

### Woodpecker workflow
```yaml
steps:
  build:
    image: docker.io/library/golang:1.21
    pull: true
    commands:
      - make build

  publish:
    image: quay.io/podman/stable:latest
    # Caution: This image is built daily. It might fill up your image store quickly.
    pull: true
    # Fill in the trusted checkbox in Woodpecker's settings as well
    privileged: true
    commands:
      # Configure podman to use sigstore attachments for both, the registry you pull from and the registry you push to.
      - |
        printf "docker:
          registry.gitlab.com:
            use-sigstore-attachments: true
          gcr.io:
            use-sigstore-attachments: true" >> /etc/containers/registries.d/default.yaml

      # At pull, check the keyless sigstore signature of the distroless image.
      # This is a very strict container policy. It allows to pull from gcr.io/distroless only. Every other registry will be rejected.
      # See https://github.com/containers/image/blob/main/docs/containers-policy.json.5.md for more information.
      
      # fulcio CA crt obtained from https://github.com/sigstore/sigstore/blob/main/pkg/tuf/repository/targets/fulcio_v1.crt.pem
      # rekor public key obtained from https://github.com/sigstore/sigstore/blob/main/pkg/tuf/repository/targets/rekor.pub
      # crt/key data is base64 encoded. --> echo "$CERT" | base64
      - |
        printf '{
            "default": [
              {
                "type": "reject"
              }
            ],
            "transports": {
              "docker": {
                "gcr.io/distroless": [
                  {
                    "type": "sigstoreSigned",
                    "fulcio": {
                      "caData": "LS0tLS1CRUdJTiBDR...QVRFLS0tLS0K",
                      "oidcIssuer": "https://accounts.google.com",
                      "subjectEmail": "keyless@distroless.iam.gserviceaccount.com"
                    },
                    "rekorPublicKeyData": "LS0tLS1CRUdJTiBQVUJ...lDIEtFWS0tLS0tCg==",
                    "signedIdentity": { "type": "matchRepository" }
                  }
                ]
              },
              "docker-daemon": {
                "": [
                  {
                    "type": "reject"
                  }
                ]
              }
            }
          }' > /etc/containers/policy.json

      # Use this key to sign the built image at push.
      - echo "$SIGSTORE_PRIVATE_KEY" > key.private
      # Login at the registry
      - echo $REGISTRY_LOGIN_TOKEN | podman login -u <username> --password-stdin registry.gitlab.com
      # Build the container image
      - podman build --tag registry.gitlab.com/<namespace>/<repository_name>/<image_name>:latest .
      # Sign and push the image
      - podman push --sign-by-sigstore-private-key ./key.private registry.gitlab.com/<namespace>/<repository_name>/<image_name>:latest

    secrets: [sigstore_private_key, registry_login_token]
```
