### DISCUSSION TITLE
Debug pipeline steps

### DISCUSSION THREAD

**Discussion by anbraten** [woodpecker-ci/woodpecker#2941] [Show and tell]
Sometimes you want to debug a pipeline. 
Therefore I recently discovered: https://github.com/ekzhang/sshx

A simple step like should allow you to debug:

```yml
steps:
  - name: debug
    image: alpine
    commands:
      - curl -sSf https://sshx.io/get | sh && sshx
      #      ^
      #      └ This will open a remote terminal session and print the URL. It
      #        should take under a second.
```
