### DISCUSSION TITLE
Secrets and variables usage best practices

### DISCUSSION THREAD

**Discussion by ojio-san** [woodpecker-ci/woodpecker#3130] [Ask a Question] [answered]
Hello,

here is a part of my .woodpecker file : 
```
## webapp
when: [...]

variables:
  - &build_plugin "woodpeckerci/plugin-docker-buildx:2.2.1"
  - &registry
      from_secret: local_registry
  - base_settings: &base_buildx_settings
      registry: *registry
      repo: 10.10.10.10:5050/webapp
      dockerfile: webapp/Dockerfile
      tag: latest
      context: webapp/


steps:
  build:
    image: *build_plugin
    secrets: [ docker_username, docker_password ]
    settings:
      <<: *base_buildx_settings
```
My local_registry secret is `10.10.10.10:5050`, and my question A is : could I use a variable for the line `repo: 10.10.10.10:5050/webapp` ?

I would like to use something like `repo: ${local_registry}/webapp`, because as far as I understand, I must use the registry name as prefix to tell docker to use my local registry (instead of the default registry-1.docker.io).

And in the end, the registry and repo settings are almost the same, like :  
```
      registry: 10.10.10.10:5050
      repo: 10.10.10.10:5050/webapp
```

Or, question B : is there a setting to auto-generate the "repo" setting when a local docker registry is used ?

Best regards and thank you :)
