### DISCUSSION TITLE
Tag name with variable

### DISCUSSION THREAD

**Discussion by ojio-san** [woodpecker-ci/woodpecker#3181] [Ask a Question] [answered]
Hello,

here is a part of my .woodpecker file :
```
## webapp
when: [...]

variables:
  - &date_var: &date_var
    - echo $(date -u +'%Y.%m.%d')

steps:
  build:
    image: "woodpeckerci/plugin-docker-buildx:2.2.1"
    secrets: [ docker_username, docker_password ]
    settings:
      registry: ${MY_REGISTRY}
      repo: ${MY_REGISTRY}/webapp
      dockerfile: webapp/Dockerfile
      tags:
        - ${CI_COMMIT_SHA:0:8}
        - latest
      context: webapp/
```

For this image, my tags are (for example) "a5fa810b" and "latest", but I would like to get the following tags : 
```
- a5fa810b-2024-01-12
- latest
```

**Question** : How should I concat the `${CI_COMMIT_SHA:0:8}` and the `*date_var` to get `a5fa810b-2024-01-12` ?

Maybe something like this, even if I know that the date can't be called here, that's just the principle :
```
variables:
  - &custom_tag: ${CI_COMMIT_SHA:0:8}-$(date -u +'%Y.%m.%d')
```
and 
```
      tags:
        - *custom_tag
        - latest
```

Best regards and thank you :)

**Comment by anbraten** [comment]
The pre-processor is currently not able to do sth like you tried / suggested with echo date.

**Comment by 6543** [comment]
**a configuration itselve should !! never !! be turning complete!!**
 

well i created a pull to not get that loost -> https://github.com/woodpecker-ci/woodpecker/pull/3184

**Comment by 6543** [comment, marked as answer]
@ojio-san as for your problem ... I'm afraid you have to wait for https://github.com/woodpecker-ci/woodpecker/discussions/2254 to be implemented.

**Reply by 6543** [reply]
@ojio-san what you can do: create a step who generates a `.tags` file ...

```
## webapp
when: [...]

steps:
  create-container-tag:
    image: alpine
    commands:
     - echo  "$(date -u +'%Y.%m.%d')" >> .tags
     - echo "${CI_COMMIT_SHA:0:8}" >> .tags
     - echo latest >> .tags
  build:
    image: "woodpeckerci/plugin-docker-buildx:2.2.1"
    secrets: [ docker_username, docker_password ]
    settings:
      registry: ${MY_REGISTRY}
      repo: ${MY_REGISTRY}/webapp
      dockerfile: webapp/Dockerfile
      tags_file: ".tags"
      context: webapp/
```
