### DISCUSSION TITLE
Rename registries

### DISCUSSION THREAD

**Discussion by qwerty287** [woodpecker-ci/woodpecker#3191] [General]
We currently have internal registry support, but this support has some issues in my opinion:

- It is only supported for the docker back end while it looks like being supported by all backends because it's in the main UI.
- They're defined in UI which does not allow to view git history etc. of changes.

My suggestion is to define registry credentials directly in the workflow yamls using `backend_options` (or any other way):

```yaml
steps:
  - name: step
    image: registry.com/xyz
    backend_options:
      docker:
        registry:
          username: some-user
          password:
            from_secret: reg_password
```
