### DISCUSSION TITLE
Configure the volumes path using variables or secrets

### DISCUSSION THREAD

**Discussion by Hentioe** [woodpecker-ci/woodpecker#3238] [Ask a Question] [answered]
For example, I'm copying the build artifacts to the host's path in one of the steps, but I don't want to publicize my server's path, or I want to make woodpecker-ci's configuration more generic. Can I use variables or secrets instead of hardcoding?

```yaml
deploy-to-host:
  image: busybox
  commands:
    - cp -R public /hugo-blog/
  volumes:
    - <MY_HOST_PATH>:/hugo-blog
```
