### DISCUSSION TITLE
Add resoure lock mechanism

### DISCUSSION THREAD

**Discussion by sschnabe** [woodpecker-ci/woodpecker#3383] [Request a Feature] [answered]
I have a service called `dockerd` and a step using this service (on kubernetes agent):

```yaml
services:
  - name: dockerd
    image: plugins/dockerd
    privileged: true
    ports: [2375]
steps:
  docker-cli:
    image: plugins/docker-cli
    environment: [DOCKER_HOST=tcp://dockerd:2375]
    commands: [docker pull rancher/k3s:v1.24.12-k3s1]
```
This works fine for a single workflow. But if multiple workflows are running (e.g. multiple pull requests) all workflows except one are failing because the service already exists. Is there any method to prevent this? E.g. like Gitlab [resource_groups](https://docs.gitlab.com/ee/ci/resource_groups/)?
