### DISCUSSION TITLE
OAuth error - gitlab - cannot authenticate user - possible causes?

### DISCUSSION THREAD

**Discussion by w90** [woodpecker-ci/woodpecker#3388] [Ask a Question]
What works: Woodpecker server, login page on dashboard.
Whats gives error: Redirection after authorizing my application in gitlab (clicking 'Authorize' button and then redirection back to woodpecker server. It show oauth error)

Has anyone else encountered such a problem?

```
{"level":"error","error":"error exchanging token: Post \"https://gitlab.xxxxxxx.com/oauth/token\": EOF","time":"2024-02-13T15:56:19Z","message":"cannot authenticate user"}
```

My server compose config file:
```
version: '3.0'

services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:latest
    ports:
      - 8000:8000
    volumes:
      - woodpecker-server-data:/var/lib/woodpecker/
    restart: always
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_GITLAB=true
      - WOODPECKER_GITLAB_URL=https://gitlab.xxxxxxx.com
      - WOODPECKER_GITLAB_SKIP_VERIFY=true
      - WOODPECKER_SERVER_ADDR=:8000
      - WOODPECKER_HOST=${WOODPECKER_HOST}
      - WOODPECKER_GITLAB_CLIENT=${WOODPECKER_GITLAB_CLIENT}
      - WOODPECKER_GITLAB_SECRET=${WOODPECKER_GITLAB_SECRET}
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_RPC_SECRET}
      - WOODPECKER_DEBUG=true
```

Ubuntu server nginx config:

```
server {
    listen 80;

    server_name ci.xxxxxxx.com;

    location / {
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;

        proxy_pass http://127.0.0.1:8000;
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_buffering off;

        chunked_transfer_encoding off;
    }
}

```
