### DISCUSSION TITLE
Optional `depends_on`

### DISCUSSION THREAD

**Discussion by anbraten** [woodpecker-ci/woodpecker#3416] [Request a Feature]
I quite sometimes would like to have an optional `depends_on` for steps and workflows.

For example sometime I want a step to be only executed in case one of two previous steps were executed.

```yml
steps:
  - name: review deployment
    when:
      - event: pull_request
  
  - name: production deployment
    when:
      - event: tag

  - name: slack
    depends_on:
      - "review deployment"
      - "production deployment"
    image: plugin/...
```

For this it would be helpful to write sth like:

```yml

steps:
  - name: review deployment
    when:
      - event: pull_request
  
  - name: production deployment
    when:
      - event: tag

  - name: slack
    depends_on:
      - name: "review deployment"
        optional: true
      - name: "production deployment"
        optional: true
    image: plugin/...
```
