### DISCUSSION TITLE
Unable to use renovate after v1.0.5

### DISCUSSION THREAD

**Discussion by MichaelSasser** [woodpecker-ci/woodpecker#3459] [Ask a Question]
Hi,

Until Woodpecker CI v1.0.5 I was able to use [renovate](https://github.com/renovatebot/renovate) without any issues. After that, I always get the following output (even with `renovate-config-validator`):

```plain
/bin/sh: 3: cannot create /root/.netrc: Permission denied
```

Has somebody an idea if I can fix this somehow, or is this an issue with woodpecker?

---

### Project settings

- [ ] Allow Pull Requests
- [ ] Protected
- [x] Only inject netrc credentials into trusted containers
- [x] Trusted

(needed for later steps)

### Example Step

```yaml
---
steps:
  validate-config:
    image: renovate/renovate:37.192.4
    environment:
      - LOG_LEVEL=debug
    commands:
      - unset GIT_COMMITTER_NAME GIT_COMMITTER_EMAIL GIT_AUTHOR_NAME GIT_AUTHOR_EMAIL
      - renovate-config-validator
```
