### DISCUSSION TITLE
Powershell and secrets

### DISCUSSION THREAD

**Discussion by Aizekso** [woodpecker-ci/woodpecker#3467] [Ask a Question]
Hi,
I'm using an agent on Windows with a local backend
How to use secrets with Powershell? All methods specified in the documentation do not work. Moreover, if you run it in a container on Linux with Powershell - everything works!

```
steps:
  - name: test1
    image: powershell
    secrets: [ secret1, secret2 ]
    commands: 
      ./script.ps1 $SECRET1 $SECRET2 
```

P.S. $${SECRET1} also don't work
