### DISCUSSION TITLE
how to change `user` with `steps` when use  backend `docker`

### DISCUSSION THREAD

**Discussion by sinlov** [woodpecker-ci/woodpecker#3551] [Ask a Question]
some image not use `root` as user like [python-poetry](https://hub.docker.com/r/fnndsc/python-poetry)

if use [ruff](https://github.com/astral-sh/ruff) to check code will be show error as

```log
error: Failed to initialize cache at /drone/src/.ruff_cache: Permission denied (os error 13)
ruff failed
  Cause: Failed to create temporary file
  Cause: No such file or directory (os error 2) at path "/drone/src/.ruff_cache/0.3.4/.tmpsDbfXr"
```

## why

- beacuse drone/woodpecker run docker as image `USER` settings

- but image [python-poetry](https://hub.docker.com/r/fnndsc/python-poetry)  set user as

```
uid=1000(mambauser) gid=1000(mambauser) groups=1000(mambauser)
```

**This setting is for deployment security reasons, which is understandable, but it will cause trouble during the build process**

## how drone fix this

- just as drone fix can use like this, support `change docker user when run building`

```yml
  - name: python-poetry-check
    image: fnndsc/python-poetry:1.7.1 # https://hub.docker.com/r/fnndsc/python-poetry/tags
    user: root # for image fnndsc/python-poetry:1.7.1 default use `mambauser` can not management file
    commands:
      - whoami
      - id
      - poetry install
      - poetry run ruff check src/ tests/
```

- or build images (`It is not recommended to do this, it is a waste of resources`). And many times, `program files need to be solidified`, and separation of permissions from cache files and configuration files is the correct choice

```Dockerfile
FROM fnndsc/python-poetry:1.7.1

USER root:root
```

## Question

But woodpecker now version `2.4.0` not support change `docker user`
