### DISCUSSION TITLE
Insufficient privileges to use privileged mode - what is missing?

### DISCUSSION THREAD

**Discussion by wsw70** [woodpecker-ci/woodpecker#3565] [Ask a Question]
I am trying to build my first image (and push it to my gitea registry) and after some fumbling I ended up with an error I do not understand:

```
[linter]    woodpecker: steps.build docker image    Insufficient privileges to use privileged mode
```

This is when I try to use the following `.woodpecker.yaml`

```
steps:
  build:
    name: build docker image
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    settings:
      tag: gitea.XXX.YY/wojtek/dash:latest
  push:
    name: push to gitea
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    settings:
      username: wojtek
      password: 
         from_secret: gitea-password
```

**What is missing and where?**

The only vaguely similar issue I found was with Drone and someone suggested to set `DRONE_ADMIN`. I have `WOODPECKER_ADMIN` set to my user (the one that is pushing the repo that includes the config file above<sup>(*)</sup>) in my docker compose file for woodpecker server.

---

<sup>(*)</sup> In other words: there is just one account in Gitea and Woodpecker (mine) and I use it for everything.
