### DISCUSSION TITLE
What is a pipeline, exactly?

### DISCUSSION THREAD

**Discussion by wsw70** [woodpecker-ci/woodpecker#3569] [Ask a Question] [answered]
I am new to Woodpecker and when digging through the documentation and examples I feel a bit lost in the general "pipeline" definition. I also apologize for the emotional rollercoaster below.

When I look at the [tutorial](https://woodpecker-ci.org/docs/intro), I see that a pipeline is 

```yaml
steps:
  - name: build
    image: debian
    commands:
      - echo "This is the build step"
  - name: a-test-step
    image: debian
    commands:
      - echo "Testing.."
```

So there is a section `steps` and then a list of steps with commands  running in containers. perfect.

A bit down I see that the steps can also be plugins:

```yaml
steps:
  deploy-to-k8s:
    image: laszlocloud/my-k8s-plugin
    settings:
      template: config/k8s/service.yaml
```

Hey, where is the list of steps gone? Now instead of a list I have a hash/dict/object... Hmmm, would that mean that I can **either** use a list **or** a dictionary? OK.

I then jump into deep water by running a workflow for a project of mine where I need to build an image from a `Dockerfile` and push the image to my registry on Gitea:

```yaml
steps:
  build:
    name: build docker image
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    settings:
      tag: gitea.XXX.YY/wojtek/dash:latest
  push:
    name: push to gitea
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    settings:
      username: wojtek
      password: 
         from_secret: gitea-password
```

I try this and, crap, there is an error:

```
[generic]           pipeline definition not found
```

<del>WTF?</del> (this was supposed to be humor but it may not be relayed correctly via writing :)) What definition? Of course I ask my friend Google for that and I get [one answer](https://codeberg.org/Codeberg-CI/feedback/issues/96) where the participants discuss about the format of the file - and this terifies me because we are talking about the core of the functionality. This ultimately points to https://github.com/woodpecker-ci/woodpecker/issues/2312 which is a different error 🥸

So back to [the docs](https://woodpecker-ci.org/docs/usage/workflow-syntax) where I see that both a list and a dict are fine. OK this is cleared at least.

But I still do no understand the error above so here I am, asking for help 🙂

One last thing: I REALLY like Woodpecker because it exactly fits the CI/CD I am looking for: simple, straightforward and with a lot of potential (as opposed to the crappy Github Actions or slightly better Gitlab I forgot what  they are called). **So I want to know!!**
