### DISCUSSION TITLE
Docker push error "tag is needed when pushing to registry"

### DISCUSSION THREAD

**Discussion by bestnite** [woodpecker-ci/woodpecker#3642] [Ask a Question]
```
when:
  - event: tag
    ref: refs/tags/v*

steps:
  - name: prepare-tags
    image: bash
    commands:
      - |
        echo "${CI_COMMIT_TAG##v}" > .tags
        if ! echo "${CI_COMMIT_TAG##v}" | grep -Eq -- "-.*\."; then
          echo "latest" >> .tags
        else
          echo "${CI_COMMIT_TAG##v}" | awk -F'[-.]' '{print $4}' >> .tags
        fi
  - name: build
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64
      logins:
        - registry: https://index.docker.io/v1/
          repo: nite07/test
          username: nite07
          password:
            from_secret: docker_password
          tags_file: .tags
        - registry: https://ghcr.io
          repo: nitezs/test-runner
          username: nitezs
          password:
            from_secret: github_token
          tags_file: .tags
```

build failed with exit code 1
```
#1 [internal] booting buildkit
#1 pulling image moby/buildkit:buildx-stable-1
#1 pulling image moby/buildkit:buildx-stable-1 5.2s done
#1 creating container buildx_buildkit_nostalgic_curie0
#1 creating container buildx_buildkit_nostalgic_curie0 1.3s done
#1 DONE 6.6s
ERROR: tag is needed when pushing to registry
time="2024-04-24T14:06:33Z" level=error msg="execution failed: exit status 1"
```

Is there something wrong in my workflow?
