### DISCUSSION TITLE
Dynamic matrix definition

### DISCUSSION THREAD

**Discussion by Kleidukos** [woodpecker-ci/woodpecker#3646] [Request a Feature]
I'd like to suggest that matrices can be generated from a JSON object, which enables CI jobs to be generated from a list of supported compiler versions that lives in the git tree of a project.

In Haskell for instance, project files have a list of supported compiler versions that a tool like [get-tested](https://github.com/Kleidukos/get-tested) parses to produce a list of jobs. 
This is especially useful because there is one authoritative list of supported versions, that informs the CI.

![image](https://github.com/woodpecker-ci/woodpecker/assets/29253044/80172e55-007b-4f32-940d-17be647f9f99)

**Comment by malikwirin** [comment]
For nix there is something similiar to get-tested [nix-github-actions](https://github.com/nix-community/nix-github-actions). I am currently trying to make Woodpecker work with it on [datalad-nix/woodpecker](https://codeberg.org/malik/datalad-nix/src/branch/woodpecker).
A Workflow could look something like this:
``` yaml
steps:
  generate-matrix:
    image: nixos/nix:latest
    environment:
      NIX_CONFIG: "experimental-features = nix-command flakes"
    commands:
      - nix-env -iA nixpkgs.jq nixpkgs.yq
      - mkdir -p .woodpecker
      - nix eval --json '.#githubActions.matrix' > .woodpecker/matrix.json
      - |
        echo "ATTR:" > .woodpecker/matrix.yml
        cat .woodpecker/matrix.json | jq -r '.include[] | .attr' | sed 's/^/  - /' >> .woodpecker/matrix.yml
      - cat .woodpecker/matrix.yml

  build:
    image: nixos/nix:latest
    environment:
      NIX_CONFIG: "experimental-features = nix-command flakes"
    commands:
      - echo "Building ${ATTR}"
      - nix build -L '.#${ATTR}'

matrix:
  from_file: .woodpecker/matrix.yml

when:
  event:
    - pull_request
    - push
```
Of course the matrix.yml file is only available after step 1
