### DISCUSSION TITLE
Docker compose: Gitea+Woodpecker+WPAgent

### DISCUSSION THREAD

**Discussion by timteka** [woodpecker-ci/woodpecker#3651] [Ask a Question]
Hi, can't solve the authorization problem. Here's my compose file:
```yaml
networks:
  gitea:
    external: false

volumes:
  gitea:
    driver: local

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER = git
      - USER_UID = 121
      - USER_GID = 121
      - HTTP_ADDR = 0.0.0.0
    restart: always
    networks:
      - gitea
    volumes:
      - /var/lib/gitea-compose/data:/data
      - /home/git/.ssh/:/data/git/.ssh
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:22"
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:latest
    container_name: woodpecker-server
    restart: always
    ports:
      - 8000:8000
      - 9000:9000
    networks:
      - gitea
    volumes:
      - /var/lib/gitea-compose/woodpecker:/var/lib/woodpecker/
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_HOST=http://10.10.2.31
      - WOODPECKER_SERVER_ADDR=:8000
      - WOODPECKER_GITEA=true
      - WOODPECKER_GITEA_URL=http://10.10.2.31:3000
      - WOODPECKER_GITEA_CLIENT=a7e08042-f03b-4f15-9793-6bf2bedf1c42
      - WOODPECKER_GITEA_SECRET=gto_qncojzjvdc53rwyixzqr3ruu3oab5ekbcxpwj2mphyldrsoy7brq
      - WOODPECKER_AGENT_SECRET=c5704bc389f1e3d47f1c4751d1295c86
      - WOODPECKER_GITEA_SKIP_VERIFY=true
      - WOODPECKER_GRPC_ADDR=:9000

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:latest
    container_name: woodpecker-agent
    command: agent
    depends_on:
      woodpecker-server:
        condition: service_healthy
    networks:
      - gitea
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/gitea-compose/woodpecker-agent:/etc/woodpecker
    environment:
      - WOODPECKER_SERVER=10.10.2.31:9000
      - WOODPECKER_AGENT_SECRET=c5704bc389f1e3d47f1c4751d1295c86
      - WOODPECKER_BACKEND_DOCKER_NETWORK=gitea 
```

**Comment by timteka** [comment]
Clicking on Login button in Woodpecker init page produces:
```
Authorization failed
Unregistered Redirect URI
```

**Comment by timteka** [comment]
The settings of the Application in Gitea:
![image](https://github.com/woodpecker-ci/woodpecker/assets/841560/11cfa10a-eb41-4ea1-8bfd-ba2cc2d492d2)

**Reply by zc-devs** [reply]
In that case `WOODPECKER_HOST` should probably be `http://10.10.2.31:8000`.

**Reply by timteka** [reply]
What was my previous version )) And that's why i've decided to explicitely set port via:
```
WOODPECKER_SERVER_ADDR=:8000
```

**Reply by zc-devs** [reply]
They might be different settings.
Try
```
WOODPECKER_HOST=http://10.10.2.31:8000
WOODPECKER_SERVER_ADDR=:8000
```

**Reply by timteka** [reply]
Still no success:
![image](https://github.com/woodpecker-ci/woodpecker/assets/841560/aa42fc6b-6cd9-4bc9-8019-fb4621fdc15a)
Nothing happens after authorization attempt.
And then timeout with:
2024/04/26 18:10:19 ...eb/routing/logger.go:102:func1() [I] router: completed GET /login/oauth/authorize?client_id=a7e08042-f03b-4f15-9793-6bf2bedf1c42&redirect_uri=http%3A%2F%2F10.10.2.31%3A8000%2Fauthorize&response_type=code&state=woodpecker for 10.10.2.12:53194, **303 See Other** in 8.7ms @ auth/oauth.go:362(auth.AuthorizeOAuth)

**Reply by timteka** [reply]
`Docker inspect` reveals correct WOODPECKER_GITEA_CLIENT and  WOODPECKER_GITEA_SECRET.
Strangeness in exposed ports:
```
"ExposedPorts": {
                "443/tcp": {},
                "80/tcp": {},
                "8000/tcp": {},
                "9000/tcp": {}
            }
```

**Reply by zc-devs** [reply]
> vpn 

> timeout 

requests stuck in the middle / truncated responses / SSL errors

=> check the MTU

**Comment by zc-devs** [comment]
```yaml
networks:
  gitea:
    external: false
```

I wonder, how do you access Gitea and Woodpecker? What do you type in the browser?
Where did you get `10.10.2.31`? Is it your Docker host's IP?

---

Cannot reproduce using Docker host IP.
Tried Gitea site-wide OAuth2 application and user-wide: both work.
[docker-compose.yaml.txt](https://github.com/woodpecker-ci/woodpecker/files/15133481/docker-compose.yaml.txt)
Gitea 1.21.11, Woodpecker 2.4.1, Docker 4.27.2, Windows 10.

**Reply by timteka** [reply]
Thanks for your help....  We use vpn server in our environment, so each VM is connected to it and getting that 10.10.2.x address.
As for your test docker-compose..... i run linux, so only the docker/docker compose are older (e.g. Docker Compose version v2.26.1) and  Docker version 25.0.4.

**Comment by timteka** [comment]
I've tried to setup the same config in VirtualBox. Just Gitea and WP-server. Still the same login failure (with `303 See Other`).

**Reply by qwerty287** [reply]
Is the config above still correct? Because as @zc-devs pointed out, the `WOODPECKER_HOST` *must* be the full user-facing URL, including port etc. And 303 is the correct code after the authorization.

**Reply by timteka** [reply]
Yep. Still the output in Chrome is:
![image](https://github.com/woodpecker-ci/woodpecker/assets/841560/9f187d85-26f8-4069-9fd0-f0bfcd5250f2)

**Reply by qwerty287** [reply]
Well, this and the next request actually seem correct, but then, an error occurred.
Is there something in the logs? Can you give me the request details for the `login?error=oauth_error`?

**Reply by timteka** [reply]
I'll do it later if you don't mind. Some urgent stuff to do.

**Reply by timteka** [reply]
@qwerty287 please import the chrome .har.
[127.0.0.1.har.zip](https://github.com/woodpecker-ci/woodpecker/files/15143475/127.0.0.1.har.zip)

**Comment by timteka** [comment]
My local config in Virtualbox on Win11:
```yaml
networks:
  gitea:
    external: false

volumes:
  gitea:
    driver: local

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER = git
      - USER_UID = 122
      - USER_GID = 122
      - HTTP_ADDR = 0.0.0.0
    restart: always
    networks:
      - gitea
    volumes:
      - /var/lib/gitea-compose/data:/data
      - /home/git/.ssh/:/data/git/.ssh
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3000:3000
      - 2222:22
      
 woodpecker-server:
    image: woodpeckerci/woodpecker-server:latest
    container_name: woodpecker-server
    restart: always
    ports:
      - 8000:8000
      - 9000:9000
    networks:
      - gitea
    volumes:
      - /var/lib/gitea-compose/woodpecker:/var/lib/woodpecker/
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_HOST=http://127.0.0.1:8000
      - WOODPECKER_SERVER_ADDR=:8000
      - WOODPECKER_GITEA=true
      - WOODPECKER_GITEA_URL=http://127.0.0.1:3000
      - WOODPECKER_GITEA_CLIENT=32922d21-012d-4407-9361-fc55323d757e
      - WOODPECKER_GITEA_SECRET=gto_vemy3dfho7y5kq7w6twse6xov7cb7lsfqbistvdd6wsrcjh7gjnq
      - WOODPECKER_GITEA_SKIP_VERIFY=true

```
Below are my network settings:
![image](https://github.com/woodpecker-ci/woodpecker/assets/841560/48a920dc-92a2-40d2-a71d-9288a9831a0f)
