### DISCUSSION TITLE
Stuck on login screen

### DISCUSSION THREAD

**Discussion by gamingdy** [woodpecker-ci/woodpecker#3737] [Ask a Question]
As started here #3689 
I have the same issue but with gitea, I have the following compose file

I know my login and client secret are correct because sometimes it connects me, then suddenly disconnects me and I can't reconnect.

I decided to check the 2.4.1 code locally, but unfortunately I couldn't reproduce the bug, when I start the development environment I can connect without any problem, only the docker image is a problem.

I may have misconfigured something, but I couldn't find it.

Already tried with and without `WOODPECKER_OPEN` set to `true/false/default`

Also tried with mysql as database driver, same issue
```yml
services:
    woodpecker-server:
        container_name: woodpecker_server
        image: woodpeckerci/woodpecker-server:latest
        restart: always
        volumes:
            - ./data/woodpecker-server-data:/var/lib/woodpecker/
        environment:
            - WOODPECKER_LOG_LEVEL=trace
            - WOODPECKER_OPEN=false
            - WOODPECKER_ADMIN=
            - WOODPECKER_GITEA=true
            - WOODPECKER_GITEA_URL=
            - WOODPECKER_GITEA_CLIENT=
            - WOODPECKER_GITEA_SECRET=
            - WOODPECKER_HOST=
            - WOODPECKER_AGENT_SECRET=
        networks:
            - woodpecker
        ports:
            - 8000:8000

    woodpecker-agent:
        image: woodpeckerci/woodpecker-agent:latest
        command: agent
        restart: always
        depends_on:
            - woodpecker-server
        volumes:
            - ./data/woodpecker-agent-config:/etc/woodpecker
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - WOODPECKER_SERVER=woodpecker_server:9000
            - WOODPECKER_AGENT_SECRET=
        networks:
            - woodpecker

networks:
    woodpecker:
```
Log when I try to connect
```
woodpecker_server   | {"level":"trace","time":"2024-05-21T08:41:56Z","caller":"/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/router.go:43","message":"[GET] /login"}
woodpecker_server   | {"level":"debug","ip":"","latency":0.531033,"method":"GET","path":"/login","status":303,"time":"2024-05-21T08:41:56Z","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36","time":"2024-05-21T08:41:56Z","caller":"/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/logger.go:59"}
woodpecker_server   | {"level":"trace","time":"2024-05-21T08:41:56Z","caller":"/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/router.go:43","message":"[GET] /authorize"}
woodpecker_server   | {"level":"debug","ip":"","latency":0.599918,"method":"GET","path":"/authorize","status":303,"time":"2024-05-21T08:41:56Z","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36","time":"2024-05-21T08:41:56Z","caller":"/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/logger.go:59"}
woodpecker_server   | {"level":"trace","time":"2024-05-21T08:41:57Z","caller":"/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/router.go:43","message":"[GET] /authorize?code=code&state=woodpecker"}
woodpecker_server   | {"level":"debug","time":"2024-05-21T08:41:57Z","caller":"/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/login.go:204","message":"synced user permission for admin admin/test"}
woodpecker_server   | {"level":"debug","ip":"","latency":161.482788,"method":"GET","path":"/authorize","status":303,"time":"2024-05-21T08:41:57Z","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36","time":"2024-05-21T08:41:57Z","caller":"/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/logger.go:59"}
woodpecker_server   | {"level":"trace","time":"2024-05-21T08:41:57Z","caller":"/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/router.go:43","message":"[GET] /"}
woodpecker_server   | {"level":"debug","ip":"","latency":0.440463,"method":"GET","path":"/","status":200,"time":"2024-05-21T08:41:57Z","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36","time":"2024-05-21T08:41:57Z","caller":"/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/logger.go:59"}
woodpecker_server   | {"level":"debug","time":"2024-05-21T08:41:57Z","caller":"/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/stream.go:82","message":"user feed: connection closed"}
woodpecker_server   | {"level":"debug","ip":"","latency":346137.119936,"method":"GET","path":"/api/stream/events","status":200,"time":"2024-05-21T08:41:57Z","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36","time":"2024-05-21T08:41:57Z","caller":"/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/logger.go:59"}
woodpecker_server   | {"level":"trace","time":"2024-05-21T08:41:58Z","caller":"/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/router.go:43","message":"[GET] /api/stream/events"}
woodpecker_server   | {"level":"debug","time":"2024-05-21T08:41:58Z","caller":"/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/stream.go:63","message":"user feed: connection opened"}
```

Woodpecker 2.4.1 amd64
Gitea 1.21.11 amd64
Gitea 1.22 amd64

**Comment by zc-devs** [comment]
> WOODPECKER_GITEA_URL=
> WOODPECKER_HOST=

Even current config is not sufficient.

And we have not touched:
```
networks:
    woodpecker:
    proxy-net:
```

Nobody knows your deployment config. You can try to draw it ([example)](https://github.com/woodpecker-ci/woodpecker/files/15209483/wp-schema.drawio.txt) and maybe you will figure it out by yourself.

**Reply by gamingdy** [reply]
I updated the network config with a better example, I don't understand why you quote, what is missing
> WOODPECKER_GITEA_URL=
> WOODPECKER_HOST=

**Reply by zc-devs** [reply]
Because [it matters](https://github.com/woodpecker-ci/woodpecker/issues/3689#issuecomment-2102136973), but yes it `is missing`.

If there would be something like `https://woodpecker.example.org`, then next question is `what is in front of your services (Gitea and WP)`? And its config.

Or I can reword. Suppose, I want to help you. How to reproduce your environment? Can I do it with your current configs? From them I can only say, that you use Gitea somehow.

BTW, Agent have nothing with login flow.

**Reply by gamingdy** [reply]
First I tested with nginx proxy manager, but all the other test was done with direct access to service via http://localhost:port

My gitea config
```yml
services:
    gitea:
        image: gitea/gitea:1.22.0
        container_name: gitea
        env_file:
            - .env.gitea
        restart: always
        ports:
            - "3000:3000"
        networks:
            - gitea
        volumes:
            - ./data/gitea:/data
        depends_on:
            db-gitea:
                condition: service_healthy

    db-gitea:
        container_name: db-gitea
        image: postgres:14
        restart: always
        env_file:
            - .env.gitea-db
        networks:
            - gitea
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 5s
            timeout: 60s
            retries: 5

networks:
    gitea:
```
`.env.gitea`
```
GITEA__database__DB_TYPE=postgres
GITEA__database__HOST=db-gitea:5432
GITEA__database__NAME=
GITEA__database__USER=
GITEA__database__PASSWD=
```

`.env.gitea-db`
```
POSTGRES_USER=
POSTGRES_PASSWORD=
POSTGRES_DB=
```

**Reply by zc-devs** [reply]
1.
> direct access to service via http://localhost:port

So, URLs in your browser looks like `http://localhost:3000` for Gitea and `http://localhost:8000` for Woodpecker, right?

2. 
```yaml
services:
    woodpecker-server:
        networks:
            - woodpecker
    gitea:
        networks:
            - gitea
```

How do they connect?

3. How do your `WOODPECKER_GITEA_URL` and `WOODPECKER_HOST` look like? Or are they really empty?
4. [Gitea's Redirect URI](https://woodpecker-ci.org/docs/administration/forges/gitea#registration) is interesting too.

----

The same questions for `I tested with nginx proxy manager` if you want investigate this use case.

**Reply by gamingdy** [reply]
For the `WOODPECKER_GITEA_URL` I put `http://vm.local:3000`, because it doesn't seem to like localhost as an url,  so just edited my host file with what I want, and `WOODPECKER_HOST=http://vm.local:8000`.

As for the nginx proxy manager, I've put it aside until I solve the main problem.

The network configuration in my compose file is just to make sure that gitea has access to its database, and that my demo agent has access to woodpecker.

Gitea redirect url, I put `http://vm.local:8000/authorize`

**Reply by zc-devs** [reply]
> edited my host file with what I want

What IPs are in there? Which network do they belong?

**Reply by gamingdy** [reply]
I just used my private IP on my network. Something like 192.168.x.x

**Reply by zc-devs** [reply]
Unfortunately, I cannot reproduce this issue.

Windows 10, Docker 25.0.3.

Docker Compose:
```yaml
version: '3'

services:
  gitea:
    image: gitea/gitea:1.22.0
    ports:
        - "3000:3000"
    volumes:
        - ./gitea-data:/data

  woodpecker-server:
    image: woodpeckerci/woodpecker-server:v2.5.0
    environment:
      - WOODPECKER_HOST=http://woodpecker.local:8000
      - WOODPECKER_ADMIN=administrator
      - WOODPECKER_GITEA=true
      - WOODPECKER_GITEA_URL=http://gitea.local:3000
      - WOODPECKER_GITEA_CLIENT=57b82f9b-9060-4bac-9492-90cd378044ad
      - WOODPECKER_GITEA_SECRET=gto_6yox5bhdh2ckfty5ytr4z2yd3k2d7cafv7nhjz6cojruvvjq7pca
      - WOODPECKER_LOG_LEVEL=trace
    ports:
      - 8000:8000
    volumes:
      - ./woodpecker-server-data:/var/lib/woodpecker/
```

Hosts:
```
192.168.43.99    gitea.local
192.168.43.99    woodpecker.local
```
^ (docker) host IP from Wi-Fi network.

Creds:
```
administrator
admin-admin
```

There are volumes data:
[gitea-data.zip](https://github.com/user-attachments/files/15522647/gitea-data.zip)
[woodpecker-server-data.zip](https://github.com/user-attachments/files/15522648/woodpecker-server-data.zip)

[Screenshot oAuth client](https://github.com/woodpecker-ci/woodpecker/assets/127358482/659b584c-b022-4614-8038-912030a6b621)
[Screenshot WP logged in](https://github.com/woodpecker-ci/woodpecker/assets/127358482/dfef95de-13e6-461f-b76d-a4c6604309a8)

HTTP archives:
[woodpecker.local_hars.zip](https://github.com/user-attachments/files/15522646/woodpecker.local_hars.zip)
first login with accepting oAuth application.

You can try to compare my configs and HARs with yours. Hope, you'll find something and resolve your issue.
