### DISCUSSION TITLE
Sending Emails through gmail

### DISCUSSION THREAD

**Discussion by amino-8** [woodpecker-ci/woodpecker#3742] [Ask a Question]
I used to have email working fine with the email plugin but since an update, it now requires a DSN. I'm having trouble getting it working again for 2 reasons:
1 - I get an error saying the gmail bridge is not installed - "Unable to send emails via "gmail" as the bridge is not installed. Try running "composer require symfony/google-mailer"."
2 - I'm not sure if I have the secrets syntax correct

The email part of my pipeline is below
```
  mail:
    image: deblan/woodpecker-email
    settings:
      dsn: "gmail+smtp://$MYEMAIL:$GMAILPASS@default"
      from: me@omaramin.me
      from.name: Woodpecker
      subject: >
        [{{ build.status }}]
        {{ repo.owner }}/{{ repo.name }}
        ({{ build.branch }} - {{ truncate build.commit 8 }}) 
      recipients_only: true
      recipients:
        - me@myemail.com 
    secrets:
    - source: myemail
      target: myemail
    - source: gmailpass
      target: gmailpass   
```

Has anyone got this working?
