### DISCUSSION TITLE
Build container and use it in pipeline

### DISCUSSION THREAD

**Discussion by dR3b** [woodpecker-ci/woodpecker#3851] [Ask a Question]
How can I build a container (plugin-docker-buildx) and use it in the next step?

```
when:
  - event: [push]

steps:
  build:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: foo/bar
      tags: latest
      dry-run: true
  run:
    image: foo/bar:latest
```

Error:
```
pull access denied for foo/bar repository does not exist or may require docker login...
```
Thanks!

**Comment by qwerty287** [comment]
Could you try what's listed in the docs? They're using the `docker` image instead of the buildx plugin.

https://woodpecker-ci.org/docs/usage/registries#local-images

**Reply by dR3b** [reply]
I am not an admin, so i can't use this suggestion.

**Comment by zc-devs** [comment]
```
steps:
  build: # build a container (plugin-docker-buildx)
    image: woodpeckerci/plugin-docker-buildx
    settings:
      registry: example.com # and push it to some registry
      repo: example.com/foo/bar
      tags: latest
      username: example_user
      password:
        from_secret: example_passwd
  run: # use it in the next step
    image: example.com/foo/bar:latest
    pull: true
```

**Reply by dR3b** [reply]
I wanted to prevent myself from filling up a registry with useless images.

**Reply by zc-devs** [reply]
Doesn't your registry support garbage collection? 👀

**Comment by pat-s** [comment]
You'd need to 

1. Save the image locally instead of pushing it to a registry
2. Persist the image in a location shared between steps
3. Move the local image to the location where docker looks for images in step `run`
4. If docker finds it there, it will use it instead of trying to pull it

Alternatively, don't use the buildx plugin but use raw `docker` commands (e.g. by using `dind`) and then chain the next command in the same step so you do not have to persist the image between steps.

(Not sure if all of this is worth it instead of pushing/pulling to a remote registry.)

**Comment by anbraten** [comment]
Would be crazy if the following would work. Issue is I think that the registry can't be easily accessed from the docker host.

```yml
steps:
  - name: build # build a container (plugin-docker-buildx)
    image: woodpeckerci/plugin-docker-buildx
    settings:
      registry: my-registry
      repo: foo/bar
      tags: latest
  - name: run # use it in the next step
    image: my-registry/foo/bar:latest # We would need to get access to the registry from the agent here somehow
    pull: true

services:
  - name: my-registry
    image: registry:2
```
