### DISCUSSION TITLE
Is it possible to use different image depending on the platform?

### DISCUSSION THREAD

**Discussion by voidcontext** [woodpecker-ci/woodpecker#3881] [Ask a Question] [answered]
What would be the best approach to use different image for a step based in the platform? Let's say `some-image` on `linux/amd64` and `aarch64/some-image` when it's `linux/arm64`.

**Comment by voidcontext** [comment, marked as answer]
Actually I think I found a solution, it might not be the best but it seems it works well:

```yaml
matrix:
  include:
    - platform: linux/amd64
      image: some-image
    - platform: linux/aarch64
      image: aarch64/some-image

labels:
  platform: ${platform}

steps:
  release:
    image: ${image}
    settings:
      ...
```
