### DISCUSSION TITLE
Alternative to setting environment variables for plugin steps

### DISCUSSION THREAD

**Discussion by Lunrtick** [woodpecker-ci/woodpecker#3964] [Ask a Question]
I see [this pull request ](https://github.com/woodpecker-ci/woodpecker/pull/3909) has been released in 2.7, which now prevents defining environment variables for plugins.

I'm trying to build/bundle my frontend code as a step in my pipeline, and I currently inject a config secret through an environment variable. Is there a recommended way to handle this scenario now?

```yaml
steps:
  build-frontend:
    image: codeberg.org/woodpecker-plugins/node-pm
    directory: frontend
    when:
      - branch: [master]
    settings:
      run: build
      with: pnpm
      frozen_lockfile: true
      ignore_node_modules: true
    environment:
      VITE_MAPPING_API_KEY:
        from_secret: mapping_api_secret
```
