### DISCUSSION TITLE
Deprecate secrets section

### DISCUSSION THREAD

**Discussion by lafriks** [woodpecker-ci/woodpecker#4015] [General]
There is imho not really much sense to have two ways to do the same thing and there has already been too much magic with secrets uppercase/lowercase etc, can't be used with plugins also, so imho it should be deprecated and removed in future in favor of `from_secret` syntax

**Comment by xoxys** [comment]
How would use cases like this https://woodpecker-ci.org/docs/next/usage/secrets#use-secrets-in-commands work then? Also, after we made it impossible to set `environment` on plugins anymore this is the only remaining way to pass additional secrets that must be set as env var to a plugin.

**Reply by lafriks** [reply]
```yaml
secrets:
  - docker_username
```

is pretty much equal to:

```yaml
environment:
  docker_username:
    from_secret: docker_username
```

**Reply by xoxys** [reply]
As I said this doesnt work for plugins anymore.

**Reply by lafriks** [reply]
Setting environment variables with plugins is different topic and same as secrets should be reviewed how to allow them securely

**Reply by xoxys** [reply]
Ok, as you asked for opinions, my vote is: keep it.

**Reply by lafriks** [reply]
But leaving aside plugins (I think secrets should be treated the same as env anyway from security perspective).

What is the benefit of having multiple ways to do the same thing?

**Reply by xoxys** [reply]
We can not permanently leave things aside.

We should not deprecate features that are used and without an alternative solution. Right now, there __is__ no other way to pass custom envs to plugins anymore. Envs don't work anymore with the latest release and people are already asking for guidance ... If we can't provide alternative solutions, stop deprecating stuff.

> I think secrets should be treated the same as env anyway from security perspective

Why? Secrets can only be set by admins, no need to dictate admins what env vars they are allowed to set.

**Reply by zc-devs** [reply]
> guidance

If I understand correctly, plugins are set up via `settings` only (now). So, guidance is simple: push the plugin's maintainers to add required settings/options :) But again it is just my perception.

**Reply by xoxys** [reply]
I don't see any value in this behavior to be honest. If someone has the rights to change env vars in a CI config, the one can also change the entire step or add a new one. In this new step, everything can be executed again. Why we try to prevent to set any env var manually in plugins is unclear to me...

**Reply by lafriks** [reply]
Because plugins can expose secrets that otherwise would be protected by plugin functionality

**Reply by zc-devs** [reply]
```yaml
environment:
  docker_username:
    from_secret: docker_password
  docker_username: johnny
```
at least it looks similar to Kubernetes
```yaml
containers:
- envFrom:
  - configMapRef:
        name: gitea
  - secretRef:
        name: gitea
```
```yaml
containers:
- env:
  - name: BACKEND_USERNAME
    valueFrom:
      configMapKeyRef:
        name: backend-user
        key: backend-username
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db-pwd
        key: db-pwd
```
https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/
https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/
