### DISCUSSION TITLE
How do I get a pipeline to run?

### DISCUSSION THREAD

**Discussion by MI3Guy** [woodpecker-ci/woodpecker#4029] [Ask a Question] [answered]
I've have
- Installed woodpecker
- Setup four agents, which can be seen in the admin section of the UI
- Logged in through Gitea
- Added my repo
- Added a pipeline file named `.woodpecker/build.yaml` to the repo and pushed it to Gitea

I've tried triggering manually, but that doesn't seem to do anything.

All it says is "No pipelines have been started yet."

I also see no relevant information in the logs.

Here's the `build.yaml`:

```
when:
  - event: push
    branch: master

steps:
  - name: build-wasm
    image: "ocaml/opam:debian-12-ocaml-4.14"
    commands:
      - opam install dune
      - eval $(opam env) && cd webassembly-spec/interpreter && make
  - name: build
    image: "eclipse-temurin:22-jdk"
    commands: "./gradlew build"
```
