### DISCUSSION TITLE
Can you check out multiple repositories for a Gradle composite build?

### DISCUSSION THREAD

**Discussion by nightm4re94** [woodpecker-ci/woodpecker#4382] [Ask a Question] [answered]
Basically I have a setup where I'm using Gradle composite build to pull a library into my build.
Locally, this works by having my main project and the library checked out in the same parent directory and adding `includeBuild ("../myLibrary")` in the main project's `settings.gradle`.
 Is it possible to have multiple clone steps in a woodpecker pipeline so I can use composite build in the CI pipeline as well?

**Comment by zc-devs** [comment, marked as answer]
The only one special `clone` step can be defined in a workflow:
```yaml
clone:
  git:
    image: woodpeckerci/plugin-git
clone:
  git:
    image: woodpeckerci/plugin-git
steps:
  build:
    image: alpine
    commands:
      - echo 'Build'
  test:
    image: alpine
    commands:
      - echo 'Test'
```
![Screenshot 2024-11-16 1](https://github.com/user-attachments/assets/dbc7b8c5-2a55-4071-b269-1f54a5aeac61)

But you can use `clone` plugin or image with `git` in so many steps, how you want:
```yaml
steps:
  clone-deps:
    image: woodpeckerci/plugin-git
    settings: ...
  build:
    image: alpine
    commands:
      - echo 'Build'
  test:
    image: alpine
    commands:
      - echo 'Test'
  push-back:
    image: alpine/git
    commands: ...
```
![Screenshot 2024-11-16 2](https://github.com/user-attachments/assets/36137df1-9e52-4da7-9d1e-900e7b526540)

---

> main project and the library checked out in the same parent directory and adding includeBuild ("../myLibrary") in the main project's settings.gradle

Consider to use git submodules.

**Reply by nightm4re94** [reply]
thanks a lot, I'll try this setup.

**Reply by nightm4re94** [reply]
I was able to get it running with this configuration:
``` yaml
steps:
  clone-litiengine:
    image: woodpeckerci/plugin-git
    settings:
      remote: "https://github.com/gurkenlabs/litiengine.git"
      ref: "main"
      path: "$CI_WORKSPACE/../../litiengine"
  build:
    image: eclipse-temurin:23
    commands:
      - ./gradlew build
```
