### DISCUSSION TITLE
Running tests on linux and windows

### DISCUSSION THREAD

**Discussion by johanvdw** [woodpecker-ci/woodpecker#4472] [Ask a Question] [answered]
Hi all, I've been keeping an eye for a while on woodpecker, and I'm trying to convert our drone setup.

However, we're hitting issues once we try to add a windows agent to the mix.

So we had eg this flow which worked fine:

```
steps:
  - name: unit-tests
    image: registry.fluves.net/drone/pydas/venv-3.11
    commands:
      - tox 

```
After I added a windows agent (compiled from the Dockerfile at https://github.com/GECO-IT/woodpecker-windows?tab=readme-ov-file )

---
labels:
  platform: windows/amd64
  backend: docker
steps:
  - name: install package & run tests
    image: xxx/drone/win_venv311:ltsc2022
    commands:
      - tox -e py
---

Also the linux agent jobs fail. Do I need to specify anything specific in those pipelines?
