### DISCUSSION TITLE
Unnecessary platform checks on the kubernetes agent

### DISCUSSION THREAD

**Discussion by ztelliot** [woodpecker-ci/woodpecker#4521] [Ask a Question]
Hi, on the latest `next-6e18a44880` version I noticed that the pipeline won't run when there is no agent for the target platform, so that I have to run agents on all nodes for all platforms.

In previous versions (I'm not sure which commit caused this issue), the server doesn't check the correspondence between the pipeline platform and the agent platform, the platform value is just passed to Kubernetes, which does the selection of the nodes.

I don't think it's necessary for the server to do this checking, Kubernetes already does it.

Thanks.

**Comment by pat-s** [comment]
I can't reproduce this. Can you show an exemplary config?

Using latest next, with one agent on `arm64`, forcing a build on `amd64` works just fine.

```yaml
[...]
    backend_options:
      kubernetes:
        nodeSelector:
          kubernetes.io/arch: amd64
```
