### DISCUSSION TITLE
Is possible to reference variables inside messages?

### DISCUSSION THREAD

**Discussion by klinux** [woodpecker-ci/woodpecker#4937] [Ask a Question]
Example, I'm using drone git push plugin, in the commit message:

`commit_message: "[skip ci] Update do connect server image version."`

I want to reference the variable ***app_version** in the message, this is possible?

Thank you

**Comment by qwerty287** [comment]
I don't think yaml allows this.

**Comment by anbraten** [comment]
@klinux What kind of variable do you want `app_version` to be / like where do you expect to define it?

**Reply by klinux** [reply]
Hello @anbraten 

The idea is use something like that

I have here the variable:

```
variables:
  - &app_version '0.0.1'
  ...
```

And in the step **commit-version**

```
  commit-version:
    image: appleboy/drone-git-push:1.0
    settings:
      branch: main
      remote: ${CI_REPO_CLONE_SSH_URL}
      ssh_key:
        from_secret: ssh_key
      author_name: <OMMITED>
      author_email: <OMMITED>
      force: false
      commit: true
      commit_message: "[skip ci] Update the version: *app_version"

    backend_options:
      <<: *backend_options
```

**Reply by albertyw** [reply]
I was able to work around this by setting the yaml variable as an environment variable and using that, i.e.

```yaml
variables:
  - &app_version '0.0.1'
steps:
  test:
    environment:
      APP_VERSION: *app_version
    commands:
      - echo $app_version
      - git commit "$app_version"
```

I'm not sure if it works with the `settings` config in your step though.
