### DISCUSSION TITLE
Use named volumes with Docker

### DISCUSSION THREAD

**Discussion by cgalo5758** [woodpecker-ci/woodpecker#5095] [Request a Feature] [answered]
I have the following publish.yaml:

```
when:
  - event: push
    branch: main

steps:
  build:
    image: hugomods/hugo:base
    commands:
      - build
    volumes:
      - public:/site
```

It unfortunately results in the following error:
>`linter` **publish:** steps.build
>
>Insufficient trust level to use `volumes`

Is there no support for [named volumes](https://docs.docker.com/engine/storage/volumes/#named-and-anonymous-volumes) or are only bind mounts supported?

**Comment by anbraten** [comment]
Using volumes in general requires the repo to be [trusted](https://woodpecker-ci.org/docs/next/usage/project-settings#trusted) by an admin. 

AFAIK only bind mounts are currently supported: https://github.com/woodpecker-ci/woodpecker/blob/131d4afd1d5f936141f211dbb9041967b31c289e/pipeline/backend/docker/docker.go#L204

**Reply by cgalo5758** [reply]
I am a little confused about this. Are you saying I can use named volumes if the repo is trusted AND only bind mounts are supported? My apologies if I am missing something obvious.

**Reply by qwerty287** [reply]
No, you can't use named volumes currently. I'll convert this into a feature request

**Reply by cgalo5758** [reply, marked as answer]
Wait a minute. I just tried it and it is working?

This is what I have:

Simple hugo deployment `compose.yaml` using swarm
```
services:
  site:
    image: hugomods/hugo:nginx-1.27.4
    networks:
      - proxy
    volumes:
      - public:/site

networks:
  proxy:
    external: true

volumes:
  # This becomes `wiki-cafe-site_public` because swarm prepends the stack name to the volume.
  public:
```

And my workflow definition `.woodpecker/publish.yaml`
```
when:
  - event: push
    branch: main

steps:
  build:
    image: hugomods/hugo:base-0.146.5
    commands:
      - ls -la /
      - pwd
      - hugo build --destination /site
    volumes:
      - wiki-cafe-site_public:/site
```
