### DISCUSSION TITLE
Why does docker buildx plugin not connect to docker daemon?

### DISCUSSION THREAD

**Discussion by n1cc00** [woodpecker-ci/woodpecker#5272] [Ask a Question]
Hello, 
I have the same issue that was described here:
https://github.com/woodpecker-ci/woodpecker/issues/4140
The solution proposed by @qwerty287 doesn't apply in my case though, I don't have "secrets" configured. Here is my workflow:

```yaml
steps:
  - name: docker-build
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64
      registry: ...
      repo: ...
      tags:
        - ${CI_COMMIT_TAG}
      username:
        from_secret: REGISTRY_USER
      password:
        from_secret: REGISTRY_PASS
```

In my docker compose, I configured the plugin privileges like this:
WOODPECKER_PLUGINS_PRIVILEGED=woodpeckerci/plugin-docker-buildx

Does anyone have an idea what I might be doing wrong?

EDIT: Its not just the plugin. This step also fails:
```yaml
  - name: debug-docker
    image: docker:24
    commands:
      - docker version
```

**Comment by pat-s** [comment]
You don't need a dedicated daemon, the plugin has its own, respectively re-uses the one from the agent.

In the end there is not enough information about your env to be able to help you but the buildx plugin usually works OOB in a k8s install via the helm chart.

**Reply by n1cc00** [reply]
Thanks for your answer, the problem is not the plugin itself, as other steps depending on the docker daemon also fail (see my EDIT in the question).
Woodpecker is running in a docker compose stack with pretty much the default configuration. If I understand it right, the daemon mounting has to be working because otherwise the pipeline run wouldn't even start, right? Also, on the same system, I mounted the daemon on various services without problems. Here is my compose:
```yaml
services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:v3
    ports:
      - 8778:8000
    volumes:
      - /volume1/docker/woodpecker/server-data:/var/lib/woodpecker/
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_HOST=${WOODPECKER_HOST}
      - WOODPECKER_GITEA=true
      - WOODPECKER_GITEA_URL=...
      - WOODPECKER_GITEA_CLIENT=...
      - WOODPECKER_GITEA_SECRET=...
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
      - WOODPECKER_PLUGINS_PRIVILEGED=woodpeckerci/plugin-docker-buildx
      - WOODPECKER_GLOBAL_SECRET_KEY=...
      - WOODPECKER_BACKEND=docker

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:v3
    user: root
    command: agent
    restart: always
    depends_on:
      - woodpecker-server
    volumes:
      - /volume1/docker/woodpecker/agent-config:/etc/woodpecker
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WOODPECKER_SERVER=woodpecker-server:9000
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
      - WOODPECKER_BACKEND=docker
    dns:
      - 192.168.90.50
``` 
If you need more information, let me know
