### ISSUE TITLE
Replace plugin auto-detection with some kind of config file

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#1034]
We currently use the Github api to find all public repos of the woodpecker org by using `org:woodpecker-ci topic:woodpecker-plugin fork:true` as search term. This restricts us to only list plugins from one forge (Github) atm and also makes it difficult to allow plugins which are not part of the `woodpecker-ci` org (see #859).

Proposal:
To be more flexible I would suggest to replace this functionality and use a simple yaml config file instead. To get the same information we currently show following config file format could be used:

```yml
plugins:
  - repoUrl: https://github.com/woodpecker-ci/plugin-surge-preview
    docsUrl: https://raw.githubusercontent.com/woodpecker-ci/plugin-surge-preview/main/docs.md
    official: true # show a blue checkmark on the plugin list that this plugin can be trusted (add hint to all others to use at on own risk)
```

The docs url would link to a txt file with a format like this (already used):

[Source](https://raw.githubusercontent.com/woodpecker-ci/plugin-surge-preview/main/docs.md)

```md
---
name: Surge preview plugin
authors: Woodpecker Authors
icon: https://woodpecker-ci.org/img/logo.svg
description: Plugin to create static pages deployments as preview environments on pull-requests.
tags: [publish, cdn, preview]
image: woodpeckerci/plugin-surge-preview
---

The surge-preview plugin [...]

## Usage

[...]
```
