### ISSUE TITLE
Certain environment variables (and their values) prevent pipelines to be triggered

### ISSUE THREAD

**Issue by x80486** [woodpecker-ci/woodpecker#1041]
### Component

server, agent, web-ui

### Describe the bug

I have a very simple pipeline:

```yaml
pipeline:
  validate:
    commands:
      - docker-compose config --quiet
    environment:
      GROUP_ID: 1000
      USER_ID: 1000
    group: verify
    image: docker.io/docker/compose:alpine-1.29.2
```

This configuration prevents `Woodpecker CI` to trigger the pipeline.

The fix is to enclose the values from `environment` in double quotes.

> The pipeline just tests that the `Docker Compose` manifest/definition file is correct, so any valid `docker-compose.yaml` file can be used to test this.

### System Info

```shell
Codeberg's Woodpecker CI
```

### Additional context

I usually test all the steps that `Woodpecker CI` will execute locally using a multi-stage `Dockerfile`. I understand that while it's not exactly the same (for all purposes), it does work (for me) for almost 95% of the cases.

So I execute this in my local PC using `Docker Compose` and it doesn't fail — either using the integers or double quoted values. That's why I'm inclined to think it could be an issue with `Woodpecker CI` and not the `docker.io/docker/compose:alpine-1.29.2` image itself.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).
