### ISSUE TITLE
Share Data across Steps / Get latest Git Tag

### ISSUE THREAD

**Issue by Tert0** [woodpecker-ci/woodpecker#1042]
Is there currently a way to share data(e.g. Environment Variables) across steps, if not is this a planned feature?
Or is there an other way to get the latest Git Tag of a Repo and use it in an other step as e.g. Environment Variable?
My simplest Idea how to achive that:
```yaml
pipeline:
  get-tag:
    image: alpine
    export: GIT_TAG # not implemented
    commands:
      - apk add --no-cache git
      - export GIT_TAG=$(git tag | sort -V | tail -1)
  build-docker-image:
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    import: get-tag.GIT_TAG  # not implemented
    settings:
      registry: docker.example.org
      repo: docker.example.org/myimage
      tags: latest
      dockerfile: Dockerfile
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      platforms: 
        - amd64
      pull_image: true
      build_args:
        - VERSION=${GIT_TAG}
```
