### ISSUE TITLE
Panic if Plugin not found

### ISSUE THREAD

**Issue by mawoka-myblock** [woodpecker-ci/woodpecker#1053]
### Component

agent

### Describe the bug

If the specified plugin isn't found, there is a panic listed in the logs, instead of a simple `Plugin wasn't found`

### System Info

```shell
Codeberg-CI
```

### Additional context

```shell
Drone Git Push Plugin built from e1d0995
panic: EOF

goroutine 1 [running]:
panic(0x72e740, 0xc82000a100)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/drone-plugins/drone-git-push/vendor/github.com/drone/drone-go/plugin.MustParse()
	/drone/src/github.com/drone-plugins/drone-git-push/vendor/github.com/drone/drone-go/plugin/plugin.go:132 +0x59
main.main()
	/drone/src/github.com/drone-plugins/drone-git-push/main.go:33 +0x44a

```
This has been the error telling me that the plugin `drone-git-push` hasn't been found, which isn't ideal.
```


### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by 6543** [comment]
@mawoka-myblock can you point us to the pipeline config?

**Comment by mawoka-myblock** [comment]
There you go:
```yaml
pipeline:
  build:
    image: node:18
    commands:
      - corepack enable
      - corepack prepare pnpm@7.7.0 --activate
      - pnpm i
      - pnpm build
      - rm .gitignore
      - echo -e '!build\n*\n.*'  > .gitignore

  publish:
    image: plugins/drone-git-push
    settings:
      remote: codeberg.org
      branch: deploy
      ssh_key:
        from_secret: SSH_KEY
```

The problem is that the plugin is called `git-push`, but I've entered `drone-git-push`. After I've fixed that, it worked.
