### ISSUE TITLE
Docu: steps can be map **or list**

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#1119]
we support
```yaml
pipeline:
  echo:
    image: debian
    commands:
      - echo hello
```
and
```yaml
pipeline:
  - name: echo
    image: debian
    commands:
      - echo hello
```

keep in mind name is optional if not added step will be numerated

-> #826
