### ISSUE TITLE
Labels are ignored on the dev version of the agent

### ISSUE THREAD

**Issue by fauust** [woodpecker-ci/woodpecker#1128]
**Warning:** This is probably normal since the problem appears only with the dev version of the agent.

### Component

server, agent

### Describe the bug

As explained on matrix, labels are not working in my setup and I was suggested to open an issue here.

Here is my agent env:

```
WOODPECKER_FILTER_LABELS=type=exec
WOODPECKER_SERVER=localhost:9000
WOODPECKER_AGENT_SECRET=secret
WOODPECKER_MAX_PROCS=1
WOODPECKER_HEALTHCHECK=false
WOODPECKER_BACKEND=local
```

Started with `go run ./cmd/agent --log-level debug` from the master branch (f21d8541).

And here is my pipeline as suggested by https://woodpecker-ci.org/docs/administration/backends/local#using-labels-to-filter-tasks:

```yml
labels:
  type: exec

pipeline:
[...]
```

The exec agent refuse to execute the pipeline and the other docker agent (configured with docker-compose) is always selected.
Here is the configuration of the docker-compose agent:

```yml
[...]
woodpecker-agent:
  image: woodpeckerci/woodpecker-agent:latest
  restart: unless-stopped
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    - WOODPECKER_FILTER_LABELS=type=docker
    - WOODPECKER_SERVER=woodpecker:9000
    - WOODPECKER_AGENT_SECRET=secret
    - WOODPECKER_MAX_PROCS=1
```

### System Info

```shell
Debian Bullseye
docker-ce: 20.10.17~3-0~debian-bullseye
docker-compose: 1.29.2
woodpecker-agent from f21d8541 commit
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).
