### ISSUE TITLE
Exit code 141 with local agent when logs exceed certain size

### ISSUE THREAD

**Issue by fauust** [woodpecker-ci/woodpecker#1144]
### Component

server, agent, web-ui

### Describe the bug

Pipeline steps will systematically fail with `exit code 141` if the log size is over something between `2063600` and `2079000` bytes.

Here is how to test it.

The following pipeline will work:
```yml
pipeline:
  logs exec:
    image: bash
    commands:
      - bash -c "for i in {1..134}; do base64 /dev/urandom | head -n 200; done"
```

The following pipeline will **not** work (`exit code 141`):
```yml
pipeline:
  logs exec:
    image: bash
    commands:
      - bash -c "for i in {1..135}; do base64 /dev/urandom | head -n 200; done"
```

`2063600 - 2079000` bytes range is given by:
```bash
for i in {1..134}; do base64 /dev/urandom | head -n 200; done >limit.log
stat --format="%s" limit.log
2063600
for i in {1..135}; do base64 /dev/urandom | head -n 200; done >limit.log
stat --format="%s" limit.log
2079000
```

This problem does not appear with docker agent, for instance, the following pipeline works without pb:

```yml
pipeline:
  generate log:
    image: debian:11-slim
    commands:
      - bash -c "for i in {1..400}; do base64 /dev/urandom | head -n 200; done"
```

**But** then, the log file seems to be trunkated to `2000000` bytes and it's impossible to download the full log from the web interface.

### System Info

Server:
```console
❯ docker images | grep woodpecker-server
woodpeckerci/woodpecker-server   next                abdf33e30acc   35 hours ago   24.1MB
```

Local agent:
Run from commit 08a99152, with `go run ./cmd/agent --log-level debug`

Docker agent:
```console
❯ docker images | grep woodpecker-agent
woodpeckerci/woodpecker-agent    next                374ee61b7354   35 hours ago   13.3MB
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).
