### ISSUE TITLE
Gitea login endless loop

### ISSUE THREAD

**Issue by H4CK3R-01** [woodpecker-ci/woodpecker#1148]
### Component

server, web-ui

### Describe the bug

If I try to login into gitea I get redirected to my gitea instance at the first time. There I can authorise woodpecker and then I get redirected back to my woodpecker instance. But again to the login view (/do-login). The next time I try to login the page refreshes only but nothing happens

Another server with the same config but connected to github is working fine.

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"0.15.3"}

I'm using docker-compose.
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by 6543** [comment]
is it possible for you to test against `next` tag?

**Comment by H4CK3R-01** [comment]
Yes. Unfortunately the same mistake.
```
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-c79d49c8"}
```

**Comment by H4CK3R-01** [comment]
Maybe you have a working docker-compose config for gitea and woodpecker?

**Comment by 6543** [comment]
https://woodpecker-ci.org/docs/next/administration/setup#docker-compose and https://woodpecker-ci.org/docs/next/administration/forges/gitea I would say?

**Comment by H4CK3R-01** [comment]
This is exactly the documentation I used. But this does not work :-(

**Comment by 6543** [comment]
just to make sure can you post the full config (secrets redacted)?

**Comment by H4CK3R-01** [comment]
My `docker-compose.yml`-file
```
version: '3'

services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:next
    restart: unless-stopped
    volumes:
      - woodpecker_server_data:/var/lib/woodpecker/
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    environment:
      - WOODPECKER_LOG_LEVEL=${WOODPECKER_LOG_LEVEL}
      - WOODPECKER_DEBUG_PRETTY=${WOODPECKER_DEBUG_PRETTY}
      - WOODPECKER_DEBUG_NOCOLOR=${WOODPECKER_DEBUG_NOCOLOR}
      - WOODPECKER_ADMIN=${WOODPECKER_ADMIN}
      - WOODPECKER_ORGS=${WOODPECKER_ORGS}
      - WOODPECKER_OPEN=${WOODPECKER_OPEN}
      - WOODPECKER_GITEA=${WOODPECKER_GITEA}
      - WOODPECKER_GITEA_URL=${WOODPECKER_GITEA_URL}
      - WOODPECKER_GITEA_CLIENT=${WOODPECKER_GITEA_CLIENT}
      - WOODPECKER_GITEA_SECRET=${WOODPECKER_GITEA_SECRET}
      - WOODPECKER_HOST=${WOODPECKER_HOST}
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
      - WOODPECKER_DATABASE_DRIVER=mysql
      - WOODPECKER_DATABASE_DATASOURCE=${DATABASE_USER}:${DATABASE_PASSWORD}@tcp(${DATABASE_HOST}:3306)/${DATABASE_DB}?parseTime=true
      - WOODPECKER_PROMETHEUS_AUTH_TOKEN=${WOODPECKER_PROMETHEUS_AUTH_TOKEN}
    networks:
      default:
        ipv4_address: ${IP_SERVER}

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:latest
    restart: unless-stopped
    depends_on:
      - woodpecker-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    environment:
      - WOODPECKER_SERVER=${IP_SERVER}:9000
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
    networks:
      default:
        ipv4_address: ${IP_AGENT}

networks:
  default:
    external:
      name: ens18_net

volumes:
  woodpecker_server_data:
```

And the `.env`-file
```
IP_SERVER=10.0.1.156
IP_AGENT=10.0.1.157

WOODPECKER_LOG_LEVEL=debug
WOODPECKER_DEBUG_PRETTY=true
WOODPECKER_DEBUG_NOCOLOR=false
WOODPECKER_ADMIN=H4CK3R-01
WOODPECKER_ORGS=
WOODPECKER_OPEN=true
WOODPECKER_GITEA=true
WOODPECKER_GITEA_URL=https://git.<domain>.com
WOODPECKER_GITEA_CLIENT=<client-id>
WOODPECKER_GITEA_SECRET=<client-secret>
WOODPECKER_HOST=https://gitea.woodpecker.<domain>.com
WOODPECKER_AGENT_SECRET=<agent-secret>

DATABASE_USER=woodpecker
DATABASE_PASSWORD=<password>
DATABASE_HOST=mariadb
DATABASE_DB=woodpecker_gitea
WOODPECKER_PROMETHEUS_AUTH_TOKEN=
```
