### ISSUE TITLE
gitea remote url disappears - fatal: no path specified

### ISSUE THREAD

**Issue by sb-child** [woodpecker-ci/woodpecker#1169]
### Component

agent

### Describe the bug

i am using woodpecker:next docker image and configured for my gitea instance:
```yml
# docker-compose.yml 
version: '3'
networks:
  put_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - 
          subnet: 172.18.0.0/24
          gateway: 172.18.0.1

services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:next
    networks:
      put_net:
        ipv4_address: 172.18.0.2
    extra_hosts:
      - "n3s1.sbc-io.xyz:10.7.1.4"
    ports:
      - 8999:8000
    expose:
      - "9000"
    volumes:
      - woodpecker-server-data:/mnt/m1/wpdata
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_HOST=https://woodpecker.example:3944
      - WOODPECKER_GITEA=true
      - WOODPECKER_GITEA_URL=https://gitea.example:3943/
      - WOODPECKER_GITEA_CLIENT=0c7d543a-b70a-461c-bb06-ef32c912789c
      - WOODPECKER_GITEA_SECRET=gto_secret
      - WOODPECKER_AGENT_SECRET=secretexample
      - WOODPECKER_DATABASE_DRIVER=postgres
      - WOODPECKER_DATABASE_DATASOURCE=postgres://woodpecker_u:passwd@172.17.0.1:5432/woodpecker_db?sslmode=disable
      - WOODPECKER_AUTHENTICATE_PUBLIC_REPOS=true
      - WOODPECKER_DEFAULT_CLONE_IMAGE=woodpeckerci/plugin-git:next
      - WOODPECKER_ADMIN=WoodpeckerBot

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:next
    networks:
      put_net:
        ipv4_address: 172.18.0.3
    extra_hosts:
      - "gitea.example:10.7.1.4"
    command: agent
    restart: always
    depends_on:
      - woodpecker-server
    links:
      - woodpecker-server
    tmpfs:
      - /tmp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WOODPECKER_SERVER=woodpecker-server:9000
      - WOODPECKER_AGENT_SECRET=secretexample

volumes:
  woodpecker-server-data:
```

now there is a private repo in the list:
![图片](https://user-images.githubusercontent.com/55868015/188775456-d470def8-f780-46b8-a92b-07654fc90fe6.png)

but Pipelines are failing:
```
+ git init -b main
Initialized empty Git repository in /woodpecker/src/gitea.example/main-mirrors-private/proj/.git/
+ git remote add origin 
+ git fetch --no-tags origin +refs/heads/main:
fatal: no path specified; see 'git help pull' for valid url syntax
exit status 128
```
i found that remote url is gone:
`+ git remote add origin *[remote url]*` on line 3 above

after execute `Repair repository` on settings, I can restart this pipeline without issues:
```
+ git init -b main
Initialized empty Git repository in /woodpecker/src/gitea.example/main-mirrors-private/proj/.git/
+ git remote add origin https://gitea.example:3943/main-mirrors-private/proj.git
+ git fetch --no-tags origin +refs/heads/main:
From https://gitea.example:3943/main-mirrors-private/proj
 * branch            main       -> FETCH_HEAD
 * [new branch]      main       -> origin/main
+ git reset --hard -q 7905a6e4214a2969b5106a19806e6c56442675e9
+ git submodule update --init --recursive
```
but after I push a new commit to trigger CI, the new pipeline failed:
```
+ git init -b main
Initialized empty Git repository in /woodpecker/src/gitea.example/main-mirrors-private/proj/.git/
+ git remote add origin 
+ git fetch --no-tags origin +refs/heads/main:
fatal: no path specified; see 'git help pull' for valid url syntax
exit status 128
```

logs:
```
wp-conf-woodpecker-agent-1   | {"level":"error","error":"io: read/write on closed pipe","time":"2022-09-07T02:47:06Z","message":"copy limited logStream part"}
wp-conf-woodpecker-agent-1   | {"level":"error","error":"rpc error: code = Unknown desc = Proc finished with exitcode 128, ","time":"2022-09-07T02:47:07Z","message":"grpc error: wait(): code: Unknown: rpc error: code = Unknown desc = Proc finished with exitcode 128, "}
wp-conf-woodpecker-agent-1   | {"level":"warn","repo":"main-mirrors-private/repo","build":"21","id":"61","error":"rpc error: code = Unknown desc = Proc finished with exitcode 128, ","time":"2022-09-07T02:47:07Z","message":"cancel signal received"}
```

### System Info

```shell
https://woodpecker.example:3944/version
{
  "source":"https://github.com/woodpecker-ci/woodpecker",
  "version":"next-05d660f2"
}

Docker Compose version v2.6.0
```

### Additional context

logs:
```
wp-conf-woodpecker-agent-1   | {"level":"error","error":"io: read/write on closed pipe","time":"2022-09-07T02:47:06Z","message":"copy limited logStream part"}
wp-conf-woodpecker-agent-1   | {"level":"error","error":"rpc error: code = Unknown desc = Proc finished with exitcode 128, ","time":"2022-09-07T02:47:07Z","message":"grpc error: wait(): code: Unknown: rpc error: code = Unknown desc = Proc finished with exitcode 128, "}
wp-conf-woodpecker-agent-1   | {"level":"warn","repo":"main-mirrors-private/repo","build":"21","id":"61","error":"rpc error: code = Unknown desc = Proc finished with exitcode 128, ","time":"2022-09-07T02:47:07Z","message":"cancel signal received"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).
