### ISSUE TITLE
Can't use `branch` condition with `when` for gitea

### ISSUE THREAD

**Issue by RealStickman** [woodpecker-ci/woodpecker#1182]
### Component

server

### Describe the bug

Filters based on branch names can't get a match match for gitea and never execute.  
I've only tested this with the `create` event, so others might work.  

Here's the full pipeline config I created.  
```
pipeline:
  build:
    image: python:latest
    when:
      event: tag
      branch: main
    commands:
      - python --version
      - pip install -U build --quiet
      - python -m build

  upload:
    image: python:latest
    when:
      event: tag
      branch: main
    secrets: [ twine_username, twine_password ]
    commands:
      - pip install -U twine --quiet
      - python -m twine upload --skip-existing --repository testpypi -u $TWINE_USERNAME -p $TWINE_PASSWORD dist/*
```
I also tested `branch: [ main, master ]` without success.  
Removing the `branch` condition makes the pipeline run when a tag is created.  

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"0.15.4"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).
