### ISSUE TITLE
Agent not triggered

### ISSUE THREAD

**Issue by MQSchleich** [woodpecker-ci/woodpecker#1187]
### Component

agent, web-ui

### Describe the bug

I was configuring `woodpecker-ci` to work with Gitea locally. 

- Both are deployed on two different servers. 
- Gitea has SSL 
- Woodpecker is not setup for SSL 

Setup went clean.

- I can connect `woodpecker` with `Gitea
- Webhook is triggered 

**Yet the agent does not execute and is idle (even after the timeout interval)**

The `docker-compose.yml` is configured according to the manual as follows: 
```yml
version: '3.5'

services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:v0.15.3
    ports:
      - 80:80
      - 443:443
      - 9000:9000
    networks:
      - woodpecker
    volumes:
      - woodpecker-server-data:/var/lib/woodpecker/
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_GITEA=true
      - WOODPECKER_SERVER_ADDR=:80
      - WOODPECKER_LETS_ENCRYPT=${WOODPECKER_LETS_ENCRYPT}
      - WOODPECKER_HOST=${WOODPECKER_HOST}
      - WOODPECKER_ADMIN=${WOODPECKER_ADMIN}
      - WOODPECKER_ORGS=${WOODPECKER_ORGS}
      - WOODPECKER_REPO_OWNERS=${WOODPECKER_REPO_OWNERS}
      - WOODPECKER_GITEA_URL=${WOODPECKER_GITEA_URL}
      - WOODPECKER_GITEA_CLIENT=${WOODPECKER_GITEA_CLIENT_ID}
      - WOODPECKER_GITEA_SECRET=${WOODPECKER_GITEA_CLIENT_SECRET}
      - WOODPECKER_AGENT_SECRET="${WOODPECKER_AGENT_SECRET}"

      - WOODPECKER_DATABASE_DRIVER=sqlite3
      - WOODPECKER_DATABASE_DATASOURCE=/var/lib/woodpecker/woodpecker.sqlite
      - WOODPECKER_DEBUG=true

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:latest
    command: agent
    restart: always
    depends_on:
      - woodpecker-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WOODPECKER_SERVER=woodpecker-server:9000
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}


networks:
  woodpecker:
    name: woodpecker_network

volumes:
  woodpecker-server-data:
```

### System Info

```shell
- woodpeckerci/woodpecker-server:v0.15.3
- woodpeckerci/woodpecker-agent:latest
- RaspberryOS 64bit
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by 6543** [comment]
They are printed to stdout

**Comment by MQSchleich** [comment]
The error is somewhat logical 

```bash
agent_from_doc-woodpecker-agent-1   |
 {"level":"error","error":"rpc error: code = Unavailable desc = connection error: desc = \"transport: 
Error while dialing dial tcp: lookup woodpecker-server on 127.0.0.11:53: no such host\"","time":"2022-09-15T14:09:50Z","message":"grpc error: done(): code: 
Unavailable: rpc error: code = Unavailable desc = connection error: 
desc = \"transport: Error while dialing dial tcp: lookup woodpecker-server on 127.0.0.11:53: no such host\""}
```

**Comment by 6543** [comment]
First i would use same tag vor server and agent, as that can cause problems otherwhise ...

And the issue you face is some sort of docker/docker-compose one. docker can not resolve the server to an ip address, you might add a hostname into docker-compose 

https://stackoverflow.com/questions/29924843/how-do-i-set-hostname-in-docker-compose

**Comment by MQSchleich** [comment]
Good idea, yet following the suggestion yields the same error as above. Implementing the docs with `localhost` seems like a step forward but throws 
```bash
agent_from_doc-woodpecker-agent-1   | {"level":"error","error":"rpc error: code = Unavailable
 desc = connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:9000: connect: connection
refused\"","time":"2022-09-17T22:09:26Z","message":"grpc error: done(): code: Unavailable: rpc error: code = Unavailable 
desc = connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:9000: connect: connection refused\""}

```

**Comment by 6543** [comment]
Can you update the docker-compose at tje issue desc. to the current one

**Comment by MQSchleich** [comment]
It might be some socker or port issue.

```yaml
version: '3.5'

services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:v0.15.3
    ports:
      - 80:80
      - 443:443
      - 9000:9000
    networks:
      - woodpecker
    volumes:
      - woodpecker-server-data:/var/lib/woodpecker/
      - /var/run/docker.sock:/var/run/docker.sock
    hostname: woodpecker
    restart: always
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_GITEA=true
      - WOODPECKER_SERVER_ADDR=:80
      - WOODPECKER_LETS_ENCRYPT=${WOODPECKER_LETS_ENCRYPT}
      - WOODPECKER_HOST=${WOODPECKER_HOST}
      - WOODPECKER_ADMIN=${WOODPECKER_ADMIN}
      - WOODPECKER_ORGS=${WOODPECKER_ORGS}
      - WOODPECKER_REPO_OWNERS=${WOODPECKER_REPO_OWNERS}
      - WOODPECKER_GITEA_URL=${WOODPECKER_GITEA_URL}
      - WOODPECKER_GITEA_CLIENT=${WOODPECKER_GITEA_CLIENT_ID}
      - WOODPECKER_GITEA_SECRET=${WOODPECKER_GITEA_CLIENT_SECRET}
      - WOODPECKER_AGENT_SECRET="${WOODPECKER_AGENT_SECRET}"

      - WOODPECKER_DATABASE_DRIVER=sqlite3
      - WOODPECKER_DATABASE_DATASOURCE=/var/lib/woodpecker/woodpecker.sqlite
      - WOODPECKER_DEBUG=true

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:latest
    command: agent
    restart: always
    depends_on:
      - woodpecker-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WOODPECKER_SERVER=localhost:9000
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}


networks:
  woodpecker:
    name: woodpecker_network

volumes:
  woodpecker-server-data:

```

**Comment by MQSchleich** [comment]
Okay, after fiddling around with the networks, I got that working up to another error message. I am not sure how to solve this yet, but I am sure I it can be fixed. 

```yaml
version: '3.5'

services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:v0.15.3
    ports:
      - 80:80
      - 443:443
      - 9000:9000
    networks: 
      default:
        ipv4_address: "172.50.0.11"
    volumes:
      - woodpecker-server-data:/var/lib/woodpecker/
      - /var/run/docker.sock:/var/run/docker.sock
    hostname: woodpecker
    restart: always
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_GITEA=true
      - WOODPECKER_SERVER_ADDR=:80
      - WOODPECKER_LETS_ENCRYPT=${WOODPECKER_LETS_ENCRYPT}
      - WOODPECKER_HOST=${WOODPECKER_HOST}
      - WOODPECKER_ADMIN=${WOODPECKER_ADMIN}
      - WOODPECKER_ORGS=${WOODPECKER_ORGS}
      - WOODPECKER_REPO_OWNERS=${WOODPECKER_REPO_OWNERS}
      - WOODPECKER_GITEA_URL=${WOODPECKER_GITEA_URL}
      - WOODPECKER_GITEA_CLIENT=${WOODPECKER_GITEA_CLIENT_ID}
      - WOODPECKER_GITEA_SECRET=${WOODPECKER_GITEA_CLIENT_SECRET}
      - WOODPECKER_AGENT_SECRET="${WOODPECKER_AGENT_SECRET}"

      - WOODPECKER_DATABASE_DRIVER=sqlite3
      - WOODPECKER_DATABASE_DATASOURCE=/var/lib/woodpecker/woodpecker.sqlite
      - WOODPECKER_DEBUG=true

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:latest
    command: agent
    restart: always
    depends_on:
      - woodpecker-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WOODPECKER_SERVER=woodpecker:9000
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
    networks:
      default:
        ipv4_address: "172.50.0.12"
    extra_hosts: 
      - "woodpecker:172.50.0.11"


networks:
  default:
    ipam: 
      config:
        - subnet: "172.50.0.0/24"
          gateway: "172.50.0.1"

volumes:
  woodpecker-server-data:

```
