### ISSUE TITLE
Webhooks: cannot find config '' in 'refs/heads/master' with user: 'user' when sending web hooks from gitea

### ISSUE THREAD

**Issue by thallosaurus** [woodpecker-ci/woodpecker#1202]
### Component

server

### Describe the bug

Hello,

Given the .woodpecker.yml file in [1], every time my Gitea instance sends a web hook to the defined URL set by woodpecker, the request fails with
```
cannot find config '' in 'refs/heads/master' with user: 'rillo'
```

and therefore doesn't trigger a build.

My woodpecker runs behind a nginx proxy server configured according to the manual.

Is this an error with my configuration or a bug on woodpeckers side?

Thanks in advance

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"0.15.4"}
```

### Additional context

[1]
```
#.woodpecker.yml
clone:
  git:
    image: plugins/git
    depth: 1
pipeline:
  build:
    image: docker:20.10.16 # fix at least major here
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - echo $DOCKER_PASSWORD | docker login registry.cyberpsych0si.is -u $DOCKER_USERNAME --password-stdin
      - docker build -t registry.example.com/dns .
      - docker push registry.example.com/dns
    secrets: [ docker_username, docker_password ]
```

Woodpecker Log Output:
```
{"level":"debug","error":"context deadline exceeded","repo":"rillo/dns","time":"2022-09-22T16:08:26Z","caller":"/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/hook.go:184","message":"cannot find config '' in 'refs/heads/master' with user: 'rillo'"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).
