### ISSUE TITLE
Does when: tag: require* works?

### ISSUE THREAD

**Issue by iamsudip** [woodpecker-ci/woodpecker#125]
My steps are still getting executed even if the tag doesn't starts with `require`

Trigger is only on git tag events.

My config:
```
---
pipeline:
  propensity-base-build:
    image: plugins/ecr
    repo: image-repo
    context: ./
    dockerfile: ./commons/Dockerfile.base
    tags:
      - propensity-base
    when:
      tag: require*
  propensity-build:
    image: plugins/ecr
    repo: image-repo
    context: ./
    dockerfile: ./commons/Dockerfile
    tags:
      - ${DRONE_COMMIT_SHA:0:8}
      - propensity-${DRONE_TAG}
      - latest
```

**Comment by laszlocph** [comment]
Not as documented. I will update the docs, meanwhile you can try matching on the `ref`

```
pipeline:
  step1:
    when:
      event: push
      ref: [ refs/heads/feature/*, refs/tags/* ]
      event: [ push, tag ]
```

as per

https://discourse.drone.io/t/execute-a-build-step-only-when-a-feature-branch-is-tagged-with-a-specific-pattern/1237/3
