### ISSUE TITLE
Sub-steps

### ISSUE THREAD

**Issue by qwerty287** [woodpecker-ci/woodpecker#1269]
### Clear and concise description of the problem

It's not possible to run multiple steps in one container.

### Suggested solution

Add something like "sub-steps" that run in the same container, but are separated in UI.

**Comment by 6543** [comment]
no we do have the commands already as string slice ... we just have to restructure how backend works - I'm already on it

**Comment by 6543** [comment]
I'm for closing this!

-> KISS

**Comment by anbraten** [comment]
@qwerty287 Could you explain your use case?

Why can't you run:

```yml
pipeline:
  one:
    image: golang
    commands:
      - go build
      - go test
```

**Comment by 6543** [comment]
:point_up:

**Comment by anbraten** [comment]
So to split it you would need to write the following for now I guess:

```yml
pipeline:
  one:
    image: golang
    commands:
      - go build
  two:
    image: golang
    commands:
      - go test
```
