### ISSUE TITLE
Use System font stack instead "Avenir"

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#1316]
I'd like to see this "Avenir" custom font removed and instead a standard [system font stack](https://systemfontstack.com/) to be used. Benefits are a consistent experience across multiple apps that also use system font stack, as well as faster load times and no flash of wrong fonts. See [here](https://github.com/go-gitea/gitea/blob/ba0a0d31c97a1cfc4f163bdd32b1749c4ddc74a5/web_src/less/_base.less#L3-L5) for an example.

_Originally posted by @silverwind in https://github.com/woodpecker-ci/woodpecker/issues/468#issuecomment-1206219108_

**Comment by silverwind** [comment]
I recommend something like this. Fonts are based on Bootstrap:

```css
:root {
  --fonts-proportional: system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", "Noto Sans", "Liberation Sans", Arial, sans-serif, var(--fonts-emoji);
  --fonts-monospace: SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace, var(--fonts-emoji);
  --fonts-emoji: "Apple Color Emoji", "Segoe UI Emoji", "Noto Color Emoji", "Twemoji Mozilla";
}

body, textarea {
  font-family:var(--fonts-regular);
}

pre, code, kbd, samp {
  font-family: var(--fonts-monospace);
  font-size: .9em;  /* compensate for monospace fonts being usually slightly larger */
}
```
