### ISSUE TITLE
Add support to import env file in pipeline steps

### ISSUE THREAD

**Issue by dvjn** [woodpecker-ci/woodpecker#1348]
### Clear and concise description of the problem

Many projects use some .env (or .dev.env, .prod.env, etc) files for managing variables.
It would be nice if woodpecker would support importing these variables directly into steps.

### Suggested solution

Proposed syntax (same as docker compose)
```yaml

pipeline:
  some_step:
    image: some-image
    commands:
      - do something
    env_file: .env

  some_plugin_step:
    image: my-build-plugin
    settings:
      foo: bar
    env_file:
      - .build.env
      - .env
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.
