### ISSUE TITLE
RFC: pipeline compile step

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#1400]
Add a own section called `compile` into pipeline config.

witch use normal workflow logic (default or custom clone) ... but it's output is no log but an pipeline config.

tldr: with way we could support **starlark**, jsonnet (#1396), drone >= 1.0, ... without needing to add it to woodpecker core

## details
we either could make a special compile pipeline, and show it as own entry, witch trigger the actual pipeline with its config
(if we do so, we need to somehow link them UI/UX wise ...)
or we just use our multi workflow approach ... where one workflow (eventually with a different icon) is the compile and all generated workflows from it are also i it ... (as a compile could create one or more workflows)

we need to make sure we dont have a recursion in it -> see permutate example

## example:
```yaml
compile:
  image: wp/jsonnet
  settings:
    file: woodpecker.jsonnet
```
```yaml
compile:
  image: wp/replace-image # permutate normal wp pipeline config

pipeline:
  normal-steps:
...
```
