### ISSUE TITLE
invalid reference format when using variable in image

### ISSUE THREAD

**Issue by pitwegner** [woodpecker-ci/woodpecker#1406]
### Component

server

### Describe the bug

After building a new image in my pipeline, I want to use it in the following step (using my semver image to version itself). I tried the following config:
```yaml
services:
   docker:
     image: docker:18-dind
     command: [ "--storage-driver=vfs", "--tls=false" ]
     privileged: true

pipeline:
  build:
    image: docker:18
    commands:
      - docker build -t $IMAGE:$CI_COMMIT_SHA .
      - docker push $IMAGE:$CI_COMMIT_SHA
    environment:
      - DOCKER_HOST=tcp://docker:2375
      - IMAGE=<repo>/semantic-release

  version:
    image: <repo>/semantic-release:$CI_COMMIT_SHA
    commands:
      - semantic-release
```

Coming from Gitlab CI, I expected this to work. However, the step fails and produces "Proc finished with exitcode 1, Error response from daemon: invalid reference format" in the logs. I checked that the image is actually there and also that the registry credentials are configured.

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"0.15.5"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).
