### ISSUE TITLE
Improve ingress/reverse proxy support

### ISSUE THREAD

**Issue by roggenbrot** [woodpecker-ci/woodpecker#1429]
### Clear and concise description of the problem

While playing around with woodpecker and Kubernetes I'm running in redirect and web UI problems when trying to set up woodpecker with a custom context path .

What I'm trying to setup

![setup](https://user-images.githubusercontent.com/41467575/202699728-d3e7a7f7-cce9-46e0-b04b-267cc2de9928.png)

I'm running into a lot of problems because a lot of paths in the UI and also all login redirect from the server are absolute:

- Logout always redirects to `https://local.cluster/logout`
- Login always redirects to `https://local.cluster/login`
- Icons in UI are broken (Wrong URL)
- API calls are broken (Wrong URL: `https://local.cluster/api`)

In a normal reverse proxy environment the redirects should be no problem (Rewrite), with Ingress it seems that this is not supported/possible.

Examples for absolute paths can be found in Additional Context

### Suggested solution

Setting a dynamic base path in `index.html` and refactor all absolute paths to relative paths:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <base href="{{ .base }}" />
  <link rel="alternate icon" type="image/png" href="./favicons/favicon-light-default.png" id="favicon-png" />
  <link rel="icon" type="image/svg+xml" href="./favicons/favicon-light-default.svg" id="favicon-svg" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="theme-color" content="#65a30d" />
  <title>{{ .title }}</title>
  <script type="" src="./web-config.js"></script>
</head>
<body>
  <div id="app"></div>
  <script type="module" src="/src/main.ts"></script>
</body>
</html>
```

Inject the base href in the index.html

server/web/web.go
```go
func handleIndex(c *gin.Context) {
  c.HTML(200, "index.html", gin.H{
    "base":  server.Config.Server.Path + "/",
    "title": server.Config.Server.PageTitle,
  })
}
```

`server.Config.Server.Path` could be calculated from `server.Config.Server.Host` (or maybe overwritten by CLI option)

cmd/server/server.go
```go
serverURL, err := url.Parse(c.String("server-host"))
if err != nil {
   panic(err)
}
server.Config.Server.Path = serverURL.Path
```

Redirects are prefixed with new path:

server/api/login.go
```go
c.Redirect(303, server.Config.Server.Path+"/login?error=oauth_error")
```

#### Absolute UI paths:

https://github.com/woodpecker-ci/woodpecker/blob/1786c0554a3f347924a0a1d36c8b2684eb45ac86/web/index.html#L5
https://github.com/woodpecker-ci/woodpecker/blob/1786c0554a3f347924a0a1d36c8b2684eb45ac86/web/index.html#L6
https://github.com/woodpecker-ci/woodpecker/blob/1786c0554a3f347924a0a1d36c8b2684eb45ac86/web/index.html#L10
https://github.com/woodpecker-ci/woodpecker/blob/1786c0554a3f347924a0a1d36c8b2684eb45ac86/web/src/compositions/useAuthentication.ts#L15

and more ...

#### Absolute redirect paths:

https://github.com/woodpecker-ci/woodpecker/blob/1786c0554a3f347924a0a1d36c8b2684eb45ac86/server/api/login.go#L55
https://github.com/woodpecker-ci/woodpecker/blob/1786c0554a3f347924a0a1d36c8b2684eb45ac86/server/api/login.go#L71
https://github.com/woodpecker-ci/woodpecker/blob/1786c0554a3f347924a0a1d36c8b2684eb45ac86/server/api/login.go#L81

and more ...

#### Ingress configuration for woodpecker

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "woodpecker"
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "local.cluster"
    cert-manager.io/cluster-issuer: "cluster-selfsigned"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
spec:
  tls:
    - hosts:
      - local.cluster
      secretName: "cluster-tls"
  rules:
    - host: "local.cluster"
      http:
        paths:
          - path: "/woodpecker(/|$)(.*)"
            pathType: ImplementationSpecific
            backend:
              service:
                name: "woodpecker"
                port:
                  number: 8000
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.
