### ISSUE TITLE
Woodpecker pipeline script ignores exit code from subshell

### ISSUE THREAD

**Issue by svdHero** [woodpecker-ci/woodpecker#1464]
### Component

other

### Describe the bug

I have the following `.woodpecker.yml` file:

```yml
pipeline:
  my-step:
    image: debian:bullseye-slim
    commands:
      - echo "Do one thing."
      - (ls /this-directory-does-not-exist; exit 0)
      - echo "Do something else."
```

The pipeline run fails with error message
```
ls: cannot access '/this-directory-does-not-exist': No such file or directory
```
which I don't understand, since the subshell `(...)` exits with status code `0`.

Other CI systems, such as Jenkins or Azure DevOps, honor subshell exit status codes. Am I doing something wrong? Are subshells not supported by Woodpecker?

### System Info

```shell
{
    "source":"https://github.com/woodpecker-ci/woodpecker",
    "version":"next-86e49851"
}
```

### Additional context

![image](https://user-images.githubusercontent.com/24250824/205004147-92bc9a09-a4de-43d9-a5a2-16cad67a71d8.png)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).
