### ISSUE TITLE
Add key `failOnStderr` to yaml pipeline schema

### ISSUE THREAD

**Issue by svdHero** [woodpecker-ci/woodpecker#1465]
### Clear and concise description of the problem

As a user of Woodpecker I would like to be able to set a boolean parameter `failOnStderr` for each pipeline step that makes the step fail if any of the listed commands print anything to stderr. In some scenarios that can be useful for catching warnings that are not reflected by a command's exit code.

Right now, the following pipeline succeeds:

```yml
pipeline:
  my-step:
    image: debian:bullseye-slim
    commands:
      - echo "Do one thing."
      - echo "Booooom. Bad error!" 1>&2
      - echo "Do something else."
```

### Suggested solution

Add the boolean parameter `failOnStderr` to the yaml pipeline schema, such that
```yml
pipeline:
  my-step:
    image: debian:bullseye-slim
    failOnStderr: false
    commands:
      - echo "Do one thing."
      - echo "Booooom. Bad error!" 1>&2
      - echo "Do something else."
```
would succeed, but
```yml
pipeline:
  my-step:
    image: debian:bullseye-slim
    failOnStderr: true
    commands:
      - echo "Do one thing."
      - echo "Booooom. Bad error!" 1>&2
      - echo "Do something else."
```
would fail.

Also compare the [Bash Task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/bash-v3?view=azure-pipelines) for Azure DevOps Pipelines which offers this feature.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.
