### ISSUE TITLE
Conditional pipeline execution

### ISSUE THREAD

**Issue by JohnKiller** [woodpecker-ci/woodpecker#1487]
### Clear and concise description of the problem

Ability to put `when` block at pipeline level so that in a multi-pipeline scenario we can skip an entire pipeline if the conditions are not met

### Suggested solution

Allow to put `when` block also at pipeline or root level

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by gapodo** [comment]
Are you searching for something other than the [global pipeline conditions](https://woodpecker-ci.org/docs/next/usage/pipeline-syntax#when---global-pipeline-conditions)?

If so, how would your supposed yaml look like?

**Comment by JohnKiller** [comment]
> Are you searching for something other than the [global pipeline conditions](https://woodpecker-ci.org/docs/next/usage/pipeline-syntax#when---global-pipeline-conditions)?
> 
> If so, how would your supposed yaml look like?

Hi, thank you very much, I didn't see that it was already supported. However, I can't get it to work.

This yaml works:

```
pipeline:
  build_base:
    image: plugins/docker
    settings:
      repo: gitea.example.com/infra/docker-base
      registry: gitea.example.com
      tag: latest
      dockerfile: base/Dockerfile
      context: base
    when:
      branch: master
      event: push
      path:
        include:
          - "base/**/*"
```

but this doesn't:

```
when:
  branch: master
  event: push
  path:
    include:
      - "base/**/*"

pipeline:
  build_base:
    image: plugins/docker
    settings:
      repo: gitea.example.com/infra/docker-base
      registry: gitea.example.com
      tag: latest
      dockerfile: base/Dockerfile
      context: base
```

I'm running v0.15.5 and Gitea 1.17.3 and I want to run this pipeline only when any file in the subdirectory "base" is changed. The first one always clones the repository but skips the step. The second one always runs everything. This is why I thought it wasn't supported
