### ISSUE TITLE
Duplicate mount point step error

### ISSUE THREAD

**Issue by lafriks** [woodpecker-ci/woodpecker#1495]
### Component

agent

### Describe the bug

After some time/conditions steps start to fail with error: `Error response from daemon: Duplicate mount point: /etc/ssl/certs` and can be resolved only by restarting docker service woodpecker is running on.

### System Info

Version:

```json
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-fc4af44b"}
```

Agent deployment:

```yaml
  woodpecker-runner:
    image: woodpeckerci/woodpecker-agent:next-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/ssl/certs:/etc/ssl/certs:ro
    networks:
      - woodpecker_internal
    environment:    
      - WOODPECKER_SERVER=woodpecker-server:9000
      - WOODPECKER_AGENT_SECRET=<redacted>
      - WOODPECKER_MAX_PROCS=4
      - WOODPECKER_HOSTNAME=${HOSTNAME}
      - WOODPECKER_BACKEND_DOCKER_VOLUMES=/etc/ssl/certs:/etc/ssl/certs:ro,/etc/docker/certs.d:/etc/docker/certs.d:ro
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).
