### ISSUE TITLE
allow for setting variables for future steps from within a step

### ISSUE THREAD

**Issue by gapodo** [woodpecker-ci/woodpecker#1504]
### Clear and concise description of the problem

Sometimes a lot of work has to be done to prepare environment variables for their future use, while I can mostly do this within the step (just run some commands, potentially even from a yaml variable), it becomes problematic when using plugins, as they don't (usually) support running commands in their environment before running.

This problem currently affects me the most with the plugin-docker-buildx, where we need to prepare some build-args to be passed into the plugin. Though it would also ease many other things I'm currently doing in pipelines.

### Suggested solution

Allow a step to export variables for use in the following steps, this could be done by either providing a way to write them to a file, which is injected as environment in the following steps, or by an explicit mechanism (i.e. calling a specific command, which woodpecker reacts to).

To properly steer / control this, a flag within the step should exist, which either allows "any" exports, or take the variable names, which are exported to the next steps.

a short (likely not syntactically correct) idea... just as a discussion start
I've left out the "normal" options (this should just be an add-on)
```yaml
pipeline:
  # potentially some steps that run before
  # a step which is allowed to provide any keys...
  standard_env:
    image: some/image
    allow_export: true
    commands:
      - what ever prepares and exports the needed key-value pairs
  
  # a step that is just allowed to provide specific keys
  debugging_env:
    image: some/other:image
    allow_exports:
      - DEBUGGING_FLAGS
      - GOPROXY
    commands:
      - ......
  
  # potentially some other steps

  # use the variables provided by previous steps
  use_env:
    image: what/ever
    include_env_from:
      standard_env: # filter values to include from standard_env
        - OUR_TAG
        - SOME_OTHER_VALUE
      debugging_env # include anything provided by debugging_env

  # use prepared variables in a step, where "normal" processing isn't possible
  use_plugin:
    image: some/plugin
    include_env_from:
      - standard_env # include all variables provided by standard_env
    settings:
      tag: $${OUR_TAG}
      label: $${SOME_OTHER_VALUE}
```

While being able to also use the variables directly (within the pipeline yaml and not the executed image) would be nice, I believe this could overcomplicate things.

### Alternative

This could also be implemented in a more hands off way, by providing a second mountpoint (additional to the normal working directory), which a step can write into a file, which could then be included in the starting-script of steps (by woodpecker)...

Basic example (as always, just the addition and usecase, may not be valid yaml as I'm just quickly typing this up in the browser...)
```yaml

env_export_mount: /env_export

pipeline:
  standard_env:
    image: ...
    export_mount: true
    commands:
      - echo "somekey=value" > /env_export/standard_env
  
  debugging_env:
    image: ...
    export_mount: true
    commands:
      - echo "debug=trace" > /env_export/debugging_env
  
  using_env:
    image: ...
    include_env:
      - standard_env # include_env would load this file into the env of the container (this should likely be done by the backend)
      - debugging_env
  
  plugin:
    image: some/plugin
    include_env:
      - standard_env # this is where the backend handling injection is important, as plugins would need to be modified otherways
    settings:
      tag: $${somekey} # this should(TM) be evaluated within the plugin, though this is where the agent doing the work would be nice for ensuring it also works in env-less containers (single binary)
```

The first approach would IMHO be more solid, while this one would likely be easier to implement (except the potential issue with plugins), though it could potentially be "bodged" by just running an additional command in the [script_<os>.go](https://github.com/woodpecker-ci/woodpecker/blob/master/pipeline/backend/common/script_posix.go#L44) / [script.go](https://github.com/woodpecker-ci/woodpecker/blob/master/pipeline/backend/common/script.go#L35)

### Additional context

Some other CIs have this feature either by design (explicitly implemented for the purpose) or by happy accident (e.g. Gitlab-CI when not using containers, as steps share the env...).

Being able to prepare variables becomes especially important, when using plugins that are privileged, as the user cannot replace them easily with something that prepares the env as he needs it (esp. so when used in a shared setting like e.g. at Codeberg or in a company/community setting, where devs should not be allowed to declare their own things as privileged).

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.
