### ISSUE TITLE
Multiline Secret does not work

### ISSUE THREAD

**Issue by maurerle** [woodpecker-ci/woodpecker#1561]
### Component

server, cli

### Describe the bug

I created a secret using:

`woodpecker secret add -repository me/testrepo -name SSH_ED25519 -value @/root/privatekey`

according to the [secrets docs](https://woodpecker-ci.org/docs/usage/secrets)
That worked fine.
Yet connecting with this key does not.
woodpecker.yml:

```
pipeline:
  deploy-app:
    image: alpine:latest
    privileged: true
    commands:
      - apk add --update openvpn openssh-client
      - echo $SSH_ED25519 > privatekey
      - ssh -i privatekey -o StrictHostKeyChecking=no root@myserver "echo hello"
```

so i added a `sleep 600` to the woodpecker.yml, ran the pipeline again and executed the container using:

`docker exec -it 0_3056348731034984128_step_0 sh`

inside the container i ran `env` which showed everything just fine with a multiline:
![image](https://user-images.githubusercontent.com/25026204/213908642-e5db4ed1-9f13-414b-92cd-888a4909cfa0.png)

but running `echo $SSH_ED25519 > privatekey` prints it as a single line.

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"0.15.6"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by maurerle** [comment]
As alpine is using busybox, print behaves differently.

Using prinft helped here. But one needs to add quotes for the multiline string:
https://stackoverflow.com/a/32371729

A pipeline to connect to OpenVPN and run a command on that server as a deployment can be seen here:

```yaml
pipeline:
  deploy-app:
    image: alpine:latest
    privileged: true
    commands:
      - apk add --update openvpn openssh-client
      - printf "$SSH_ED25519" > privatekey
      - printf "$CLIENT_OVPN" > config.ovpn
      - chmod og= privatekey
      - chmod og= config.ovpn
      - echo $VPN_USER > /etc/openvpn/cred.txt
      - echo $VPN_PWD >> /etc/openvpn/cred.txt
      - openvpn --config config.ovpn --auth-user-pass /etc/openvpn/cred.txt --daemon
      - sleep 20s
      
      - ssh -p $SERVER_PORT -i privatekey -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd deployment && docker-compose pull && docker-compose down && docker-compose up -d && docker system prune -f"
    secrets: [ ssh_ed25519, client_ovpn, vpn_user, vpn_pwd, server_user, server_ip, server_port ]
```
