### ISSUE TITLE
Sometimes settings not passed to plugin

### ISSUE THREAD

**Issue by wenerme** [woodpecker-ci/woodpecker#1678]
### Component

server, agent

### Describe the bug

Pipeline like

```yaml
variables:
- &node_image 'wener/node:docker'
- &notify_image 'wener/woodpecker-feishu-bot'


pipeline:
  Notify Start:
    image: *notify_image
    settings:
      feishu_bot_url:
        from_secret: feishu_bot_url
      feishu_bot_secret:
        from_secret: feishu_bot_secret
      text: |
        Hello
      markdown: |
        🏗️ 开始构建 <%= env.CI_REPO_NAME %> #<%= env.CI_BUILD_NUMBER %>
        
        - <%= $.link(env.CI_COMMIT,env.CI_COMMIT_LINK) %> <%=env.CI_COMMIT_MESSAGE.replaceAll(/\n/g,';')%>
        
        📦️ <%=$.link(env.CI_REPO_NAME,env.CI_BUILD_LINK)%>

  Notify Done:
    image: *notify_image
    settings:
      feishu_bot_url:
        from_secret: feishu_bot_url
      feishu_bot_secret:
        from_secret: feishu_bot_secret
      markdown: |
        <%= env.CI_PIPELINE_STATUS === 'success' ? '✅' : '❌' %> 构建完成 <%= env.CI_REPO_NAME %> #<%= env.CI_BUILD_NUMBER %>
        
        - <%= env.CI_COMMIT_MESSAGE %>
        
        📦️ <%= $.link(env.CI_REPO_NAME, env.CI_BUILD_LINK) %> · ⏳<%= env.CI_PIPELINE_FINISHED - env.CI_PIPELINE_STARTED %>
    when:
      status: [ success, failure ]

```

But 

<img width="373" alt="image" src="https://user-images.githubusercontent.com/1777211/227446873-b0195fee-c946-47ec-8b08-7b94d10c6bd6.png">

<img width="491" alt="image" src="https://user-images.githubusercontent.com/1777211/227447029-6966ee84-53fd-4568-8af4-f26f83acadb7.png">

<img width="743" alt="image" src="https://user-images.githubusercontent.com/1777211/227447156-3c74fb6c-b5a6-469d-8dcd-44c9a965200e.png">

### System Info

```shell
- 0.15.7
- k8s manifest https://github.com/wenerme/kube-stub-cluster/tree/main/dev-system/services/woodpecker
```

### Additional context

Not check the next version yet, the next version is incompatible with current.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).
