### ISSUE TITLE
Woodpecker Server sql: no rows in result set

### ISSUE THREAD

**Issue by neel** [woodpecker-ci/woodpecker#1682]
### Component

server

### Describe the bug

Added gitea repo to woodpecker. The repo contains the following `.woodpecker.yml` file
```
pipeline:
  build:
    image: debian
    commands:
      - echo "This is the build step"
  a-test-step:
    image: debian
    commands:
      - echo "Testing.."
      - cat README.md
```

After enabling the repo in woodpecker, I see

> No pipelines have been started yet.

shown under Activity panel.

I checked `systemctl status woodpecker` and found the following log
```
Mar 27 16:03:07 git systemd[1]: Started Woodpecker.
Mar 27 16:03:07 git woodpecker-server[19874]: {"time":"2023-03-27T16:03:07Z","message":"LogLevel = warn"}
Mar 27 16:03:17 git woodpecker-server[19874]: {"level":"warn","error":"sql: no rows in result set","time":"2023-03-27T16:03:17Z"}
```

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"0.15.7"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).
