### ISSUE TITLE
Agent listen tcp :3000: bind: address already in use

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#1757]
With the autoscaler I am creating following docker-compose set for the agent. Somehow the agent does not start and complains about a port being already in use:

```
root-woodpecker-agent-1  | rpc error: code = Unavailable desc = connection error: desc = "error reading server preface: read tcp 172.18.0.2:59030->xxx:443: read: connection reset by peer"
root-woodpecker-agent-1  | {"level":"warn","error":"rpc error: code = Unavailable desc = connection error: desc = \"error reading server preface: read tcp 172.18.0.2:58580->xxx:443: read: connection reset by peer\"","time":"2023-05-14T12:35:07Z","message":"cannot connect to server, retrying in 2s"}
root-woodpecker-agent-1  | {"level":"error","time":"2023-05-14T12:35:09Z","message":"cannot listen on address :3000: listen tcp :3000: bind: address already in use"}
```

```yml
# docker-compose.yml
version: '3'
services:
  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:next
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WOODPECKER_AGENT_SECRET=xxx
      - WOODPECKER_MAX_WORKFLOWS=2
      - WOODPECKER_SERVER=xxx
```
