### ISSUE TITLE
Environment variable `CI_BUILD_STATUS` is `pending` even after a success

### ISSUE THREAD

**Issue by dessalines** [woodpecker-ci/woodpecker#1777]
### Component

agent

### Describe the bug

I have a block in my `.woodpecker.yml` like this, which notifies me of the build status when its done. 

```yml
notify_on_done:
  image: curl
  commands:
    - "curl -d'My build ${CI_BUILD_STATUS}: ${CI_BUILD_LINK}' ntfy.sh/.."
  when:
    status: [failure, success]
```

On failure, the `CI_BUILD_STATUS` does correctly say `failed`.

On success, that env var says `pending`, when it should say *success*.

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-3b070547"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).
