### ISSUE TITLE
drop step.group in favour of depends_on to create a DAG

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#1860]
Support parallelism inside a pipeline via a [DAG](https://en.wikipedia.org/wiki/Directed_acyclic_graph). This requires a way to define step dependencies which can then allow the runner to build said DAG. Edit: I see [`group`](https://woodpecker-ci.org/docs/usage/pipeline-syntax#group---parallel-execution) provides something similar for static fan-out, but certainly not as flexible as defining dependencies directly.

_Originally posted by @silverwind in https://github.com/woodpecker-ci/woodpecker/issues/567#issuecomment-1282954563_

**Comment by 6543** [comment]
what about `depends_on` we already use it for workflow dep.-DAG ?

**Comment by 6543** [comment]
**one big downside! and what esp. makes it breaking!!!:**

now we assume that steps need to be run in sequence if not told otherwise (because it is what you normally want)
if we change this ... it would be the exact other way around

so what I think is **really** important: by default it should run sequential (that's just good UX-Design)

so what about a workflow config: `parallel: false` that if enabled would create a step dag ?!?

**Comment by 6543** [comment]
so I propose:
 - pipeline/backend typse -> always use a DAG
 - pipeline/frontend types (yaml) -> use a dag if specified and if not it creates a simpjle dag
   -> `(step1->step2->(group:step3 & step 4)-> step5...)` witch could still encounter the groups feature...

**Comment by 6543** [comment]
we should explicite write that down as one of our core values:
- `by default the config should work intuetive for beginners and not for advanced users - KISS` &
- `the default should be the so that the normal pipelines dont need to configure almost anything`

**Comment by silverwind** [comment]
In drone, it is also sequential until you add the first `depends_on` to a step, at which point it becomes a DAG.

**Comment by 6543** [comment]
That sounds nice as long as you dont have a workflow with steps that **all** can run paralel

**Comment by 6543** [comment]
I would call that not easy to lint, parse and sanitize ...

Also it would increase yaml config more ...

The more i think and talk about this with others the more i think we should have a workflow flag "parallel: true" and depends_on ... for the DAG

**Comment by lumpi101** [comment]
One more idea: to execute steps in parallel or not can be decided on whether the steps in the yaml are defined as a list or a dictionary.
- A list is sequential by nature and thus means that all listed steps are executed sequentially in that order.
- A dictionary has no ordering (also not in the yaml-specs afaik) and thus means that all steps are run in parallel, constrained by the "depends_on" markers.

This is of course not backwards compatible und would require some versioning of the pipeline syntax.
Also, having a dictionary, step names cannot be omitted which makes some kind of sense because autonaming steps with some enumeration could pretend some ordering which is not the case then.

A modified example from the docs...

parallel execution with DAG:
```
 version: 2
 steps:
   backend:  # <-- step names are mandatory
     image: golang
     commands:
       - go build
       - go test
   frontend:
     image: node
     commands:
       - npm install
       - npm run test
       - npm run build
   publish:
     image: plugins/docker
     depends_on: [backend, frontend]  # <-- if we would omit this, all 3 steps would be executed in parallel
     repo: octocat/hello-world
```

sequential execution:
```
 steps:
   - name: backend  # <-- step names are optional (afaik)
     image: golang
     commands:
       - go build
       - go test
   - name: frontend
     image: node
     commands:
       - npm install
       - npm run test
       - npm run build
   - name: publish
     image: plugins/docker
     repo: octocat/hello-world
```
