### ISSUE TITLE
Customization options for Containers

### ISSUE THREAD

**Issue by schewara** [woodpecker-ci/woodpecker#1868]
### Clear and concise description of the problem

Currently the usage of images is very limited, which requires one to implement some workarounds like using custom images/plugins to play along with woodpecker and sometimes existing infrastructure requirements.

Therefore I would like to suggest to add support for the following options to not have to re-invent the weel every time when one wants to integrate a new tool/image which does not match the current limitations.

- **containerprefix**
  currrently the name shows up like `0_338859503931012122_step_0` and defining a name or a static prefix would make it clearer which container to look for in case of a hanging job which needs to be investigated, or for monitoring exclusion.
- **labels/attributes**
  would help in situations where external components rely on the existence of specific labels, like log collection/shipping, alerting rules, service discovery, ...
- **entrypoint**
  some containers either have default entrypoints (e.g. trivy), which can not be used in a CI context or containers built from scratch which don't have a shell available would need a way to customize the the entrypoint to work properly out of the box.

This list is only my "Top 3" with potentially more options to follow, but these would already cover more then 90% of all my use cases.

### Suggested solution

The ability to define specific options for images like:

```
pipeline:
  test:
    image:
      name: a-container:latest
      entrypoint: [""]
      pull_policy: [always, if-not-present, never]
      labels:
        key: value
```

or as `backend_options`

```
    image: my-container:latest
    backend_options:
      docker:
        name: the-container-name
        entrypoint: [""]
        pull_policy: [always, if-not-present, never]
        labels:
          key: value
```

### Alternative

Currently the only alternative I see, are custom images or plugins tailered to work with woodpecker.

### Additional context

- As already predicted by @gapodo in https://github.com/woodpecker-ci/woodpecker/pull/1825#issuecomment-1576598884, where labels support has been removed (here we go :smirk:)
- #278
- [GitLab Runner - Docker executor](https://docs.gitlab.com/runner/executors/docker.html) documentation
- How the [Testcontainers](https://java.testcontainers.org/features/advanced_options/) Project does it

### Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.
