### ISSUE TITLE
when.platform does filter based on server not agent platform string

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#1870]
we might need to figure out how to compile pipelines based on that ...

I would suggest that this filter does only apply if root.platform or root.lables.platform is set ... so that you can do something like this:

```yaml
matrix:
    PLATFORMS:
        - linux/amd64
        - linux/arm

platform: ${PLATFORMS}

steps:
    hello:
        image: golang
        commands:
            - echo hello woodpecker
            - sleep 3s
            - echo build things ...

    arm-only:
        image: bash
        commands: echo from arm only
        when:
            platform: linux/arm
```
