### ISSUE TITLE
Stop leaking secrets

### ISSUE THREAD

**Issue by lonix1** [woodpecker-ci/woodpecker#1920]
# Clear and concise description of the problem

Various secrets must be hardcoded [in the compose file](https://woodpecker-ci.org/docs/administration/setup) as environment variables; e.g. `WOODPECKER_AGENT_SECRET`, `WOODPECKER_GITHUB_SECRET`, etc.

This is very bad:
- most users would follow the docs blindly and expose the secrets this way
- the secrets would end up in source control
- environment variables (and thus their secrets) *are leaked via logging*

# Suggested solution

Please adopt best practice: introduce matching variables for each secret. For example:
- for `WOODPECKER_GITHUB_SECRET`, add new variable `WOODPECKER_GITHUB_SECRET_FILE`
- for `WOODPECKER_AGENT_SECRET`, add new variable `WOODPECKER_AGENT_SECRET_FILE`
- etc.

Each of those new variables should be set to the path of a file containing the secret.

Example setup:

`.github-secret` with permissions `400`
```
mygithubmegasecret1234567890
```

`.woodpecker-secret` with permissions `400`
```
mysupersecret1234567890
```

`docker-compose.yml`
```yml
secrets:
  github-secret:
    file: .github-secret
  woodpecker-secret:
    file: .woodpecker-secret

woodpecker-server:
  # ...
  secrets:
    - github-secret               # mounted inside container at '/run/secrets/github-secret'
    - woodpecker-secret           # mounted inside container at '/run/secrets/woodpecker-secret'
  environment:
    - WOODPECKER_GITHUB_SECRET: /run/secrets/github-secret
    - WOODPECKER_AGENT_SECRET_FILE: /run/secrets/woodpecker-secret

woodpecker-agent:
  # ...
  secrets:
    - woodpecker-secret           # mounted inside container at '/run/secrets/woodpecker-secret'
  environment:
    - WOODPECKER_AGENT_SECRET_FILE: /run/secrets/woodpecker-secret
```

All this is optional and backwards compatible: the user could still hardcode secrets in the compose file.

# Alternative

Bad security. :smile:

# Additional context

### 1. What must woodpecker do?
If woodpecker detects that one of the new variables is set, then simply read the secret from the associated file.

For example:
- if `WOODPECKER_GITHUB_SECRET_FILE` is set to `/run/secrets/github-secret`
- read the file `/run/secrets/github-secret` into a variable in memory (not into an environment variable!)
- ignore the corresponding `WOODPECKER_GITHUB_SECRET` environment variable

### 2. What environment variables must be added?
From examination of the [server](https://woodpecker-ci.org/docs/administration/server-config) and [agent](https://woodpecker-ci.org/docs/administration/agent-config) docs:

Server:
- `WOODPECKER_ADMIN_FILE`
- `WOODPECKER_AGENT_SECRET_FILE`
- `WOODPECKER_GITHUB_CLIENT_FILE`, `WOODPECKER_GITHUB_SECRET_FILE`
- `WOODPECKER_GITEA_CLIENT_FILE`, `WOODPECKER_GITEA_SECRET_FILE`
- etc.

Agent:
- `WOODPECKER_USERNAME_FILE`
- `WOODPECKER_AGENT_SECRET_FILE`

# Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

# Thank You!
Although this is a long post, the solution is extremely simple. Thank you for considering it!
