### ISSUE TITLE
Manual clone step does not work

### ISSUE THREAD

**Issue by windsource** [woodpecker-ci/woodpecker#1928]
### Component

server, agent

### Describe the bug

With previous next versions of Woodpecker the manual clone step worked fine but with `next-44b54db475` it does not  work anymore.

`.woodpecker.yml`:

```yaml
clone:
  git:
    image: woodpeckerci/plugin-git
    settings: 
      depth: 50
    
steps:
  build-main:
    image: ubuntu
    commands: 
      - echo Build main
      - cat README.md
```

results in failure in the `git` step:

```
+ git init -b main
Initialized empty Git repository in /woodpecker/src/github.com/<removed>
+ git remote add origin https://github.com/<removed>
+ git fetch --no-tags --depth=1 --filter=tree:0 origin +refs/heads/main:
fatal: could not read Username for 'https://github.com': No such device or address
exit status 128
```

A `.woodpecker.yml` without a manual clone step works fine:

```yaml
steps:
  build-main:
    image: ubuntu
    commands: 
      - echo Build main
      - cat README.md
```

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-44b54db4"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).
