### ISSUE TITLE
Local backend fails when using clone configuration

### ISSUE THREAD

**Issue by adamcstephens** [woodpecker-ci/woodpecker#1931]
### Component

server

### Describe the bug

When using a local backend and specifying a `clone` configuration, the clone step fails.

This configuration:

```yaml
clone:
  git:
    image: plugin-git
    settings:
      partial: false
      depth: 20
```

Generates this error:

```
Incorrect Usage. flag provided but not defined: -c

NAME:
   git plugin - git plugin
<SNIP>
```

Looking through the backend led me to try using the constant string. https://github.com/woodpecker-ci/woodpecker/blob/0cf602a1f6b1ef688eabb209e9bd2f5d0f9ce164/pipeline/backend/local/local.go#L131-L139

This does /not/ fail, but the settings are not honored nor supported.

```yaml
clone:
  git:
    image: docker.io/woodpeckerci/plugin-git:2.0.3
    settings:
      partial: false
```

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-3158980d"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).
