### ISSUE TITLE
Matrix variable not usable in environment

### ISSUE THREAD

**Issue by simmstein** [woodpecker-ci/woodpecker#1945]
### Component

server, agent

### Describe the bug

When a variable is defined through a matrix, it's not possible to use it as environment variable.

This following configuration results on error: `failed to parse pipeline: Cannot unmarshal '<nil>' of type <nil> into a string value`.

 ```
matrix:
  FOO:
    - foo1
    - foo2

steps:
  example:
    image: alpine:latest
    environment:
      BAR: ${FOO}
    commands:
      - echo ${FOO}
```

But this following config works:

```
matrix:
  FOO:
    - foo1
    - foo2

steps:
  example:
    image: alpine:latest
    commands:
      - echo ${FOO}
```

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-0cf602a1"}
```

### Additional context

Example: https://ci.gitnet.fr/repos/315

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by pat-s** [comment]
This seems to be the same issue as reported in https://github.com/woodpecker-ci/woodpecker/issues/2505#issuecomment-1757672451

**Comment by zc-devs** [comment]
```
matrix:
  FOO:
    - foo1
    - foo2

steps:
  example:
    image: alpine
    environment:
      BAR: ${FOO}
    commands:
      - echo foo=${FOO}
      - printenv
```

Can't reproduce on a95f1bc6255ea9d5f16f7a754d4d09277e4ceb9c:
![Screenshot 2023-10-16 185337](https://github.com/woodpecker-ci/woodpecker/assets/127358482/c9764b4a-8ed5-4bbc-ac1a-44c0f0531458)

Also, it's not necessary to pass matrix variable via `environment`, as it is available by its name:
![Screenshot 2023-10-16 185451](https://github.com/woodpecker-ci/woodpecker/assets/127358482/1610bca4-432f-48ea-a37b-a713627bc74b)

**Comment by simmstein** [comment]
Yes it works: https://ci.gitnet.fr/repos/315/pipeline/4

But, using matrix this ways failed:

```
matrix:
  PHP_VERSION:
    - 8.1
    - 8.2

steps:
  example:
    image: deblan/php:${PHP_VERSION}
    commands:
      - php -v
```

- https://ci.gitnet.fr/repos/315/pipeline/7/config
- https://ci.gitnet.fr/repos/315/pipeline/7

```
matrix:
  PHP_VERSION:
    - 8.1
    - 8.2

steps:
  example:
    image: deblan/php:$PHP_VERSION
    commands:
      - php -v
```

- https://ci.gitnet.fr/repos/315/pipeline/8/config
- https://ci.gitnet.fr/repos/315/pipeline/8

The next syntax works but is not practical because I can't reuse PHP_VERSION:

```
matrix:
  PHP_VERSION:
    - deblan/php:8.1
    - deblan/php:8.2

steps:
  example:
    image: ${PHP_VERSION}
    commands:
      - php -v
```

Expected:

```
matrix:
  PHP_VERSION:
    - 8.1
    - 8.2

steps:
  foo:
    image: foo/bar:${PHP_VERSION}
  bar:
    image: foo2/bar2:${PHP_VERSION}
```
