### ISSUE TITLE
Fix clone-image recognition for netrc inject filter

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#1948]
repo settings -> disable `Only inject netrc credentials into trusted containers` ...

that filter is currently bit broken :/ (it does not recognice the custom clone as "trusted" one atm)

version: cef135eba5f21a3e4ad429f9af51f535ce907372

TOFIX:
we need to let custom clone steps that use the trusted images and are used as plugin still access the netrc by default!!!

**Comment by windsource** [comment]
Will also fix #1928.

**Comment by 6543** [comment]
Duplicate of #1928 i would say 😅

**Comment by 6543** [comment]
Also dublicate to #1837

**Comment by 6543** [comment]
well if you do:
```
clone:
  clone:
    image: woodpeckerci/plugin-git:2.0.3

steps:
  build:
    # ...
```

now it's named "clone"
