### ISSUE TITLE
kubernetes: git clone broken

### ISSUE THREAD

**Issue by ymettier** [woodpecker-ci/woodpecker#1955]
### Component

server, agent, web-ui

### Describe the bug

Step `git clone` does not work.

It was working with next-94f2331a4c (July 6th 2023).

It is broken with next-1d6b073ca5 (July 8th 2023 few hours ago).

![image](https://github.com/woodpecker-ci/woodpecker/assets/2285664/c0c69d1f-fe17-4bac-94ef-c5accb4563b2)

On the right pane, I can read `Chargement…` that means `Loading...`

I can switch from one version (it works) to the other version (it does not work) and rollback to the previous version (it works) again and again. I made no change anywhere except the image tag of Woodpecker agent and server.

I compared the logs ( `kubectl logs woodpecker-0; kubectl logs woodpecker-agent-xxxxxx`). There is no interesting difference.

### System Info

```shell
Working with next-94f2331a4c (July 6th 2023).
Broken with next-1d6b073ca5 (July 8th 2023 few hours ago).

Kubernetes backend
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by 6543** [comment]
there are two related pulls since then:  #1914 &  #1909

cc @zc-devs

**Comment by 6543** [comment]
thanks for the detailed report @ymettier :+1:

**Comment by zc-devs** [comment]
Custom `next-556607b525`.

```
  containers:
    - name: wp-01h4w19zvmmgb91jgdwcwde9qt-0-step-3
      image: woodpeckerci/plugin-docker-buildx
      workingDir: /woodpecker/src/forge/user/woodpecker
      env:
        - name: CI_PREV_COMMIT_SHA
        - name: CI_REPO_PRIVATE
          value: 'true'
          ...
        - name: DRONE_REPO_BRANCH
          value: master
        - name: CI_SYSTEM_PLATFORM
        - name: CI_SYSTEM_ARCH
          value: linux/amd64
          ...
```
