### ISSUE TITLE
failed to parse pipeline: yaml: line 4: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by XDream8** [woodpecker-ci/woodpecker#2002]
Error:
![20230715_09h12m46s_grim](https://github.com/woodpecker-ci/woodpecker/assets/62709801/864c2eb7-4313-4cdd-b43f-91bb0e5452c4)

Pipeline:
```yaml
pipeline:
  test:
    group: test
    image: rust:${TAG}
    environment:
      - CARGO_TERM_COLOR=always
      - CARGO_BUILD_TARGET=${TARGET}
    commands:
      - rustup default stable
      - rustup target add ${TARGET}
      - rustup component add clippy
      - cargo test
      - cargo clippy

  build:
    group: build
    image: rust:${TAG}
    when:
      event: tag
    environment:
      - CARGO_TERM_COLOR=always
      - CARGO_BUILD_TARGET=${TARGET}
    commands:
      - rustup default stable
      - rustup target add ${TARGET}
      - cargo build --profile optimized
      - tar -zcvf file-rs-${TARGET}.tar.gz target/${TARGET}/optimized/file-rs

  publish:
    group: publish
    image: woodpeckerci/plugin-gitea-release
    when:
      event: tag
    settings:
      base_url: https://codeberg.org
      files:
        - "file-rs-${TARGET}.tar.gz"
      file-exists: overwrite
      api_key:
        from_secret: CODEBERG_ACCESS_TOKEN
      target: main
      title: file-rs
      skip_verify: true

matrix:
  include:
    - TARGET: x86_64-unknown-linux-musl
      TAG: alpine
    - TARGET: x86_64-unknown-linux-gnu
      TAG: latest
    - TARGET: aarch64-unknown-linux-musl
      TAG: alpine
    - TARGET: aarch64-unknown-linux-gnu
      TAG: latest
    - TARGET: x86_64-pc-windows-gnu
      TAG: latest
```

I followed the [documentation for matrix builds](https://woodpecker-ci.org/docs/usage/matrix-builds) but in the end this error came up.

When I use normal matrix combinations it works fine but when I try to use specific matrix combinations this happens.
