### ISSUE TITLE
Global variables in top-level section

### ISSUE THREAD

**Issue by lonix1** [woodpecker-ci/woodpecker#2016]
### Clear and concise description of the problem

There have been similar ideas in other issues over the years, but the ones I've seen are closed, or related to a narrow topic.

# PROBLEM

To keep pipeline files DRY, we should use variables.

There are a number of workarounds, but each one is lacking in some respect, so pipeline files are more messy than they should be.

### Suggested solution

# SOLUTION

In other ci/cd systems there are global env vars at the top-level (e.g. for drone [here](https://docs.drone.io/pipeline/environment/syntax/#per-pipeline)).

Something like this would be ideal:
```yml
environment:                # <-----
  - BASH_VERSION=1.2.3      # <-----
  - PATH_SRC=/src/          # <-----
  - PATH_TEST=/test/        # <-----
  - FOO=something           # <-----
steps:
  build:
    image: bash:${BASH_VERSION}
    directory: ${PATH_SRC}
    commands:
      - make ${FOO} -o ${PATH_TEST}
  test:
    image: bash:${BASH_VERSION}
    commands:
      - test ${PATH_TEST}
```

### Alternative

# WORKAROUNDS

## yaml extensions
From the [docs](https://woodpecker-ci.org/docs/next/usage/advanced-yaml-syntax):
```yml
variables:
  - &golang_image 'golang:1.18'
 steps:
   build:
    #image: golang:1.18
     image: *golang_image             # cannot interpolate
     commands: build
```

This is good for whole-line variables, when interpolation isn't needed.

## persisting env data between steps
A very cool trick taught to me by @6543 on [discord](https://discord.com/channels/838698813463724034/838698813463724037/1131201211350143048):
```yml
steps:
  init_vars:
    image: bash
    commands:
      echo "FOO=hello" >> envvars
      echo "BAR=world" >> envvars
  ...
  user_vars:
    image: debian
    commands:
      - source envvars
      - echo $FOO
```

This is probably the most useful approach, but it's not perfect:
```yml
steps:
  init:
    image: busybox
    commands:
      echo "BASH_VERSION=1.2.3" >>envvars
      echo "APP_PATH=/app/" >> envvars
      echo "FOO=something" >> envvars
  build:
    image: bash:${BASH_VERSION}      # doesn't work here
    directory: ${APP_PATH}           # doesn't work here
    commands:
      - source envvars
      - make ${FOO}                  # works here
```

## set global environment in `docker-compose.yml`
From [docs](https://woodpecker-ci.org/docs/next/usage/environment#global-environment-variables):
```yml
services:
  woodpecker-server:
    # ...
    environment:
      - WOODPECKER_ENVIRONMENT=first_var:value1,second_var:value2
      # ...
```

Although this works, it's not convenient. It tightly couples the server config and the app config (which is a completely separate application). It might be useful for truly global data, which is common to all apps.

### Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by 6543** [comment]
I dont see mouch value in adding an extra parsing step and add even more options to the pipeline config. as it is already covered by variables:

```yml
variables:
  - global_env: &global_env 
    - BASH_VERSION=1.2.3
    - PATH_SRC=/src/
    - PATH_TEST=/test/
    - FOO=something

steps:
  build:
    image: bash:${BASH_VERSION}
    directory: ${PATH_SRC}
    commands:
      - make ${FOO} -o ${PATH_TEST}
    environment: *global_env

  test:
    image: bash:${BASH_VERSION}
    commands:
      - test ${PATH_TEST}
    environment:
      - <<:*global_env
      - ADDITIONAL_LOCAL="var value"
```
