### ISSUE TITLE
Incorrect error for buildx plugin and global secret of insufficient scope

### ISSUE THREAD

**Issue by lonix1** [woodpecker-ci/woodpecker#2032]
### Component

server

### Describe the bug

This is further to the discussion on [discord](https://discord.com/channels/838698813463724034/911685405546524722/1132977506362855424).

My publish step (using `woodpeckerci/plugin-docker-buildx`) was correct, yet still yielded this error:
> ERROR: tag is needed when pushing to registry

I spent hours going over every little thing in my config. No one on the discord channel could figure it out either.

Finally I discovered the problem:
```yml
  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      password:
        from_secret: publish-to-registry
      tags: [latest, 1.2.3]                 # <----- I did specify tags
      # ...
    when:
      event: tag
```
The `publish-to-registry` global secret had the `manual` and `push` scopes, but not `tag`.

So the error log was misleading.

I hope it can be fixed so it doesn't waste other peoples' time, and cause more repo issues (unnecessary work for you :smile:).

### System Info

```shell
next-b3c2bb2e (latest)
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).
