### ISSUE TITLE
Service command override stopped working with 1.0.0-rc1

### ISSUE THREAD

**Issue by ateuber** [woodpecker-ci/woodpecker#2054]
### Component

agent

### Describe the bug

We use the following services definition with a `command` statement as a workaround for a bug in Timescaledb:

```
services:
  database_timescale:
    image: timescale/timescaledb:latest-pg15
    command: postgres -c timescaledb.max_background_workers=0
```

If we don't start postgres with this `max_background_workers` setting, Woodpecker is unable to clone the test database.

This worked with Woodpecker 0.15.11 and stopped working with Woodpecker 1.0.0-rc1. Have there been any changes regarding this services command override?

### System Info

```shell
Woodpecker 1.0.0-rc1
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by 6543** [comment]
@ateuber did this worked for sure in the past? 

should'nt it be  `commands`  <- missing **s** ?

**Comment by 6543** [comment]
https://github.com/woodpecker-ci/woodpecker/blob/release/v0.15/pipeline/frontend/yaml/container.go#L30-L31
vs.
https://github.com/woodpecker-ci/woodpecker/blob/main/pipeline/frontend/yaml/types/container.go#L23

**Comment by 6543** [comment]
ok if the v0.15 had this mentioned in the docs somewhere we have to handle it as breaking change and mention it in the cangelog and provide a migration path

**Comment by 6543** [comment]
likely a regression of  #1032

**Comment by 6543** [comment]
@ateuber we wont add it back for safety reasons.

but you can migrate any service by lookup how the **entrypoint** in the original image was and combine it into it's `commands` form. If the entrypoint already was a shell you just have to append an **s** as in your case.

```yaml
services:
  database_timescale:
    image: timescale/timescaledb:latest-pg15
    commans: postgres -c timescaledb.max_background_workers=0
```
