### ISSUE TITLE
Cannot pull custom docker image without full semver

### ISSUE THREAD

**Issue by lonix1** [woodpecker-ci/woodpecker#2059]
### Component

server

### Describe the bug

My `woodpecker.yml`:
```yml
variables:
  - &PLUGIN_CUSTOM_1 gitea.example.com/my-org/my-repo:0         # fails: major
  - &PLUGIN_CUSTOM_2 gitea.example.com/my-org/my-repo:0.1       # fails: major.minor
  - &PLUGIN_CUSTOM_3 gitea.example.com/my-org/my-repo:0.1.1     # works: major.minor.patch
  - &PLUGIN_GIT woodpeckerci/plugin-git:2                       # works: major

clone:
  clone:
    image: *PLUGIN_GIT

steps:
  my-step-1:
    image: *PLUGIN_CUSTOM_1
  my-step-2:
    image: *PLUGIN_CUSTOM_2
  my-step-3:
    image: *PLUGIN_CUSTOM_3
```

For `my-step-1` and `my-step-2` I get:
> Manifest unknown

It only works when I specify the full semver `major.minor.patch` format - I cannot specify only `major`. But for plugins from github and codeberg I can specify only `major`.

### System Info

```shell
1.0.0-rc1
docker
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).
