### ISSUE TITLE
Matrix and `when.evaluate` regression (not evaluating matrix variables)

### ISSUE THREAD

**Issue by ambroisie** [woodpecker-ci/woodpecker#2068]
### Component

server

### Describe the bug

I used to be able to use the following configuration:

```yaml
matrix:
  include:
    - TYPE: dev
      MAKE_TARGET: build-dev
      SSH_TARGET: ssh_target_dev
    - TYPE: prod
      MAKE_TARGET: build-prod
      SSH_TARGET: ssh_target

# Run the correct matrix build on the correct branch
when:
  evaluate: |
    CI_PIPELINE_EVENT in ["push", "cron", "deployment", "manual"]
    and ((CI_COMMIT_BRANCH == CI_REPO_DEFAULT_BRANCH) == ("${TYPE}" == "prod"))
```

To be able to have a workflow which has 95% overlap between `prod` and `dev`, but only runs `prod` on `main` and `dev` on other branches.

When updating to 1.0.0, I noticed that this configuration stopped working.

From the logs, I can see that the filter is evaluated once for the whole workflow, and `${TYPE}` is empty/not evaluated. I would expect it to evaluate the filter once for each matrix variant instead, as it used to be ~6 months ago.

### System Info

```shell
Version: 1.0.0
Run on a NixOS host.
```

### Additional context

```
Evaluate:\"CI_PIPELINE_EVENT in [\\\"push\\\", \\\"cron\\\", \\\"deployment\\\", \\\"manual\\\"]\\nand ((CI_COMMIT_BRANCH != CI_REPO_DEFAULT_BRANCH) == (\\\"\\\" == \\\"prod\\\"))\\n\"}}}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).
