### ISSUE TITLE
Resource limits for step containers

### ISSUE THREAD

**Issue by lonix1** [woodpecker-ci/woodpecker#2135]
I originally posted on [discord](https://discord.com/channels/838698813463724034/838698813463724037/1137646174195695647), twice, without resolution. I assume that means what I've described isn't currently possible, hence this feature request.

## Clear and concise description of the problem

In a memory constrained VPS, I'd like to set memory and cpu limits, because (even for a small build) the *memory use spikes and impacts other docker services*. I think the issue is not for the server or agent containers, but rather the ephemeral "step containers".

Typically one would set (in `docker-compose.yml`) resource limits for such containers:
```yml
services:
  foo:
    # ...
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 150m
    memswap_limit: 1g
```

I found env vars in the [docs](https://woodpecker-ci.org/docs/administration/server-config#woodpecker_limit_mem) but evidently they don't represent the same idea as the code above.

```yml
services:
  woodpecker:
    # ...
    environment:
      - WOODPECKER_LIMIT_MEM=157286400          # 150MiB: only a number works, suffixes are not allowed (e.g. 'm", 'mb', 'M', 'Mi', 'MiB'), which is fine
      - WOODPECKER_LIMIT_MEM_SWAP=1073741824    # 1GiB
      - WOODPECKER_LIMIT_CPU_QUOTA=             # ?
      - WOODPECKER_LIMIT_CPU_SHARES=            # ?
```

The docs state:
> `WOODPECKER_LIMIT_CPU_QUOTA`: "The number of microseconds per CPU period that the container is limited to before throttled. There is no limit if 0."

and
> `WOODPECKER_LIMIT_CPU_SHARES`: "The relative weight vs. other containers."

I'm unsure why these options were made available, or what is their use case - my guess is woodpecker is using a go docker library which exposes this functionality, and so wraps it?

## Suggested solution

What's missing is cpu throttling by percentage, like docker does it. So for example:
```yml
- WOODPECKER_LIMIT_CPU_PERCENT=0.25
```

## Alternative

There is no alternative, from what I can tell? The step containers use as much CPU as they need.

## Additional context

Thanks.

## Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

## Environment
1.0.0
docker
