### ISSUE TITLE
Multiple steps within the same container/image

### ISSUE THREAD

**Issue by MV-GH** [woodpecker-ci/woodpecker#2155]
### Clear and concise description of the problem

My apologies if this is already possible but I did not see this in the docs. I want to be able to do multiple steps in the same container.

For example my .yml is:

```yml
steps:
  check_formatting:
    image: cimg/android:2023.08
    commands:
      - sudo chown -R circleci:circleci .
      - ./gradlew lintKotlin

  build_project:
    image: cimg/android:2023.08
    commands:
      - sudo chown -R circleci:circleci .
      - ./gradlew assembleDebug
```

I can do of course

```yml
steps:
  check_formatting_build_project:
    image: cimg/android:2023.08
    commands:
      - sudo chown -R circleci:circleci .
      - ./gradlew lintKotlin
      - ./gradlew assembleDebug
```
But this will show up as one step in the UI

The reason for this is that I don't want to create multiple unnecessary containers but I do want to keep the usefulness to see from a quick glance in the UI in which step the pipeline failed.

### Suggested solution

Not sure how this would look like in the config, but the following is a possible example

```yml
steps:
  compound_step:
    compound: true
    image: cimg/android:2023.08
    steps:
       - name: lint
         commands:
           - sudo chown -R circleci:circleci .
           - ./gradlew lintKotlin
       - name: build
         commands:
            - ./gradlew assembleDebug       
```       

### Alternative

The ability for one step to reuse the container in the next step

### Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.
