### ISSUE TITLE
cron running all steps instead of only cron events

### ISSUE THREAD

**Issue by philipkozeny** [woodpecker-ci/woodpecker#2226]
### Component

server, agent

### Describe the bug

In previous versions I am pretty confident that only those steps in a pipeline were run, that had a `cron` event attached to them. 

Example:

```
  security:
    image: fancyimage
    pull: true
    commands:
      - yarn audit
      - composer audit --locked
    when:
      - event: [cron]
 ```

Running v1.x I can see, that all other steps without events are also executed when the job is triggered by cron.

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"1.0.2"}
```

### Additional context

.woodpecker.yml

```yaml
pipeline:
  setup:
    image: ci-image-php:8.2
    pull: true
    commands:
    [...]
    secrets: [ ssh_private_key ]

  test:
    image: ci-image-php:8.2
    pull: true
    commands:
    [...]

  deploy-dev:
    image: curlimages/curl
    [...]
    when:
      - event: [ push ]
        branch: ${CI_REPO_DEFAULT_BRANCH}

  security:
    image: ci-image-php:8.2
    [...]
    when:
      - event: [ push, pull_request, tag, deployment, cron, manual ]

  mail:
    image: deblan/woodpecker-email
       [...]
      evaluate: 'CI_STEP_STATUS == "failure" || CI_PREV_PIPELINE_STATUS == "failure"'
    when:
      - status: [ success, failure ]
      - event: [ push, pull_request, tag, deployment, cron, manual ]

services:
  database:
    image: mysql:8
    [...]
```

Here are the steps that are executed when triggered by cron:

```
 clone
00:05

database
01:35

setup
00:56

test
00:33

security
00:03

mail
00:01
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).
