### ISSUE TITLE
[Feature] Keyword / Commit message condition

### ISSUE THREAD

**Issue by kdumontnu** [woodpecker-ci/woodpecker#224]
This should enable a new trigger for keywords in the commit message or title (using either wildcard glob or regex). The usage is as follows:

```
trigger:
  keyword:
  - "*[RUN PIPELINE]*"
```
Should only run if the keyword is matched.

or

```
trigger:
  keyword:
    exclude:
    - "*[SKIP DEPLOY]*"
```
Should not run if the keyword is matched.

I considered simplifying the notation just matching the keyword anywhere in the string, but it would give the user less control on matching specific strings.
