### ISSUE TITLE
Workflow When use "Any" instead of "All" which differs from the documentation

### ISSUE THREAD

**Issue by westinpigott** [woodpecker-ci/woodpecker#2324]
### Component

server, other

### Describe the bug

According to the documentation (https://woodpecker-ci.org/docs/usage/pipeline-syntax#when---global-pipeline-conditions), "If all conditions in the when block evaluate to true the pipeline is executed, otherwise it is skipped" however, it seems the workflow-level when block is actually using "any conditions evaluate to true".

**The desired state is how the documentation presents it, with "all conditions" required.**

Example.  I have 2 workflows shown below.  "manager.deploy" should only run when there is a deployment event, AND test was successful AND environment is production.  It will run always though.

### manager.test.yml
```
when:
  - path:
      include: ['Manager/**/*', '.woodpecker/manager.*' ]
  - event: [push, pull_request, manual]

steps:
  Run Tests:
    image: alpine:latest
    commands:
      - echo 'Do Something"
```
### manager.deploy.yml
```
when:
  - path:
      include: ['Manager/**/*', '.woodpecker/manager.*' ]
  - event: [deployment]
  - environment: production
  - depends_on:
      - manager.test

depends_on:
  - manager.test

steps:
  Run Deploy:
    image: alpine:latest
    commands:
      - echo 'Do Something"
```

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"1.0.2"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).
