### ISSUE TITLE
Variable expansion everywhere, not only commands: block

### ISSUE THREAD

**Issue by denisz1** [woodpecker-ci/woodpecker#2330]
### Clear and concise description of the problem

Hello!

We can use environment var like:

```yml
variables:
  - &env
    - SOMETHING=bar

steps:
  build:
    image: bash
    environment: *env
    commands:
      - foo "$SOMETHING"
```

But not like this (I use docker plugin only for example):

```yml
variables:
  - &env
    - registry_url=ourregistry.com
    - repo_name=therepo

steps:
  docker:
    image: woodpeckerci/plugin-docker-buildx
    environment: *env
    settings:
      registry: ${registry_url}
      username: ${CI_REPO_OWNER}
      password:
        from_secret: secret
      repo: ${registry_url}/${CI_REPO_OWNER}/$repo_name
```

It can not work for `repo: ourregistry.com/${CI_REPO_OWNER}/$repo_name` because it not expands those variables `registry_url` and `repo_name` and they are blank.

I read the [documents](https://woodpecker-ci.org/docs/usage/environment). I think this not available now - we can expand env vars in `commands:` block only. (I am correct?)

We have microservices and so many '.woodpecker.yml' files! Very hard to use. So would be good to have them "DRY" with more variables substitution/expansion.

### Suggested solution

Please can we use env vars anywhere in file?

### Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.
