### ISSUE TITLE
Parsing issue when using YAML anchors/aliases for secrets

### ISSUE THREAD

**Issue by lonix1** [woodpecker-ci/woodpecker#2331]
### Component

server

### Describe the bug

As discussed in [discord](https://discord.com/channels/838698813463724034/838698813463724037/1145015819626086460).

There is an issue with how the parser deals with yaml anchors/aliases when used for secrets.

A minimal repro below:

`.woodpecker.yml`
```yml
variables:
  - &USERNAME some_global_secret_1
  - &TOKEN some_global_secret_2

steps:

  use-as-list:
    image: busybox
    commands:
      - echo $USERNAME
      - echo $TOKEN
    secrets:
      - *USERNAME
      - *TOKEN

  use-as-scalar:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: Dockerfile
      registry: ${CI_FORGE_URL##https://}
      username: ${CI_REPO_OWNER}
      password:
        from_secret: *TOKEN
      repo: ${CI_FORGE_URL##https://}/${CI_REPO_OWNER}/myrepo
      tag: test
````

`Dockerfile`
```docker
FROM busybox
ENTRYPOINT ["echo", "hello"]
````

Result:
> failed to parse pipeline: yaml: unknown anchor 'USERNAME' referenced

@6543 Spent some time investigating. Some preliminary results:
- Test repo [here](https://codeberg.org/test_it/test_ci_thing)
- Test pipeline [here](https://ci.codeberg.org/repos/12550)
- Possible issue somewhere [here](https://github.com/woodpecker-ci/woodpecker/blob/336c41dd3312864b1ff135bd6d35ce583b72c257/pipeline/frontend/yaml/compiler/settings/params.go#L162)

### System Info

```shell
1.0.2
docker
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).
