### ISSUE TITLE
"woodpecker-cli lint" fails on name property

### ISSUE THREAD

**Issue by pinpox** [woodpecker-ci/woodpecker#2342]
### Component

cli

### Describe the bug

Woodpecker-cli seems to have a wrong schema. When linting an example pipeline from the docs, it reports it as being invalid.

### Steps to reproduce: 
1. Save the following as `test.yaml` (taken from the docs)
```yaml
steps:
  - name: backend
    image: golang
    commands:
      - go build
      - go test
  - name: frontend
    image: node
    commands:
      - npm install
      - npm run test
      - npm run build
```
1. run `woodpecker-cli lint test.yaml` and you get:
```
shell ❯ woodpecker-cli lint test.yaml
❌ Config is invalid
In steps: Must validate one and only one schema (oneOf)
In steps.0: Additional property name is not allowed
In steps.1: Additional property name is not allowed
2:52PM FTL error running cli error="Config not valid"
```

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"1.0.2"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).
