### ISSUE TITLE
Load env vars from file

### ISSUE THREAD

**Issue by lonix1** [woodpecker-ci/woodpecker#2352]
Originally asked on [discord](https://discord.com/channels/838698813463724034/838698813463724037/1145927398097956915) without any respose, so I assume this is not currently possible, and hence this feature request.

### Clear and concise description of the problem

The [docker-buildx](https://woodpecker-ci.org/plugins/Docker%20Buildx) plugin has option `build_args` to specify individual args and `build_args_from_env` to load all env vars into the build context.

But there does not seem to be a way to *load env vars from a file*.

For example I have `Dockerfile`, and `Dockerfile.env` which is sourced in my build scripts:
```console
. Dockerfile.env ; docker build Dockerfile
```

Encapsulating env vars in a file is a common use case, as they can be checked into source control and shared among people, also they allow us to encode configuration outside the pipeline (where it belongs) instead of inside the pipeline.

### Suggested solution

There are probably two ways to do this:
1. Add an argument to the buildx plugin, e.g.
  ```yaml
  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      build_args_from_file: Dockerfile.env
      # etc...
  ```
2. Add a generic feature which can be used in any step (but I suppose more complicated to develop):
  ```yml
  steps:
    foo:
      image: something
      environment:
        - VAR_A=10
        - VAR_B=hello
      env_file:                   # same idea as in 'docker-compose.yml'
        - .env
        - Dockerfile.env
        - settings.production.ini
  ```

In either case, the file must have `ini` format.

### Alternative

Hardcode env vars into the pipeline config.

### Additional context

Whether it's implemented or not, thanks for considering it!

### Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.
