### ISSUE TITLE
Use variables for secrets

### ISSUE THREAD

**Issue by lonix1** [woodpecker-ci/woodpecker#2375]
### Clear and concise description of the problem

According to [the docs](https://woodpecker-ci.org/docs/usage/secrets), a secret is supplied to the step as an uppercase environment variable.

For example, here are two global secrets named `docker_username` and `docker_password`:

```yml
steps:
  docker:
    image: docker
    commands:
      - echo $DOCKER_USERNAME
      - echo $DOCKER_PASSWORD
    secrets: [ docker_username, docker_password ]
```

That works, but isn't convenient - one will probably use those secrets multiple times in the same pipeline.

### Suggested solution

So it's better and more maintainable to use variables, for example:

```yml
variables:
  - &SECRET bearer_token

steps:

  restore:
    image: some_sdk
    commands:
      - restore packages --api-token "$BEARER_TOKEN"
    secrets: *SECRET

  push:
    image: some_sdk
    commands:
      - push packages --api-token "$BEARER_TOKEN"
    secrets: *SECRET

  deploy:
    image: some_sdk
    commands:
      - deploy packages --api-token "$BEARER_TOKEN"
    secrets: *SECRET

  other:
    # etc.
```

Notice how the `SECRET` variable is used, but one must nonetheless use the uppercase of the actual secret name `BEARER_TOKEN`. So in this case *using a variable adds no value*.

Please consider allowing this common use case? Then we could write this pipeline which is more sensible:

```yml
variables:
  - &SECRET bearer_token

steps:

  restore:
    image: some_sdk
    commands:
      - restore packages --api-token "$SECRET"      # <---- SECRET instead of BEARER_TOKEN
    secrets: *SECRET

  push:
    image: some_sdk
    commands:
      - push packages --api-token "$SECRET"         # <---- SECRET instead of BEARER_TOKEN
    secrets: *SECRET

  deploy:
    image: some_sdk
    commands:
      - deploy packages --api-token "$SECRET"       # <---- SECRET instead of BEARER_TOKEN
    secrets: *SECRET

  other:
    # etc.
```

### Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.
