### ISSUE TITLE
Woodpecker doesn't seem to start the webserver

### ISSUE THREAD

**Issue by mawoka-myblock** [woodpecker-ci/woodpecker#238]
Yea, I cant access Woodpecker...
My docker-compose:
```yaml
version: "3"

services:
  gitea:
    #image: gitea/gitea:1.10.3
    image: gitea/gitea:1.14.3
    container_name: gitea
    environment:
      - APP_NAME=Gitea
      - USER_UID=1000
      - USER_GID=1000
      - ROOT_URL=https://git.example.com
      #- SSH_DOMAIN=git.example.com
      #- SSH_PORT=2222
      - HTTP_PORT=3000
      - DB_TYPE=postgres
      - DB_HOST=gitea-db:5432
      - DB_NAME=gitea
      - DB_USER=postgres
      - DB_PASSWD=postgres
    restart: always
    volumes:
      - gitea:/data
    ports:
      - "8068:3000"
      #- "2222:2222"
    networks:
      - appnet

  gitea-db:
    image: postgres:alpine
    container_name: gitea-db
    restart: always
    volumes:
      - gitea-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gitea
    networks:
      - appnet

  woodpecker-server:
    image: laszlocloud/woodpecker-server:v0.9.0
    #image: ruanbekker/drone-server:basic-auth-1.2.1
    container_name: woodpecker-server
    ports:
      - "8067:80"
      - 9000
    volumes:
      - woodpecker-server-data:/var/lib/drone/
    restart: always
    depends_on:
      - gitea
    environment:
#      - GIN_MODE=release
      - DRONE_OPEN=true
      - DRONE_GITEA_CLIENT_ID=GITEA_CLIENT_ID
      - DRONE_GITEA_CLIENT_SECRET=GITEA_SECRER
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_GITEA_SERVER=https://git.example.com
      - DRONE_RPC_SECRET=SECRET
      - DRONE_HOST=https://ci.example.com
      - DRONE_USER_CREATE=username:USER,admin:true
#      - DRONE_SERVER_PROTO=http
      - DRONE_GITEA=true
    networks:
      - appnet

  woodpecker-agent:
    image: laszlocloud/woodpecker-agent:v0.9.0
    command: agent
    restart: always
    depends_on:
      - woodpecker-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=woodpecker-server:9000
      - DRONE_SECRET=SECRET
    networks:
      - appnet

volumes:
  gitea: {}
  gitea-db: {}
  drone: {}
  drone-agent: {}
  woodpecker-server-data:
networks:
  appnet:
    name: appnet
```

I also have useless logs for you:
```
woodpecker-server    | [GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
woodpecker-server    |  - using env:    export GIN_MODE=release
woodpecker-server    |  - using code:   gin.SetMode(gin.ReleaseMode)
woodpecker-server    | 
woodpecker-server    | [GIN-debug] GET    /logout                   --> github.com/laszlocph/woodpecker/server.GetLogout (12 handlers)
woodpecker-server    | [GIN-debug] GET    /login                    --> github.com/laszlocph/woodpecker/server.HandleLogin (12 handlers)
woodpecker-server    | [GIN-debug] GET    /api/user                 --> github.com/laszlocph/woodpecker/server.GetSelf (13 handlers)
woodpecker-server    | [GIN-debug] GET    /api/user/feed            --> github.com/laszlocph/woodpecker/server.GetFeed (13 handlers)
woodpecker-server    | [GIN-debug] GET    /api/user/repos           --> github.com/laszlocph/woodpecker/server.GetRepos (13 handlers)
woodpecker-server    | [GIN-debug] POST   /api/user/token           --> github.com/laszlocph/woodpecker/server.PostToken (13 handlers)
woodpecker-server    | [GIN-debug] DELETE /api/user/token           --> github.com/laszlocph/woodpecker/server.DeleteToken (13 handlers)
woodpecker-server    | [GIN-debug] GET    /api/users                --> github.com/laszlocph/woodpecker/server.GetUsers (13 handlers)
woodpecker-server    | [GIN-debug] POST   /api/users                --> github.com/laszlocph/woodpecker/server.PostUser (13 handlers)
woodpecker-server    | [GIN-debug] GET    /api/users/:login         --> github.com/laszlocph/woodpecker/server.GetUser (13 handlers)
woodpecker-server    | [GIN-debug] PATCH  /api/users/:login         --> github.com/laszlocph/woodpecker/server.PatchUser (13 handlers)
woodpecker-server    | [GIN-debug] DELETE /api/users/:login         --> github.com/laszlocph/woodpecker/server.DeleteUser (13 handlers)
woodpecker-server    | [GIN-debug] POST   /api/repos/:owner/:name   --> github.com/laszlocph/woodpecker/server.PostRepo (16 handlers)
woodpecker-server    | [GIN-debug] GET    /api/repos/:owner/:name   --> github.com/laszlocph/woodpecker/server.GetRepo (15 handlers)
woodpecker-server    | [GIN-debug] GET    /api/repos/:owner/:name/builds --> github.com/laszlocph/woodpecker/server.GetBuilds (15 handlers)
woodpecker-server    | [GIN-debug] GET    /api/repos/:owner/:name/builds/:number --> github.com/laszlocph/woodpecker/server.GetBuild (15 handlers)
woodpecker-server    | [GIN-debug] GET    /api/repos/:owner/:name/logs/:number/:pid --> github.com/laszlocph/woodpecker/server.GetProcLogs (15 handlers)
woodpecker-server    | [GIN-debug] GET    /api/repos/:owner/:name/logs/:number/:pid/:proc --> github.com/laszlocph/woodpecker/server.GetBuildLogs (15 handlers)
woodpecker-server    | [GIN-debug] GET    /api/repos/:owner/:name/files/:number --> github.com/laszlocph/woodpecker/server.FileList (15 handlers)
woodpecker-server    | [GIN-debug] GET    /api/repos/:owner/:name/files/:number/:proc/*file --> github.com/laszlocph/woodpecker/server.FileGet (15 handlers)
woodpecker-server    | [GIN-debug] GET    /api/repos/:owner/:name/secrets --> github.com/laszlocph/woodpecker/server.GetSecretList (16 handlers)
woodpecker-server    | [GIN-debug] POST   /api/repos/:owner/:name/secrets --> github.com/laszlocph/woodpecker/server.PostSecret (16 handlers)
woodpecker-server    | [GIN-debug] GET    /api/repos/:owner/:name/secrets/:secret --> github.com/laszlocph/woodpecker/server.GetSecret (16 handlers)
woodpecker-server    | [GIN-debug] PATCH  /api/repos/:owner/:name/secrets/:secret --> github.com/laszlocph/woodpecker/server.PatchSecret (16 handlers)
woodpecker-server    | [GIN-debug] DELETE /api/repos/:owner/:name/secrets/:secret --> github.com/laszlocph/woodpecker/server.DeleteSecret (16 handlers)
woodpecker-server    | [GIN-debug] GET    /api/repos/:owner/:name/registry --> github.com/laszlocph/woodpecker/server.GetRegistryList (16 handlers)
woodpecker-server    | [GIN-debug] POST   /api/repos/:owner/:name/registry --> github.com/laszlocph/woodpecker/server.PostRegistry (16 handlers)
woodpecker-server    | [GIN-debug] GET    /api/repos/:owner/:name/registry/:registry --> github.com/laszlocph/woodpecker/server.GetRegistry (16 handlers)
woodpecker-server    | [GIN-debug] PATCH  /api/repos/:owner/:name/registry/:registry --> github.com/laszlocph/woodpecker/server.PatchRegistry (16 handlers)
woodpecker-server    | [GIN-debug] DELETE /api/repos/:owner/:name/registry/:registry --> github.com/laszlocph/woodpecker/server.DeleteRegistry (16 handlers)
woodpecker-server    | [GIN-debug] PATCH  /api/repos/:owner/:name   --> github.com/laszlocph/woodpecker/server.PatchRepo (16 handlers)
woodpecker-server    | [GIN-debug] DELETE /api/repos/:owner/:name   --> github.com/laszlocph/woodpecker/server.DeleteRepo (16 handlers)
woodpecker-server    | [GIN-debug] POST   /api/repos/:owner/:name/chown --> github.com/laszlocph/woodpecker/server.ChownRepo (16 handlers)
woodpecker-server    | [GIN-debug] POST   /api/repos/:owner/:name/repair --> github.com/laszlocph/woodpecker/server.RepairRepo (16 handlers)
woodpecker-server    | [GIN-debug] POST   /api/repos/:owner/:name/move --> github.com/laszlocph/woodpecker/server.MoveRepo (16 handlers)
woodpecker-server    | [GIN-debug] POST   /api/repos/:owner/:name/builds/:number --> github.com/laszlocph/woodpecker/server.PostBuild (16 handlers)
woodpecker-server    | [GIN-debug] DELETE /api/repos/:owner/:name/builds/:number --> github.com/laszlocph/woodpecker/server.DeleteBuild (16 handlers)
woodpecker-server    | [GIN-debug] POST   /api/repos/:owner/:name/builds/:number/approve --> github.com/laszlocph/woodpecker/server.PostApproval (16 handlers)
woodpecker-server    | [GIN-debug] POST   /api/repos/:owner/:name/builds/:number/decline --> github.com/laszlocph/woodpecker/server.PostDecline (16 handlers)
woodpecker-server    | [GIN-debug] DELETE /api/repos/:owner/:name/builds/:number/:job --> github.com/laszlocph/woodpecker/server.DeleteBuild (16 handlers)
woodpecker-server    | [GIN-debug] DELETE /api/repos/:owner/:name/logs/:number --> github.com/laszlocph/woodpecker/server.DeleteBuildLogs (16 handlers)
woodpecker-server    | [GIN-debug] GET    /api/badges/:owner/:name/status.svg --> github.com/laszlocph/woodpecker/server.GetBadge (12 handlers)
woodpecker-server    | [GIN-debug] GET    /api/badges/:owner/:name/cc.xml --> github.com/laszlocph/woodpecker/server.GetCC (12 handlers)
woodpecker-server    | [GIN-debug] POST   /hook                     --> github.com/laszlocph/woodpecker/server.PostHook (12 handlers)
woodpecker-server    | [GIN-debug] POST   /api/hook                 --> github.com/laszlocph/woodpecker/server.PostHook (12 handlers)
woodpecker-server    | [GIN-debug] GET    /stream/events            --> github.com/laszlocph/woodpecker/server.EventStreamSSE (12 handlers)
woodpecker-server    | [GIN-debug] GET    /stream/logs/:owner/:name/:build/:number --> github.com/laszlocph/woodpecker/server.LogStreamSSE (15 handlers)
woodpecker-server    | [GIN-debug] GET    /api/queue/info           --> github.com/laszlocph/woodpecker/server.GetQueueInfo (13 handlers)
woodpecker-server    | [GIN-debug] GET    /api/queue/pause          --> github.com/laszlocph/woodpecker/server.PauseQueue (13 handlers)
woodpecker-server    | [GIN-debug] GET    /api/queue/resume         --> github.com/laszlocph/woodpecker/server.ResumeQueue (13 handlers)
woodpecker-server    | [GIN-debug] GET    /api/queue/norunningbuilds --> github.com/laszlocph/woodpecker/server.BlockTilQueueHasRunningItem (13 handlers)
woodpecker-server    | [GIN-debug] GET    /authorize                --> github.com/laszlocph/woodpecker/server.HandleAuth (12 handlers)
woodpecker-server    | [GIN-debug] POST   /authorize                --> github.com/laszlocph/woodpecker/server.HandleAuth (12 handlers)
woodpecker-server    | [GIN-debug] POST   /authorize/token          --> github.com/laszlocph/woodpecker/server.GetLoginToken (12 handlers)
woodpecker-server    | [GIN-debug] GET    /api/builds               --> github.com/laszlocph/woodpecker/server.GetBuildQueue (13 handlers)
woodpecker-server    | [GIN-debug] GET    /api/debug/pprof/         --> github.com/laszlocph/woodpecker/server/debug.IndexHandler.func1 (13 handlers)
woodpecker-server    | [GIN-debug] GET    /api/debug/pprof/heap     --> github.com/laszlocph/woodpecker/server/debug.HeapHandler.func1 (13 handlers)
woodpecker-server    | [GIN-debug] GET    /api/debug/pprof/goroutine --> github.com/laszlocph/woodpecker/server/debug.GoroutineHandler.func1 (13 handlers)
woodpecker-server    | [GIN-debug] GET    /api/debug/pprof/block    --> github.com/laszlocph/woodpecker/server/debug.BlockHandler.func1 (13 handlers)
woodpecker-server    | [GIN-debug] GET    /api/debug/pprof/threadcreate --> github.com/laszlocph/woodpecker/server/debug.ThreadCreateHandler.func1 (13 handlers)
woodpecker-server    | [GIN-debug] GET    /api/debug/pprof/cmdline  --> github.com/laszlocph/woodpecker/server/debug.CmdlineHandler.func1 (13 handlers)
woodpecker-server    | [GIN-debug] GET    /api/debug/pprof/profile  --> github.com/laszlocph/woodpecker/server/debug.ProfileHandler.func1 (13 handlers)
woodpecker-server    | [GIN-debug] GET    /api/debug/pprof/symbol   --> github.com/laszlocph/woodpecker/server/debug.SymbolHandler.func1 (13 handlers)
woodpecker-server    | [GIN-debug] POST   /api/debug/pprof/symbol   --> github.com/laszlocph/woodpecker/server/debug.SymbolHandler.func1 (13 handlers)
woodpecker-server    | [GIN-debug] GET    /api/debug/pprof/trace    --> github.com/laszlocph/woodpecker/server/debug.TraceHandler.func1 (13 handlers)
woodpecker-server    | [GIN-debug] GET    /metrics                  --> github.com/laszlocph/woodpecker/server/metrics.PromHandler.func1 (12 handlers)
woodpecker-server    | [GIN-debug] GET    /version                  --> github.com/laszlocph/woodpecker/server.Version (12 handlers)
woodpecker-server    | [GIN-debug] GET    /healthz                  --> github.com/laszlocph/woodpecker/server.Health (12 handlers)
```
That's everything I get. 
## What I also tried
I also tried port 443, no success...
## What happens
I simply get a `connection refused` and a 502 over NGINX which makes sense...
