### ISSUE TITLE
Support specific arch pipelines

### ISSUE THREAD

**Issue by samip5** [woodpecker-ci/woodpecker#2492]
### Clear and concise description of the problem

I need to be able to specify multiple pipelines that are only run on that specific architecture hardware as I have ARM64 and AMD64 agents.

### Suggested solution

The solution should be to allow the following syntax in pipeline:

```
platform:
  os: linux
  arch: amd64
```

### Alternative

Using Drone CI which supports this, but I'm not a fan.

### Additional context

The following does work in Drone CI and I would love for it to be supported for Woodpecker too.

```yaml
---
kind: pipeline
name: build-container-amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: build-amd64
    image: plugins/docker
    settings:
      username:
        from_secret: HARBOR_USER
      password:
        from_secret: HARBOR_PASS
      registry:
        from_secret: REGISTRY
      repo: registry.<snip>.fi/ahmia/${CI_REPO_NAME}
      tags:
        - latest-amd64

---
kind: pipeline
name: build-container-arm64
type: docker

platform:
  os: linux
  arch: arm64

steps:
  - name: build-arm64
    image: plugins/docker
    settings:
      username:
        from_secret: HARBOR_USER
      password:
        from_secret: HARBOR_PASS
      registry:
        from_secret: REGISTRY
      repo: registry.<snip>.fi/ahmia/${CI_REPO_NAME}
      tags:
        - latest-arm64

---
kind: pipeline
name: docker-manifest

clone:
  disable: true

platform:
  os: linux
  arch: amd64

steps:
  - name: manifest
    image: plugins/manifest
    pull: always
    settings:
      username:
        from_secret: HARBOR_USER
      password:
        from_secret: HARBOR_PASS
      registry:
        from_secret: REGISTRY
      target: registry.<snip>.fi/ahmia/${CI_REPO_NAME}
      template: registry.<snip>.fi/ahmia/${CI_REPO_NAME}:latest-ARCH
      platforms:
        - linux/amd64
        - linux/arm64

depends_on:
  - build-container-arm64
  - build-container-amd64
```

### Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.
