### ISSUE TITLE
Add custom SSH config when clone via SSH instead of HTTP

### ISSUE THREAD

**Issue by sinlov** [woodpecker-ci/woodpecker#2496]
### Clear and concise description of the problem

Currently woodpecker clones the repositories via HTTP, but some git ssh config must use custom config.

- support custom `git config` as [ssh_config](https://man.openbsd.org/ssh_config)
- support use `different ssh clone config` at different ssh clone pipline
- compatibility [plugin-git/Add option to use SSH for cloning repo #75](https://github.com/woodpecker-ci/plugin-git/pull/75) 

### Suggested solution

- workflow of this feature

1. create custom ssh config as file map

```
.
└── default
    ├── config
    ├── id_rsa
    └── known_hosts
```

2. setting `woodpecker-agent` arg `WOODPECKER_CUSTOM_SSH_GROUP_ROOT`

3. config

```yml
pipeline:
  clone:
    image: woodpeckerci/plugin-git
    settings:
      custom_ssh_group:
        name: default
        dryrun_host: host_name # optional
```

4.  at clone step

-  copy all file `custom_ssh_group` setting by `name` to `woodpecker-agent` path `$HOME/.ssh/` for git ssh to use

### Alternative

- custom ssh `config` at woodpecker agent as `WOODPECKER_CUSTOM_SSH_GROUP_ROOT`  when `$HOME/.ssh/config` after workspace init.  this path call `custom_ssh_group_root`.
  - for support use different key at different ssh clone pipline,  `WOODPECKER_CUSTOM_SSH_GROUP_ROOT` can set from volume or local path
  - `custom_ssh_group_root` file map as

```
.
├── bar
│   ├── config
│   ├── id_rsa
│   └── known_hosts
├── default
│   ├── config
│   ├── id_rsa
│   └── known_hosts
└── foo
    ├── config
    ├── id_rsa
    └── known_hosts
```
  -  copy all file `custom_ssh_group` setting by `name` to `woodpecker-agent` path `$HOME/.ssh/` for git ssh to use
  - each `config` file format as [ssh_config](https://man.openbsd.org/ssh_config)
  - each `known_hosts` file is optional
  - `default` folder is default ssh config, this is necessary，so less file map as

```
.
└── default
    ├── config
    ├── id_rsa
    └── known_hosts
```

- `pipeline-syntax` at `clone` can config by

```yml
pipeline:
  clone:
    image: woodpeckerci/plugin-git
    settings:
      custom_ssh_group:
        name: default
        dryrun_host: host_name # optional
```

> beacuse `settings. ssh_key` args (type string) is change  `git config core.sshCommand ssh -i <key>`,  don not use at same time

- support `settings.custom_ssh_group.dryrun_host` as `string` can set ssh test `host`
  -  will check config file when copy from `WOODPECKER_CUSTOM_SSH_GROUP_ROOT` and `name` set
  - copy succese, will run `exec` as `ssh -vT <dryrun_host>` for check ssh config

### Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.
