### ISSUE TITLE
Node Selector assigns wrong architecture for builds

### ISSUE THREAD

**Issue by pat-s** [woodpecker-ci/woodpecker#2505]
### Component

agent

### Describe the bug

Recently, I am seeing builds being assigned to the wrong nodes on our cluster. 
Inspecting the pods, I can see that the `platform` env, which comes from the matrix definition, is set to `amd64`. However, the nodeSelector is set to `arm64` instead.

```
Environment:
  platform:                        linux/amd64 

[...]

Node-Selectors:              kubernetes.io/arch=arm64 
```

The WF definition is as follows

```
platform: ${platform}

matrix:
  include:
    - DISTRIBUTION: ubuntu
      RELEASE: focal
      OS_RELEASE: 20.04
      platform: linux/amd64
    - DISTRIBUTION: ubuntu
      RELEASE: jammy
      OS_RELEASE: 22.04
      platform: linux/amd64
    - DISTRIBUTION: redhat/ubi8-minimal
      RELEASE: latest
      platform: linux/amd64
      OS_RELEASE: rhel8
    - DISTRIBUTION: redhat/ubi9-minimal
      RELEASE: latest
      platform: linux/amd64
      OS_RELEASE: rhel9
```

Could it be that https://github.com/woodpecker-ci/woodpecker/pull/2048 changed the logic in a way that `nodeSelector` is always set to `CI_SYSTEM_PLATFORM` and does not honor `platform` env anymore?

https://github.com/woodpecker-ci/woodpecker/blob/0eacbe8a33823b75e1ecdd738f6c0cad00bd7d68/pipeline/backend/kubernetes/pod.go#L112

Or maybe one of the changes within the recent months caused this behavior?
Tagging @6543 and @zc-devs as you both did modifications in this area lately.

I am not having enough experience in GO to make an educated judgement right now - all I can see is that `CI_SYSTEM_PLATFORM` is not honoring `platform` env and therefore the `nodeSelector` is wrong in the end :)

### System Info

```shell
`next-f8e91f00aa`
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by pat-s** [comment]
I can confirm that the issue is not present in v1.0.2.

**Comment by pat-s** [comment]
@6543 @zc-devs This is somewhat important and should be fixed before the next release or reverted (if no one has time). A response would be appreciated :)

**Comment by pat-s** [comment]
Given that 1.0.2 works and hence everything in `main` until July 29th should be fine, I suspect #2249 to be the issue. 

After testing: jup, `main` until 3954d85a5b962cc4cc3149a528a84866fe201a92 and the arch/nodeSelector mapping broke with #2249.

@klinux Are you able to look into this and fix the code? I'd revert the PR until it's fixed.

**Comment by zc-devs** [comment]
Is your WP server and agent run on `arm64`? And you want to run step on `amd64` by setting `platform` in the matrix , right? Does it work, if you set it in a step directly rather then in the matrix?

> nodeSelector is always set to CI_SYSTEM_PLATFORM and does not honor platform env anymore?

`nodeSelector` was always set from environment variable. It used to be `CI_SYSTEM_ARCH`. Then it became `CI_SYSTEM_PLATFORM`.

**Comment by pat-s** [comment]
> Is your WP server and agent run on arm64?

Agent runs on one (random assignment), agent runs on both (one of each).

> And you want to run step on amd64 by setting platform in the matrix , right?

Yes, that worked (at least) until #2249. See OP. It might be that another commit broke it but I haven't done further bisecting yet and just looked at the history of `pod.go`.

> Does it work, if you set it in a step directly rather then in the matrix?

I didn't test this but it doesn't matter much for the issue at hand as the matrix assignments as shown in the OP should work. So essentially, the mapping of `platform` must be honored (if defined) and carried over to the NodeSelector.

**Comment by pat-s** [comment]
Nope, not really. You're right. My bad! I was too fast judging on the history...the issue must be somewhere else.

**Comment by zc-devs** [comment]
I've done some tests on 61b567205140d049d510c9414aede9c89e28616d.

Pipeline:
```
skip_clone: true
platform: linux/mips
steps:
  test:
    image: alpine
    commands:
      - echo Hello from test
```

Agent on server:
```
update agents set platform = 'linux/mips';
```

Then agent doesn't pick up job.

Then I  changed labels on agent:
```
WOODPECKER_FILTER_LABELS: platform=linux/mips
```

And agent runs job successfully. But I have no `platform` env var on the pod.

Also I have `CI_SYSTEM_PLATFORM=linux/amd64`. And it looks right, because it is set up from [Agent's node platform](https://github.com/woodpecker-ci/woodpecker/blob/8791e6455734dfa07a658488f33e601554ea9e4f/agent/tracer.go#L79).

I guess, that your agent wrongly picks up job that intended for other agent. 

It's difficult to test as I have no different platforms. Maybe [labels](https://woodpecker-ci.org/docs/next/administration/agent-config#woodpecker_filter_labels) will help you somehow.

**Comment by pat-s** [comment]
I've figured it out. The matrix notation should look like this

```yml
matrix:
  include:
    - DISTRIBUTION: ubuntu
      ARCH: arm64
```

where `ARCH` is just an arbitrary key name.

Then, in the pipeline, `kubernetes.io/arch` must be set in the steps `backend_options` as follows:

```yml
[...]
    backend_options:
      kubernetes:
        nodeSelector:
          kubernetes.io/arch: "${ARCH}"
```

The documentation also needs to be updated. Will do...

**Comment by zc-devs** [comment]
So, there is nothing wrong with `nodeSelector` and Kubernetes backend. Issue should be renamed.

1. Platform labels [works](https://github.com/woodpecker-ci/woodpecker/issues/2505#issuecomment-1746794776).
2. Matrix works too:
```yaml
matrix:
  PLATFORM:
    - linux/amd64
    - windows/arm64

skip_clone: true
steps:
  test:
    image: alpine
    commands:
      - echo Hello from ${PLATFORM}
```
![Screenshot 2023-10-11 160514](https://github.com/woodpecker-ci/woodpecker/assets/127358482/60e5b408-0475-4363-b260-a18a42d2853b)
3. There is some bug in their combination:
```yaml
matrix:
  PLATFORM:
    - linux/amd64
    - windows/arm64

labels:
  platform: ${PLATFORM}

skip_clone: true
steps:
  test:
    image: alpine
    commands:
      - echo Hello from ${PLATFORM}
```
Server log:
```
{"level":"trace","error":"Cannot unmarshal '<nil>' of type <nil> into a string value","time":"2023-10-11T13:01:30Z","caller":"/woodpecker/server/pipeline/filter.go:69","message":"failed to parse config '.woodpecker.yml'"}
```
