### ISSUE TITLE
Release helm chart 

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#261]
Release helm chart to github-pages, so woodpecker can be installed via helm without the need to checkout this repo initially.

https://github.com/helm/chart-releaser
Chart-releaser could be executed by the woodpecker-ci:

```yml
pipeline:
  backend:
    image: quay.io/helmpack/chart-releaser:v1.2.1
    environment:
      - CR_OWNER=true
      - CR_GIT_REPO=${DRONE_HOST}
      - CR_PACKAGE_PATH=true
      - CR_TOKEN=${DRONE_GITHUB_CLIENT}
      - CR_GIT_BASE_URL="https://api.github.com/"
      - CR_GIT_UPLOAD_URL="https://uploads.github.com/"
    commands:
      - cr upload
```

or by using this github-action: https://github.com/helm/chart-releaser-action
