### ISSUE TITLE
CI_WORKSPACE set wrong in local backends

### ISSUE THREAD

**Issue by zxm8421** [woodpecker-ci/woodpecker#2610]
### Component

agent

### Describe the bug

pipeline file like this
```yml
---
labels:
  platform: linux/amd64
  backend: local

steps:
  hello:
    image: bash
    commands:
      - uname -a
      - pwd
      - echo $${CI_WORKSPACE}
      - ls -AFlh
      - echo "hello world 你好"
      - touch hello.txt
      - echo $${PATH}

  测试:
    image: bash
    commands:
      - uname -a
      - pwd
      - ls -AFlh
      - echo "hello world 你好 测试"
```

CI_WORKSPACE set wrong in local backends

![image](https://github.com/woodpecker-ci/woodpecker/assets/31583951/14e5d8da-8d98-4990-983b-0713e4dda1fc)

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"1.0.3"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).
