### ISSUE TITLE
server choose backends wrong sometimes

### ISSUE THREAD

**Issue by zxm8421** [woodpecker-ci/woodpecker#2611]
### Component

server

### Describe the bug

pipefile like this
```yml
---
labels:
  platform: windows/amd64
  backend: local

steps:
  hello:
    image: C:\Program Files\Git\bin\bash.exe
    commands:
      - uname -a
      - pwd
      - ls -AFlh
      - echo "hello world 你好"
      - touch hello.txt
      - echo $${PATH}

  测试:
    image: C:\Program Files\Git\bin\bash.exe
    commands:
      - uname -a
      - pwd
      - ls -AFlh
      - echo "hello world 你好 测试"
```

it runs on linux local backends sometimes,
when windows local backends offline.

![image](https://github.com/woodpecker-ci/woodpecker/assets/31583951/b34a2aa1-8981-4dd2-9e13-cd6ae8ec84ee)

and windows local pipeline runs on linux local backends sometimes,
when linux local backends offline.

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"1.0.3"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).
