### ISSUE TITLE
local backend dont work with "cmd" shell

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#2612]
if you have this config:
```
steps:
  # a demo step that say hello and show current work path
  hello:
    image: cmd.exe
    commands:
      - echo hello world
      - echo %CD%
```

for a **local** backend on **windows** you will get:
![image](https://github.com/woodpecker-ci/woodpecker/assets/24977596/5588fa2e-95e5-43c1-97e4-7fff4a6f2165)
