### ISSUE TITLE
Mising Discription for SE_Linux

### ISSUE THREAD

**Issue by birkenfunk** [woodpecker-ci/woodpecker#2646]
When using SE_Linux 
When using Linux Server with SE_Linux installed SE_Linux prevents access to Docker socket.

So there is a missing documentation for SE_Linux

```log
woodpecker-agent_1   | {"level":"error","error":"permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post \"http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/wp_d46cc036-e50d-4e31-beba-8c95cbc1de63/kill?signal=9\": dial unix /var/run/docker.sock: connect: permission denied","time":"2023-10-24T19:03:24Z","caller":"/src/pipeline/backend/docker/docker.go:301","message":"could not kill container 'wp_01hdhh3ydbxhyfn9ehz8eq2jpr_0_clone'"}
woodpecker-agent_1   | {"level":"error","error":"permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Delete \"http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/wp_d46cc036-e50d-4e31-beba-8c95cbc1de63?v=1\": dial unix /var/run/docker.sock: connect: permission denied","time":"2023-10-24T19:03:24Z","caller":"/src/pipeline/backend/docker/docker.go:304","message":"could not remove container 'wp_01hdhh3ydbxhyfn9ehz8eq2jpr_0_clone'"}
woodpecker-agent_1   | {"level":"error","error":"permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post \"http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/wp_2c297076-f725-40b1-910c-4e1dd9b8cae2/kill?signal=9\": dial unix /var/run/docker.sock: connect: permission denied","time":"2023-10-24T19:03:24Z","caller":"/src/pipeline/backend/docker/docker.go:301","message":"could not kill container 'wp_01hdhh3ydbxhyfn9ehz8eq2jpr_0_stage_0'"}
woodpecker-agent_1   | {"level":"error","error":"permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Delete \"http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/wp_2c297076-f725-40b1-910c-4e1dd9b8cae2?v=1\": dial unix /var/run/docker.sock: connect: permission denied","time":"2023-10-24T19:03:24Z","caller":"/src/pipeline/backend/docker/docker.go:304","message":"could not remove container 'wp_01hdhh3ydbxhyfn9ehz8eq2jpr_0_stage_0'"}
woodpecker-agent_1   | {"level":"error","error":"permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post \"http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/wp_53e393aa-80f7-4e69-bc8e-f61319f89472/kill?signal=9\": dial unix /var/run/docker.sock: connect: permission denied","time":"2023-10-24T19:03:24Z","caller":"/src/pipeline/backend/docker/docker.go:301","message":"could not kill container 'wp_01hdhh3ydbxhyfn9ehz8eq2jpr_0_stage_1'"}
woodpecker-agent_1   | {"level":"error","error":"permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Delete \"http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/wp_53e393aa-80f7-4e69-bc8e-f61319f89472?v=1\": dial unix /var/run/docker.sock: connect: permission denied","time":"2023-10-24T19:03:24Z","caller":"/src/pipeline/backend/docker/docker.go:304","message":"could not remove container 'wp_01hdhh3ydbxhyfn9ehz8eq2jpr_0_stage_1'"}
woodpecker-agent_1   | {"level":"error","error":"permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Delete \"http://%2Fvar%2Frun%2Fdocker.sock/v1.24/volumes/wp_01hdhh3ydbxhyfn9ehz8eq2jpr_0_default\": dial unix /var/run/docker.sock: connect: permission denied","time":"2023-10-24T19:03:24Z","caller":"/src/pipeline/backend/docker/docker.go:310","message":"could not remove volume 'wp_01hdhh3ydbxhyfn9ehz8eq2jpr_0_default'"}
woodpecker-agent_1   | {"level":"error","error":"permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Delete \"http://%2Fvar%2Frun%2Fdocker.sock/v1.24/networks/wp_01hdhh3ydbxhyfn9ehz8eq2jpr_0_default\": dial unix /var/run/docker.sock: connect: permission denied","time":"2023-10-24T19:03:24Z","caller":"/src/pipeline/backend/docker/docker.go:315","message":"could not remove network 'wp_01hdhh3ydbxhyfn9ehz8eq2jpr_0_default'"}
```

**Comment by pat-s** [comment]
Can you prove that it's related to selinux? I.e. by changing the selinux level and testing whether it works/fails with doing so?

**Comment by birkenfunk** [comment]
I already fixed it together with @6543 and after disabeling SeLinux it worked without any problems

To Fix it I had to execute the commands:
```shell
sudo ausearch -c 'woodpecker-agen' --raw | audit2allow -M my-woodpeckeragen
sudo semodule -X 300 -i my-woodpeckeragen.pp
```

After doing so Woodpecker worked without any problems

So maybe you could add a documentation for SeLinux.

**Comment by birkenfunk** [comment]
Here is my docker-compose.
The problem is that i can't give you the Logs any more because they are already gone and I can't revert the rules I changed. 
The commands are from the SeLinux tab from the Web Admin Console(Cockpit)

```yml
# docker-compose.yml
version: '3'

services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:next
    ports:
      - 8000:8000
    volumes:
      - woodpecker-server-data:/var/lib/woodpecker/
    env_file:
      - .env
    environment:
      - WOODPECKER_OPEN=false
      - WOODPECKER_HOST=${WOODPECKER_HOST}
      - WOODPECKER_GITEA=true
      - WOODPECKER_GITEA_URL=${WOODPECKER_GITEA_URL}
      - WOODPECKER_GITEA_CLIENT=${WOODPECKER_GITEA_CLIENT}
      - WOODPECKER_GITEA_SECRET=${WOODPECKER_GITEA_SECRET}
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
      - WOODPECKER_ADMIN=Birkenfunk
      - WOODPECKER_GRPC_SECURE=true
      - WOODPECKER_GRPC_VERIFY=true
#      - WOODPECKER_LOG_LEVEL=trace

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:next
    command: agent
    restart: always
    depends_on:
      - woodpecker-server
    volumes:
      - woodpecker-agent-config:/etc/woodpecker
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    environment:
      - WOODPECKER_SERVER=woodpecker-server:9000
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
      - WOODPECKER_BACKEND=docker
      - WOODPECKER_MAX_WORKFLOWS=3
#      - WOODPECKER_LOG_LEVEL=trace

volumes:
  woodpecker-server-data:
  woodpecker-agent-config:
```
