### ISSUE TITLE
Service selector doesn't match pod (Kubernetes)

### ISSUE THREAD

**Issue by zc-devs** [woodpecker-ci/woodpecker#2709]
### Component

agent, other

### Describe the bug

Woodpecker creates Kubernetes service with wrong selector. Therefore endpoints are empty and service is not ready (doesn't work).

### System Info

Woodpecker `next-f270be4940`.

Pipeline:
```yaml
services:
  database:
    image: mysql
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=example
    ports:
      - 3306

steps:
  get-version:
    image: ubuntu
    commands:
      - ( apt update && apt dist-upgrade -y && apt install -y mysql-client 2>&1 )> /dev/null
      - sleep 30s # need to wait for mysql-server init
      - echo 'SHOW VARIABLES LIKE "version"' | mysql -uroot -hdatabase test -pexample
```

### Additional context

![Screenshot 2023-11-02 183959](https://github.com/woodpecker-ci/woodpecker/assets/127358482/6bbfcb49-3603-41a0-8e94-ab021a6ee7d6)
![Screenshot 2023-11-02 184042](https://github.com/woodpecker-ci/woodpecker/assets/127358482/ba4629ba-07f3-4319-9ecf-6b90c41e3033)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).
