### ISSUE TITLE
Prevent user from naming pipeline job with internal name like git

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#272]
If I use git as a pipeline job, the pipeline execution hangs after executing the internal git command.

**Comment by 6543** [comment]
@anbraten can you add a demo pipeline config?

**Comment by 6543** [comment]
@anbraten tested:

```yml
pipeline:
  build:
    image: debian
    pull: true
    commands:
      - echo "Build test"
    when:
      event: [push, tag]

  git:
    image: debian
    pull: true
    commands:
      - echo "zap"

# The following statement causes the issue:
branches: main
```
and it worked just fine!
