### ISSUE TITLE
(Kubernetes) -  Add UDP Port Support for Pipeline Services

### ISSUE THREAD

**Issue by J-Ha** [woodpecker-ci/woodpecker#2727]
### Clear and concise description of the problem

At the moment there is for at least the Kubernetes backend no option to specify the type of a service port.
kubernetes defaults this to TCP

### Suggested solution

Add an option to specify the port kind, and keep tcp as default if nothing is defined 

```
services:
  udpservice:
    image: image
    ports:
    - 1234/udp
  tcpservice:
    image: image
    ports:
    - 2345/tcp
 tcpservice2:
    image: image
    ports:
    - 3456
```

     

### Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.
