### ISSUE TITLE
Cannot override container command

### ISSUE THREAD

**Issue by UnlimitedCookies** [woodpecker-ci/woodpecker#273]
Hi,

when I push to the repo it fails with this error message:
`Cannot override container command`

I don't know how to debug this properly. Maybe some info should be provided here.

My `.drone.yml`:
```
pipeline:
  build:
    image: debian
    commands:
      - echo "HELLO WORLD"
    when:
      event: [push, tag]

  package:
    image: debian
    command:
      - echo "zap"
    when:
      event: tag
```
