### ISSUE TITLE
Duplicate pipeline execution on tag event

### ISSUE THREAD

**Issue by UnlimitedCookies** [woodpecker-ci/woodpecker#274]
When I tag/release two builds are executed. One of them does the `when: event: tag` part and the other does not. I think this is because one of the builds is executed because Woodpecker sees a new branch.

![image](https://user-images.githubusercontent.com/49200216/130476754-79c74830-020d-4207-9acd-a5decdf716e5.png)

Weirdly enough, if I add a `branches: master` the build will time out saying exit code 0 on all steps without any further info from the step execution. [Might be a separate issue]

My `.drone.yml`:
```
pipeline:
  build:
    image: debian
    pull: true
    commands:
      - echo "HALLO WELT, KANNST DU MICH HOEREN"
    when:
      event: [push, tag]

  package:
    image: debian
    pull: true
    commands:
      - echo "zap"
    when:
      event: tag

# Not working :/
#branches: master
```

I am using Gitea as my VCS and have enabled all 4 webhook triggers in the settings.

**Comment by anbraten** [comment]
I think this is because the webhook is fired by Gitea for a new tag generation and the push to this new tag. Can you check the webhook history in Gitea. 

Maybe you could try something like:

```yml
when:
      event: [push, tag]
      branch: master
```
