### ISSUE TITLE
Can't authenticate btw. Gitea and woodpecker 

### ISSUE THREAD

**Issue by timskovjacobsen** [woodpecker-ci/woodpecker#277]
Thanks for maintaining this project! It looks very promising.

I would like to use woodpecker with Gitea. I saw in previous issues that OAuth should be working acc. to PR #226.

I'm trying to use the `docker-compose.yml` provided in the docs, with slight modifications:

```yml
# docker-compose.yml
version: '3'

services:
  woodpecker-server:
    image: laszlocloud/woodpecker-server:v0.9.0
    ports:
      - 80:8000
      - 9000
    volumes:
      - woodpecker-server-data:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_GITEA=true
      - DRONE_GITEA_SERVER=http://{my-domain}.net/
      - DRONE_GITEA_CLIENT={id_created_in_gitea_oauth_applicatoin}
      - DRONE_GITEA_SECRET={secret_created_in_gitea_oauth_applicatoin}
      - DRONE_SECRET={random_string}
      - DRONE_ADMIN=sysadm
      - DRONE_USER_CREATE=username:sysadm,admin:true
      - DRONE_SERVER_HOST=http://drone-server:80

  woodpecker-agent:
    image: laszlocloud/woodpecker-agent:v0.9.0
    command: agent
    restart: always
    depends_on:
      - woodpecker-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=woodpecker-server:9000
      - DRONE_SECRET={random_string}

volumes:
  woodpecker-server-data:
```

When I visit the drone server host and log in using the same admin user as I have created on the Gitea instance running at `http://{my-domain}.net/`, I see this:

![image](https://user-images.githubusercontent.com/17104278/130623237-fd8b37cb-529b-4b5d-af72-495d0ba9e3ec.png)

With this error log in the terminal:

`woodpecker-server_1  | time="2021-08-24T13:13:11Z" level=error msg="cannot authenticate user. basic auth required"`

## Another try

I tried using `woodpeckerci/woodpecker-server:latest` and `woodpeckerci/woodpecker-agent:latest` as suggested in #238.

Instead of seeing the woodpecker login screen, I see the [try.gitea.io](https://try.gitea.io/user/login) login screen. 

## Another try

I tried removing the `DRONE_GITEA_CLIENT` and `DRONE_GITEA_SECRET` in order to authorize communication with Gitea via username and password. It came with the exact same message as my original attempt.

## What I expected to happen

With the compose config posted above, I expected to see a page where I can press a "authorize Gitea" button and then access the woodpecker UI. From here, sync the repos and run builds.

Any help is appreciated and I will gladly contribute documentation should I get a working solution up and running with Gitea.

**Comment by UnlimitedCookies** [comment]
Hello there.

Please note that the docs on the dedicated website are unfortunately outdated. I think you need an ssl-encrypted website for proper oauth. 
I suggest trying my working docker-compose.yml that I based of the added environment variables. Sadly, Woodpecker still lacks a proper documentation page for Gitea like it has for Github.

So please try my config.
```
version: "3"

services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 9000:9000 #might not be needed
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_ADMIN=admin1,admin2
      - WOODPECKER_HOST=https://woodpecker.my-domain.com
      - WOODPECKER_SECRET={SECRET HERE}
      - WOODPECKER_GITEA=true
      - WOODPECKER_GITEA_CLIENT={client id from gitea web interface}
      - WOODPECKER_GITEA_SECRET={secret from gitea web interface}
      - WOODPECKER_GITEA_URL=https://gitea.my-domain.com
      - WOODPECKER_SERVER_CERT=/path/to/woodpecker.crt
      - WOODPECKER_SERVER_KEY=/path/to/woodpecker.key
    volumes:
      - ./woodpecker-data:/var/lib/drone/
      - ./woodpecker-cert:/etc/certs/woodpecker/
      - /etc/localtime:/etc/localtime:ro
  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:latest
    command: agent
    restart: unless-stopped
    depends_on:
      - woodpecker-server
    environment:
      - WOODPECKER_SERVER=woodpecker-server:9000
      - WOODPECKER_SECRET={SECRET HERE}
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
```
