### ISSUE TITLE
Allow to change entrypoint / shell for ci step

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#278]
# Problem

Currently `/bin/sh` is used as entrypoint for every ci step. If an image does not contain `/bin/sh` it can not be used with woodpecker ATM. For example `gcr.io/kaniko-project/executor:debug` only ships with `/bin/busybox`. 

```go
// File: /pipeline/frontend/yaml/compiler/convert.go

entrypoint = []string{"/bin/sh", "-c"}
command = []string{"echo $CI_SCRIPT | base64 -d | /bin/sh -e"}
```

# Solution

Allow to exec multiple commands with the agent instead of a single combined one. This could allow to use the default entrypoint or even a specific one.  Commands could be executed with something like `docker exec` instead.

# Workaround

Create a plugin as plugins can define their entrypoint.

**Comment by zc-devs** [comment]
As a temporary workaround we can try to create symbolic link:
```
pipeline:
  build-package:
    image: python:3.11.4-slim-bullseye
    commands:
      - ln -sf /bin/bash /bin/sh
```

**Comment by 6543** [comment]
Well from securety standpoint: as long as we handle it like normal steps there should not be a downside ... we just make sure that asap it is set ... it's not a plugin anymore

**Comment by zc-devs** [comment]
[For linux-like OS entrypoint and command](https://github.com/woodpecker-ci/woodpecker/blob/cef135eba5f21a3e4ad429f9af51f535ce907372/pipeline/backend/common/script.go#L30) look like mentioned above:
```
env["CI_SCRIPT"] = base64.StdEncoding.EncodeToString([]byte(generateScriptPosix(commands)))
env["HOME"] = "/root"
env["SHELL"] = "/bin/sh"
entry = []string{"/bin/sh", "-c"}
cmd = []string{"echo $CI_SCRIPT | base64 -d | /bin/sh -e"}
```

So, we depend on some `shell` _and_ `base64`. Seems we can change shell only and hope image would contain `base64` command. Am I right? Things are getting worse with Windows.

If we want to execute the `command images` like a general `kaniko`, then we can put entrypoint used by image instead of shell like below:
```
  build-image:
    image: gcr.io/kaniko-project/executor
    entrypoint: /kaniko/executor
```
```
env["SHELL"] = ""
var stepEntrypoint string
entry = []string{stepEntrypoint}
cmd = []string{"echo $CI_SCRIPT"}
```
We need to get rid of `-c` in entrypoint and ` | base64 -d | /bin/sh -e` in command. The consequence of this is that we can't use multiple commands in step, only one.

We should also distinguish somehow between `command images` and `regular` ones. Instead of some flag, maybe we can use `commands` for `regular images` and `command` for `command images`?
```
  build-image:
    image: gcr.io/kaniko-project/executor
    entrypoint: /kaniko/executor
    command:
      - --context ./ --dockerfile Dockerfile --destination docker.io/user/project
```
Or even doesn't set entrypoint in pipeline and `script.go`. Then image's entrypoint would be used:
```
  test:
    image: alpine/curl
    command:
      - http://nextcloud.com/cron.php
```

**Comment by zc-devs** [comment]
[For linux-like OS entrypoint and command](https://github.com/woodpecker-ci/woodpecker/blob/cef135eba5f21a3e4ad429f9af51f535ce907372/pipeline/backend/common/script.go#L30) look like mentioned above:
```
env["CI_SCRIPT"] = base64.StdEncoding.EncodeToString([]byte(generateScriptPosix(commands)))
env["HOME"] = "/root"
env["SHELL"] = "/bin/sh"
entry = []string{"/bin/sh", "-c"}
cmd = []string{"echo $CI_SCRIPT | base64 -d | /bin/sh -e"}
```

So, we depend on some `shell` _and_ `base64`. Seems we can change shell only and hope image would contain `base64` command. Am I right? Things are getting worse with Windows.

If we want to execute the `command images` like a general `kaniko`, then we can put entrypoint used by image instead of shell like below:
```
  build-image:
    image: gcr.io/kaniko-project/executor
    entrypoint: /kaniko/executor
```
```
env["SHELL"] = ""
var stepEntrypoint string
entry = []string{stepEntrypoint}
cmd = []string{"echo $CI_SCRIPT"}
```
We need to get rid of `-c` in entrypoint and ` | base64 -d | /bin/sh -e` in command. The consequence of this is that we can't use multiple commands in step, only one.

We should also distinguish somehow between `command images` and `regular` ones. Instead of some flag, maybe we can use `commands` for `regular images` and `command` for `command images`?
```
  build-image:
    image: gcr.io/kaniko-project/executor
    entrypoint: /kaniko/executor
    command:
      - --context ./ --dockerfile Dockerfile --destination docker.io/user/project
```
Or even doesn't set entrypoint in pipeline and `script.go`. Then image's entrypoint would be used:
```
  test:
    image: alpine/curl
    command:
      - http://nextcloud.com/cron.php
```
