### ISSUE TITLE
Allow setting name for matrix pipelines

### ISSUE THREAD

**Issue by JakobDev** [woodpecker-ci/woodpecker#2819]
### Clear and concise description of the problem

Since #2695 the build status of matrix pipelines gets correctly reported, what is awesome. However, there is still room for improvement. Currently it gets reported as `{name}/{number}`. It would be better if a name would be used instead of a number.

### Suggested solution

Add a new filed `matrixname` which allows setting the name for a matrix pipeline. With the [example from the documentation](https://woodpecker-ci.org/docs/usage/matrix-workflows) it could look like this:
```yaml
matrix:
  GO_VERSION:
    - 1.4
    - 1.3
  DATABASE:
    - mysql:5.5
    - mysql:6.5
    - mariadb:10.1

steps:
  build:
    image: golang:${GO_VERSION}
    commands:
      - go get
      - go build
      - go test

services:
  database:
    image: ${DATABASE}

matrixname: ${GO_VERSION}-${DATABASE}
```
This would be reported as e.g. `{name}/1.4-mysql:5.5`.

### Alternative

Of only one variable is used, we can also use the variable instead of the number.

### Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.
