### ISSUE TITLE
Service step doesn't change its status

### ISSUE THREAD

**Issue by zc-devs** [woodpecker-ci/woodpecker#2831]
### Component

web-ui

### Describe the bug

Running pipeline with a service, it doesn't change its status and logs are empty unless page are reloaded.

Pipeline:
```yaml
services:
  database:
    image: mysql
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=example
    ports:
      - 3306
steps:
  get-version:
    image: ubuntu
    commands:
      - ( apt update && apt dist-upgrade -y && apt install -y mysql-client 2>&1 )> /dev/null
      - sleep 60s # need to wait for mysql-server init
      - echo 'SHOW VARIABLES LIKE "version"' | mysql -uroot -hdatabase test -pexample
```

Start pipeline and click on the service step - logs exist:
![Screenshot 2023-11-16 152141](https://github.com/woodpecker-ci/woodpecker/assets/127358482/e63e8482-a135-4d45-88c8-80f5903fdf0e)

Then switch to the general step and wait to complete - there are logs, status changes to completed, execution timer stops:
![Screenshot 2023-11-16 152553](https://github.com/woodpecker-ci/woodpecker/assets/127358482/a0212711-9dfc-4593-9ba3-c822f64e3ce9)

Switch back to the service - now there are no logs, step is executing forever:
![Screenshot 2023-11-16 152702](https://github.com/woodpecker-ci/woodpecker/assets/127358482/f1900aaf-039c-4a0b-9e11-38818c02dae5)

After page reloading, all displays as expected - logs, status and execution timer:
![Screenshot 2023-11-16 152756](https://github.com/woodpecker-ci/woodpecker/assets/127358482/5a36e81a-b4d8-4bfa-b2a5-351a72076bdb)

The later should be without refreshing page.

### System Info

```shell
2.0.0-rc.0, Kubernetes
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).
