### ISSUE TITLE
Proxy environment variables not passed through in pipeline steps

### ISSUE THREAD

**Issue by OCram85** [woodpecker-ci/woodpecker#2858]
### Component

server, agent

### Describe the bug

If you try to set proxy related env vars in a pipeline step, they won't get used. They are present but without the given values:

```yaml
when:
  - event: [pull_request, tag, cron]
  - event: push
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}
      - renovate/*

variables:
  - &golang "golang:1.21"
  - proxy_args: &proxy_args
      - "http_proxy=http://swarmproxy:8888"
      - "https_proxy=http://swarmproxy:8888"
      - "no_proxy=.myhost.com"
      - "TESTENV=DEBUGGING"
steps:
  test:
    image: *golang
    environment:
      - <<: *proxy_args
    commands:
      - env | sort
      - go test -cover ./...
```

The output looks like this:

```shell
....
GOLANG_VERSION=1.21.4
GOPATH=/go
GOTOOLCHAIN=local
HOME=/root
HOSTNAME=45d463959e69
HTTPS_PROXY=
HTTP_PROXY=
NO_PROXY=
PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/woodpecker/src/xxxxxx/Templates/plugin-extend-env
SHELL=/bin/sh
TESTENV=DEBUGGING
http_proxy=
https_proxy=
no_proxy=
+ go test -cover ./...
go: downloading github.com/urfave/cli/v2 v2.25.7
go: downloading github.com/sirupsen/logrus v1.9.3
go: downloading github.com/Masterminds/semver/v3 v3.2.1
go: downloading github.com/joho/godotenv v1.5.1
semver.go:6:2: github.com/Masterminds/semver/v3@v3.2.1: Get "https://proxy.golang.org/github.com/%21masterminds/semver/v3/@v/v3.2.1.zip": dial tcp: lookup proxy.golang.org on 127.0.0.11:53: no such host
tools.go:3:8: github.com/joho/godotenv@v1.5.1: Get "https://proxy.golang.org/github.com/joho/godotenv/@v/v1.5.1.zip": dial tcp: lookup proxy.golang.org on 127.0.0.11:53: no such host
logger.go:6:2: github.com/sirupsen/logrus@v1.9.3: Get "https://proxy.golang.org/github.com/sirupsen/logrus/@v/v1.9.3.zip": dial tcp: lookup proxy.golang.org on 127.0.0.11:53: no such host
flags.go:4:2: github.com/urfave/cli/v2@v2.25.7: Get "https://proxy.golang.org/github.com/urfave/cli/v2/@v/v2.25.7.zip": dial tcp: lookup proxy.golang.org on 127.0.0.11:53: no such host
...
```

### System Info

```shell
{
  "source": "https://github.com/woodpecker-ci/woodpecker",
  "version": "1.0.5"
}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).
