### ISSUE TITLE
Branch specifier causes endless execution of pipeline with exit code `0`

### ISSUE THREAD

**Issue by UnlimitedCookies** [woodpecker-ci/woodpecker#290]
As mentioned in #274 when adding a branch specifier, the pipeline runs endlessly but shows exit code 0 for some reason on all steps. After multiple hours of _running_ I have to manually cancel the build. 

This issue is only caused by the tag/release event and not by a push to the repo.

![image](https://user-images.githubusercontent.com/49200216/131407785-984e3488-2d16-477a-b211-c112d5f6a59c.png)
![image](https://user-images.githubusercontent.com/49200216/131407820-c29f7a50-f0d2-4a4c-a436-85cda40d232a.png)

The `.drone.yml`:
```
pipeline:
  build:
    image: debian
    pull: true
    commands:
      - echo "Build test"
    when:
      event: [push, tag]

  package:
    image: debian
    pull: true
    commands:
      - echo "zap"
    when:
      event: tag

# The following statement causes the issue:
branches: master
```
I am using Gitea as my VCS and have enabled all 4 webhook triggers in the settings.
