### ISSUE TITLE
CI_PIPELINE_NUMBER Built-in environment variable not set correctly (or at all)

### ISSUE THREAD

**Issue by TheAngusMcFire** [woodpecker-ci/woodpecker#2929]
### Component

server

### Describe the bug

We use the CI_PIPELINE_NUMBER to tag our docker containers, but since the update to 2.0.0 CI_PIPELINE_NUMBER is always 0
Also the pipeline number in CI_PIPELINE_URL is always 0.

### System Info

```shell
version 2.0.0

woodpecker in k8s and agent as docker runner in VM
```

### Additional context

To reproduce:
```yaml
steps:
  triggerTest:
    image: debian:bookworm
    commands:
      - echo I triggered!
      - echo $CI_PIPELINE_NUMBER
      - echo $CI_PIPELINE_EVENT
      - echo $CI_STEP_NAME
      - echo $CI_STEP_NUMBER
      - echo $CI_PIPELINE_PARENT
      - echo $CI
      - echo $CI_PIPELINE_URL
```

Output:
```
+ echo I triggered!
I triggered!
+ echo $CI_PIPELINE_NUMBER
0
+ echo $CI_PIPELINE_EVENT
push
+ echo $CI_STEP_NAME
wp_01hhcbmfw90rnt0hnyd4f6c0sk_0_step_0
+ echo $CI_STEP_NUMBER
0
+ echo $CI_PIPELINE_PARENT
0
+ echo $CI
woodpecker
+ echo $CI_PIPELINE_URL
https://<hidden>/repos/6/pipeline/0
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).
