### ISSUE TITLE
Invalid hostAliases.ip in IPv6-only cluster

### ISSUE THREAD

**Issue by zc-devs** [woodpecker-ci/woodpecker#2991]
### Component

agent

### Describe the bug

Trying to run pipeline with a service in IPv6-only cluster. Get error:

![Screenshot 2023-12-22 141318](https://github.com/woodpecker-ci/woodpecker/assets/127358482/78d878a7-0d17-4d7f-b64b-774958b1f1a1)

### System Info

```shell
Woodpecker next-619858e0
K3s 1.28.4
```

### Additional context

[woodpecker-agent.log](https://github.com/woodpecker-ci/woodpecker/files/13751825/woodpecker-agent.log)

```yaml
services:
  database:
    image: mysql
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=example
    ports:
      - 3306/tcp
steps:
  get-version:
    image: ubuntu
    commands:
      - ( apt update && apt dist-upgrade -y && apt install -y mysql-client 2>&1 )> /dev/null
      - sleep 30s # need to wait for mysql-server init
      - echo 'SHOW VARIABLES LIKE "version"' | mysql -uroot -hdatabase test -pexample

```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).
