### ISSUE TITLE
JS error on repository activity / pipelines list page

### ISSUE THREAD

**Issue by zc-devs** [woodpecker-ci/woodpecker#3012]
### Component

web-ui

### Describe the bug

1. Open developer console in browser
2. Go to [repository activity](https://woodpecker.test.smthd.com/repos/1)
3. Get two errors

Chrome:
```
index-yc-Su7Fu.js:1
TypeError: Cannot read properties of undefined (reading 'slice')
    at PipelineList.vue_vue_type_script_setup_true_lang-DuVPdeQs.js:1:4843
    at r (index-yc-Su7Fu.js:1:17606)
    at ya (index-yc-Su7Fu.js:1:26645)
    at ListItem.vue_vue_type_script_setup_true_lang-J7Q-CsOV.js:1:503
    at Object.r [as default] (index-yc-Su7Fu.js:1:17606)
    at Proxy.<anonymous> (index-yc-Su7Fu.js:25:15333)
    at Es (index-yc-Su7Fu.js:1:17922)
    at wo.K [as fn] (index-yc-Su7Fu.js:1:42078)
    at wo.run (index-yc-Su7Fu.js:1:5674)
    at R.h.update (index-yc-Su7Fu.js:1:42357)
```

Firefox
```
index-Hkbfabkk.js:1:15193
TypeError: e.value.commit is undefined
```

### System Info

```shell
next-acec955943
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by zc-devs** [comment]
Ohh... Some guess have come up...

I logged in and worked in Woodpecker as `usr`. In Gitea repository `wp-test` is owned by `usr` and I commited with `usr`'s email.

BUT, when I commited first time, I was prompted for authentication, chose "credentials helper". The problem is at this time I was logged in as `adm`. So all my commits was from `adm` user. Manual pipeline triggering run by `usr` as expected.

`e.value.commit is undefined` - seems like `usr` have no rights to fetch commit information from other user (or from admin?). I relogined in Gitea as normal `usr`, but runs from `adm` still in the history, therefore I always get error.

Test instance is down currently. I'll check again later.

**Comment by zc-devs** [comment]
>  seems like usr have no rights to fetch commit information from other user (or from admin?)

Nope. General user cannot push to other user repo (by default, at least). Admin can, [but there are no errors](https://woodpecker.test.smthd.com/repos/2).

> e.value.commit is undefined

I've just looked at `api/repos/1/pipelines` response and found this [pipeline run without commit](https://woodpecker.test.smthd.com/repos/1/pipeline/32):
```yaml
{
    "id": 32,
    "number": 32,
    "author": "usr",
    "parent": 0,
    "event": "manual",
    "status": "error",
    "errors": [
        {
            "type": "generic",
            "message": "pipeline definition not found in usr/wp-test",
            "is_warning": false,
            "data": null
        }
    ],
    "enqueued_at": 1703438701,
    "created_at": 1703438701,
    "updated_at": 1703438701,
    "started_at": 1703438701,
    "finished_at": 1703438701,
    "deploy_to": "",
    "commit": "",
    "branch": "2727-port-protocol",
    "ref": "2727-port-protocol",
    "refspec": "",
    "clone_url": "",
    "title": "",
    "message": "MANUAL PIPELINE @ 2727-port-protocol",
    "timestamp": 1703438701,
    "sender": "",
    "author_avatar": "https://gitea.test.smthd.com/avatars/ae5a44010207eb61f78f920f9bf2e888",
    "author_email": "user@local",
    "forge_url": "https://gitea.test.smthd.com/usr/wp-test",
    "reviewed_by": "",
    "reviewed_at": 0
}
```

TBH, I don't remember what was wrong with this run...
