### ISSUE TITLE
depends_on incorrectly detects cycles

### ISSUE THREAD

**Issue by xfix** [woodpecker-ci/woodpecker#3048]
### Component

server

### Describe the bug

The following workflow incorrectly detects a cycle:

```yaml
steps:
  a:
    image: ubuntu
    commands:
      - echo a
  b:
    image: ubuntu
    commands:
      - echo b
    depends_on: [a]
  c:
    image: ubuntu
    commands:
      - echo c
    depends_on: [a]
  d:
    image: ubuntu
    commands:
      - echo d
    depends_on: [b, c]
```

> cycle detected: [d c]

This is due to the DAG detection code not marking node as unvisited when returning from DFS visit.

I will send a PR for this.

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"2.1.1"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).
