### ISSUE TITLE
Allow steps/services to have same name

### ISSUE THREAD

**Issue by qwerty287** [woodpecker-ci/woodpecker#3109]
See https://github.com/woodpecker-ci/woodpecker/pull/3079

Services can't have names that steps have, also adding another step `clone` does not work.

I think we can also disallow this but then we should add a linter for it.

**Comment by 6543** [comment]
No woodpecker should just handle it!

We use uuid's for all steps internaly so equal names should not have any impact

**Comment by 6543** [comment]
(So i considder it a bug)

**Comment by 6543** [comment]
found it finally:  #3143

tested with docker backend and config:
```yml
steps:
    wait:
        image: "bash"
        commands:
            - "echo type: step"
            - "sleep 10s"
            - "echo hihi step"
            - "sleep 30s"

services:
    wait:
        image: "bash"
        commands:
            - "echo type: service"
            - "sleep 10s"
            - "echo hihi service"
            - "sleep 30s"
```
