### ISSUE TITLE
Add a cookbook 

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#316]
Add all kinds of samples with woodpecker to the documentation to give new users an idea what is possible and how common pipelines can be created:

For example:
- Caching files like `node_modules/`
- Uploading artifacts
- Notify with slack after a pipeline succeeds or fails

**Comment by 6543** [comment]
Even better than samples are links to projects using us ... (link to conf file)

**Comment by smainz** [comment]
Here is one recipe I can contribute.  Questions:

1. Is there a better approach?
2. Where would be a place to store this?
3. Is anybody interested in a plugin which will automate the step, so you do not have to copy and paste the code in all pipelines?

---
## Interact with git repository in your steps

### Problem

Woodpecker provides a clone step for cloning the repository into the workspace but does not expose username and password for interacting with the git repository in subsequent steps.
If your pipeline steps need to interact with the git repository (be it a simple `git fetch`, update the version of a project `npm version minor` or a complete gitflow release process) you have to provide a means to do so.
This is how to provide **all** subsequent steps in the pipeline with access to the repo it was cloned from.

### Recipe

1.	Create a user in the forge who has the required permissions on the repo
4.	Create a ssh key for that user and add the public key to the forge
5.	Add the private key of this user to woodpecker (either global, repo or pipeline level) using the name `WOODPECKER_SSH_KEY`
6.	Add this to your pipeline before the steps which require access to the git repository:

    ```yaml
    pipeline:
      - name: Provide access to git repo
        image: woodpeckerci/plugin-git
        secrets:
          - WOODPECKER_SSH_KEY
        commands:
          # Prepare ssh key to use with git      
          - echo "$${WOODPECKER_SSH_KEY}" >  $(pwd)/.git/woodpecker.key 
          - chmod 600 $(pwd)/.git/woodpecker.key 
          # Define git user
          - git config --local user.email "woodpecker-ci@dynaware.de"
          - git config --local user.name "Woodpecker-CI"
          - git config --local core.sshCommand 'ssh -i $(pwd)/.git/woodpecker.key -o StrictHostKeyChecking=no'     
          # Change url of origin from http to ssh
          - SSH_REPO_URL=$$(git remote get-url origin | sed -E -e "s/https?:\\/\\//git@/g" -e "s/\\//:/") 
          - git remote set-url origin $${SSH_REPO_URL}         
    ```

Of course you can change the name of the secret of the ssh key, the gut user name and git user email to your taste.

Here is an example on how to interact with the repo in the next step. The only thing required is an image with git installed.
```
      - name: Use git credentials  
        image: woodpeckerci/plugin-git
        commands:
          - git fetch
```

The recipe *abuses* the `.git` repository to persist the ssh key file between different steps. The reason for this is thet .git is ignored by git and you do not get untracked file you would have otherwise to care about. Usually on would place a proper config in `~/.ssh/config`, but this does not persist between steps.
