### ISSUE TITLE
Pipeline with service doesn't work (K8s)

### ISSUE THREAD

**Issue by zc-devs** [woodpecker-ci/woodpecker#3178]
### Component

server, agent

### Describe the bug

When running pipeline with service, it going to start, but there is no pods and even attempts to create them.
There are no errors and WP pods (Server, Agent) restarts.

Pipeline:
```yaml
skip_clone: true
services:
  server:
    image: digitalocean/doks-debug
    commands:
      - echo 'This is test server' | nc -l -6 1234
    ports:
      - 1234
steps:
  client:
    image: digitalocean/doks-debug
    commands:
      - nc -v -6 -w 10 server 1234
```

Result:
![Screenshot 2024-01-12](https://github.com/woodpecker-ci/woodpecker/assets/127358482/4c97de70-da33-4289-b720-808804fbbf16)

### System Info

```shell
`next-a5fa810bcc`
```

### Additional context

[woodpecker-server.log](https://github.com/woodpecker-ci/woodpecker/files/13920400/woodpecker-server.log)
[woodpecker-agent.log](https://github.com/woodpecker-ci/woodpecker/files/13920401/woodpecker-agent.log)

https://woodpecker.test.smthd.com/repos/1/pipeline/85

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).
