### ISSUE TITLE
Path condition is not working as expected

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#324]
### Component

server

### Describe the bug

~~Although no docs files have been changed in #281, the pipeline for the documentation has been executed. There seems to be a bug in the path matching or with the current config.~~

Edit: The Woodpecker instance under `https://wp.laszlo.cloud` isn't using the latest version of Woodpecker. Because of this path wasn't supported by the server at all and so the server ignored it.

### System Info

Relevant CI execution: https://wp.laszlo.cloud/woodpecker-ci/woodpecker/340/4

Relevant CI config: (docs.yml)

```yml
clone:
  git:
    image: plugins/git:next

branches: master

pipeline:
  deploy-docs:
    image: node:14-alpine
    secrets:
      - BOT_PRIVATE_KEY
    environment:
      - USE_SSH=true
      - GIT_USER=woodpecker-bot
      - DEPLOYMENT_BRANCH=master
    commands:
      - apk add openssh-client git
      - mkdir -p $HOME/.ssh
      - ssh-keyscan -t rsa github.com >> $HOME/.ssh/known_hosts
      - echo "$BOT_PRIVATE_KEY" > $HOME/.ssh/id_rsa
      - chmod 0600 $HOME/.ssh/id_rsa
      - git config --global user.email "woodpecker-bot@obermui.de"
      - git config --global user.name "woodpecker-bot"
      - cd docs/
      - yarn install --frozen-lockfile
      - yarn deploy
    when:
      event: push
      branch: master
      path: "docs/*"

  build-docs-pr:
    image: node:14-alpine
    commands:
      - cd docs/
      - yarn install --frozen-lockfile
      - yarn build
    when:
      event: [pull_request]
      path: "docs/*"
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.github.io/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy).
