### ISSUE TITLE
User secret not found when triggering deployment

### ISSUE THREAD

**Issue by philipkozeny** [woodpecker-ci/woodpecker#3267]
### Component

server, agent

### Describe the bug

I am working on a pipeline configuration to enable each user to deploy to a server using their own private SSH key. These keys are intended to be stored as user secrets.

The users set up a user secret in their profile, named `ssh_deploy_prod_key`, containing their private SSH key.
The deployment is triggered through the web interface. 

Problem: Despite this setup, the deployment fails because the pipeline does not seem to recognize or access the user secrets as intended. Every time a deployment is triggered, I encounter the error: `Secret "ssh_deploy_prod_key" not found or not allowed to be used.`

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"2.2.2"}
```

### Additional context

Here's part of the pipeline:

```
  deploy-prod:
    image: *deployer_image
    pull: true
    commands:
      - eval `ssh-agent -s` && echo $SSH_DEPLOY_PROD_KEY | base64 -d | ssh-add -
      - deploy.py deployment.prod.json
    secrets: [ssh_deploy_prod_key]
    when:
      - event: [deployment]
```

here's the error message: ```[generic] secret "ssh_deploy_prod_key" not found or not allowed to be used```

here's the sqlite entry of the secret: 
```
secret_id|secret_repo_id|secret_name|secret_value|secret_images|secret_events|secret_org_id
36|0|ssh_deploy_prod_key|asdf|[]|["deployment","push"]|4
```
 The reference org is 
```
id|name|is_user|private
4|my.username|1|0
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
