### ISSUE TITLE
Filtered steps and depends_on (step)

### ISSUE THREAD

**Issue by johchur** [woodpecker-ci/woodpecker#3278]
### Component

server

### Describe the bug

One cannot use a filtered step in the depends_on clause. If you try it, the linter rejects the configuration
![image](https://github.com/woodpecker-ci/woodpecker/assets/99276246/ad6f2e0e-f9db-47ab-a55a-31c29c8684d0)

This prohibits the combination of parallel steps and optional steps in the same pipeline.

Minimal reproducer:
```
steps:
  - name: filtered
    image:  alpine
    commands:
      - echo "step 1"
    when:
      branch:
        - xyz

  - name: unconditional
    image: alpine
    commands:
      - echo "step 2"
    depends_on:
      - filtered
```

### System Info

```shell
Version 2.2.2
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
