### ISSUE TITLE
Multiple flaws when running pipelines with the same service (K8s)

### ISSUE THREAD

**Issue by zc-devs** [woodpecker-ci/woodpecker#3288]
### Component

server, agent

### Describe the bug

User-1 have pipeline in repository `wp-test`, he [runs](https://woodpecker.test.smthd.com/repos/1/pipeline/139) `gitea-integration-test` branch:
```yaml
skip_clone: true
services:
  postgres:
    image: digitalocean/doks-debug
    commands:
      - echo 'This is Gitea Postgres test server' | nc -l -6 5432
    ports:
      - 5432
steps:
  gitea:
    image: digitalocean/doks-debug
    commands:
      - nc -v -6 -w 10 postgres 5432
```

User-2 have pipeline below in his `wp-test-2` repository and `woodpecker-integration-test` branch:
```yaml
skip_clone: true
services:
  postgres:
    image: digitalocean/doks-debug
    commands:
      - echo 'This is Woodpecker Postgres test server' | nc -l -6 5432
    ports:
      - 5432
steps:
  wp:
    image: digitalocean/doks-debug
    commands:
      - nc -v -6 -w 10 postgres 5432
```
When User-1's pipeline service and service pod was launched, User-2 [ran his own](https://woodpecker.test.smthd.com/repos/2/pipeline/13).

Bugs:
1. User-2's pipeline was cancelled  with `error":"services "postgres" already exists`.
2. User-1's Service and Service Pod were deleted because User-2's pipeline cleaned up resources and the names were the same - `postgres`.

### System Info

```shell
`next-0b5eef7d1e`, 1 Server, 1 agent, max workflows 2.
```

### Additional context

[woodpecker-agent.log](https://github.com/woodpecker-ci/woodpecker/files/14075623/woodpecker-agent.log)

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
