### ISSUE TITLE
Templates for manual workflows

### ISSUE THREAD

**Issue by CodeDoctorDE** [woodpecker-ci/woodpecker#3326]
### Clear and concise description of the problem

When running many manual workflows, it is not very handy to input the keys on every run.

### Suggested solution

Create a system for github action like form where you add default values, checkboxes and more.
![image](https://github.com/woodpecker-ci/woodpecker/assets/20452814/feeb85ea-37fd-4cd2-86e8-783b5859347d)
The syntax should be like in github actions:
```yaml
    inputs:
      next_version:
        default: "0.0.0"
        description: "The next version to be released"
        required: false
      stable:
        default: false
        description: "Is this version stable?"
        type: boolean
        required: false
```

Maybe adding an extra type of event for tis.

### Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by zc-devs** [comment]
I propose to just display [ENV](https://woodpecker-ci.org/docs/usage/environment) vars from workflow and set default value defined in yaml.
```yaml
 steps:
   - name: build
     image: golang
     environment:
       - CGO=0
       - GOOS=linux
       - GOARCH=amd64
       - DISABLE_CACHE
     commands:
       - go build
       - go test
```

![Screenshot 2024-02-05](https://github.com/woodpecker-ci/woodpecker/assets/127358482/f753caa8-b768-4f88-a9bf-3f1290faa1b0)

**Comment by zc-devs** [comment]
>make a opt-in/out for this for internal env vars?

Do you mean [built-in-environment-variables](https://woodpecker-ci.org/docs/usage/environment#built-in-environment-variables). I'm afraid, it is not gonna work. Just look, how much vars Server sends to Agent :) (if you on Kubernetes, just describe pod).

**Comment by smainz** [comment]
Just one thing to consider: 

We are using the manual pipeline execution to perform builds too, but there are much more environment variables in the steps than need to be set / overriden while performing a build / deployment.

Would a config like 
```yml
   environement-input: 
     - BUILD_NUMER: <proposed value>
       MATCH_REX: <some regex to validate the input>
```
   
be an option?

At the moment we have a seperate step to validate the ENV vars to overcome typos.

**Comment by CodeDoctorDE** [comment]
That looks good.
In the future we could expand this by adding dropdowns with values: ["one", "two", "three"]

**Comment by zc-devs** [comment]
I'm thinking towards having special syntax for inputs now as both of you have mentioned.
I've just looked at one of my pipelines:
```yaml
# Environments
# SKIP_PACKAGE=true|false - skip package step
# APP_TAG=0.0.1 - override CI_COMMIT_TAG var, application release version

steps:
  set-env:
    image: debian:bookworm-slim
    commands:
      - .cicd/set-env.sh
  package:
    when:
      evaluate: 'SKIP_PACKAGE != "true"'
    image: python:3.12.1-slim-bookworm
    commands:
      - .cicd/package.sh
    secrets:
      - twine_username
      - twine_password
```
As we can see, I use variables that aren't defined in `environment` sections. Some of them are not used in pipeline definition even.
Furthermore, your variants would make possible enums
> dropdowns with values: ["one", "two", "three"]
