### ISSUE TITLE
yaml linter error warnning when.event.6 must be one of the following

### ISSUE THREAD

**Issue by sinlov** [woodpecker-ci/woodpecker#3356]
### Component

server, web-ui

### Describe the bug

update woodpecker-ci version to 2.3.0 with [Add release event #3226](https://github.com/woodpecker-ci/woodpecker/pull/3226)

release event as

```yml
when:
  path:
    exclude:
      - README.md
      - LICENSE
      - .github/**
  event:
    - manual
    - push
    - pull_request
    - pull_request_closed
    - tag
    - deployment
    - release
```

will show `Warnings`

```
[linter]
go-ci-docker: when
Must validate one and only one schema (oneOf)
[linter]
go-ci-docker: when.event
Must validate one and only one schema (oneOf)
[linter]
go-ci-docker: when.event.6
when.event.6 must be one of the following: "push", "pull_request", "pull_request_closed", "tag", "deployment", "cron", "manual"
```

![image](https://github.com/woodpecker-ci/woodpecker/assets/3433415/fdc1b9a3-f890-4c32-ac18-b2771deccac5)

### System Info

```shell
docker-compose


image: woodpeckerci/woodpecker-server:v2.3.0
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
