### ISSUE TITLE
Setting WOODPECKER_DATABASE_DATASOURCE_FILE does not work as expected when using docker image

### ISSUE THREAD

**Issue by smainz** [woodpecker-ci/woodpecker#3389]
### Component

server, other

### Describe the bug

Using this `docker-compose.yml` snippet

```yaml
  server:
    image: *woodpecker-server-image
    restart: unless-stopped
    expose:
      - 9000
    volumes:
      - ./woodpecker-server-data:/var/lib/woodpecker/
      - ./secrets/woodpecker/agent-secret.conf:/run/secrets/agent-secret.conf:ro
      - ./secrets/woodpecker/gitea-secret.conf:/run/secrets/gitea-secret.conf:ro
      - ./secrets/woodpecker/gitea-client.conf:/run/secrets/gitea-client.conf:ro
      - ./secrets/woodpecker/docker-config.json:/run/secrets/docker-config.json:ro
      - ./secrets/woodpecker/woodpecker-datasource.conf:/run/secrets/woodpecker-datasource.conf
    environment:
      - WOODPECKER_DATABASE_DRIVER=postgres
      - WOODPECKER_DATABASE_DATASOURCE_FILE=/run/secrets/woodpecker-datasource.conf
```

does not pick up the datasource secrets from the file, but will try to use `/var/lib/woodpecker/woodpecker.sqlite`

Log:

```txt
server-1  | 9:12AM TRC woodpecker/src/github.com/woodpecker-ci/woodpecker/cmd/server/setup.go:88 > setup datastore: store.Opts{Driver:"postgres", Config:"/var/lib/woodpecker/woodpecker.sqlite", XORM:store.XORM{Log:true, ShowSQL:true}}
```

The reason is, that the env var `WOODPECKER_DATABASE_DATASOURCE` is set in the Dockerfile and takes precedence.

To make it work one has to cancel this environment variable by using this:

```yaml
    environment:
      - WOODPECKER_DATABASE_DRIVER=postgres
      - WOODPECKER_DATABASE_DATASOURCE
      - WOODPECKER_DATABASE_DATASOURCE_FILE=/run/secrets/woodpecker-datasource.conf
```

**Note:** No equal sign behind `WOODPECKER_DATABASE_DATASOURCE` 

Had to find out the hard way. 

Should this be documented in https://github.com/woodpecker-ci/woodpecker/blob/5e0ec973baea3be1c4f6514b2ce778bfc0c961d6/docs/docs/30-administration/10-server-config.md?plain=1#L66-L102

If you agree, that is is only a documentation issue, I will provide a PR.

### System Info

```shell
Docker Image `woodpeckerci/woodpecker-server:v2.3.0`
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
