### ISSUE TITLE
matrix workflows set up environment in wrong way

### ISSUE THREAD

**Issue by rockdrilla** [woodpecker-ci/woodpecker#3436]
### Component

server

### Describe the bug

Consider following `.woodpecker.yml`:
```yaml
variables:
  - &my_testing_var1 'first value'

matrix:
  MY_MATRIX_ENV:
    - aaa
    - bbb

steps:
  - name: test-env
    image: busybox
    environment:
      MY_TESTING_VAR1: *my_testing_var1
      MY_TESTING_VAR2: "second value"
    commands:
      - |
        echo "$${MY_MATRIX_ENV:?}"
        echo "$${MY_TESTING_VAR1:?}"
        echo "$${MY_TESTING_VAR2:?}"
```

Expected output (e.g. with `MY_MATRIX_ENV=aaa`):
```
aaa
first value
second value
```

Actual output (e.g. with `MY_MATRIX_ENV=aaa`):
```
aaa
sh: MY_TESTING_VAR1: parameter not set or null
```

However, I've detected that it sets provided variables in following manner:
```sh
PLUGIN_MY_TESTING_VAR1="first value"
PLUGIN_MY_TESTING_VAR2="second value"
```

### System Info

```shell
docker.io/woodpeckerci/woodpecker-server:next-5b0430ab4a
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
