### ISSUE TITLE
Overriding 'entrypoint' in kubernetes backend does not work

### ISSUE THREAD

**Issue by everflux** [woodpecker-ci/woodpecker#3477]
### Component

agent

### Describe the bug

I have a workflow that specifies an entrypoint, during execution the following error is shown

`Additional property entrypoint is not allowed`

### System Info

```shell
Woodpecker 2.3.0, docker.io/woodpeckerci/woodpecker-agent:v2.3.0
```

### Additional context

Pipeline snippet

```
cache-baseimages:
    image: gcr.io/kaniko-project/warmer
    entrypoint:
    - /kaniko/warmer
    - --dockerfile=./Dockerfile
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
