### ISSUE TITLE
Config service broken with 2.4.x

### ISSUE THREAD

**Issue by Sebclem** [woodpecker-ci/woodpecker#3528]
### Component

server, agent

### Describe the bug

Since update to 2.4.x, my config service as stopped working, this is my setup: 
In my app repo, my .woodpecker.yml contain only this:
```yml
extend: https://mygiteahostname/sebclem/woodpecker-pipeline-config/raw/branch/main/playbook.yml
```
then i have setup a config service with `WOODPECKER_CONFIG_SERVICE_ENDPOINT`, this is the response form my service:
```json
{
	"configs": [
		{
			"name": "playbook.yml",
			"data": "steps:\n  check-ansible-syntax:\n    image: xxxxxxxxx/sebclem/woodpecker-ansible-runner\n    pull: true\n    settings:\n      playbook: playbooks/install.yml\n      galaxy_file: roles/requirements.yml\n      check_syntax: true\n      vault_token:\n        from_secret: ansible_vault_token\n    when:\n      - event: \"push\"\n        branch: [main, master]\n      - event: [pull_request, manual, deployment]\n\n  run-ansible-playbook:\n    image: xxxxxxxxx/sebclem/woodpecker-ansible-runner\n    pull: true\n    settings:\n      verbosity: ${verbosity=0}\n      limit: ${limit}\n      tags: ${tags}\n      playbook: playbooks/install.yml\n      galaxy_file: roles/requirements.yml\n      vault_token:\n        from_secret: ansible_vault_token\n      private_key:\n        from_secret: ansible_private_key\n    when:\n      environment: production\n      event: deployment\n\nwhen:\n  - event: \"push\"\n    branch: [main, master]\n  - event: [pull_request, manual, deployment]\n"
		}
	]
}
```

Here the better formatted yml response: 
```yml
steps:
  check-ansible-syntax:
    image: xxxxxxxxx/sebclem/woodpecker-ansible-runner
    pull: true
    settings:
      playbook: playbooks/install.yml
      galaxy_file: roles/requirements.yml
      check_syntax: true
      vault_token:
        from_secret: ansible_vault_token
    when:
      - event: \"push\"
        branch: [main, master]
      - event: [pull_request, manual, deployment]

  run-ansible-playbook:
    image: xxxxxxxxx/sebclem/woodpecker-ansible-runner
    pull: true
    settings:
      verbosity: ${verbosity=0}
      limit: ${limit}
      tags: ${tags}
      playbook: playbooks/install.yml
      galaxy_file: roles/requirements.yml
      vault_token:
        from_secret: ansible_vault_token
      private_key:
        from_secret: ansible_private_key
    when:
      environment: production
      event: deployment

when:
  - event: \"push\"
    branch: [main, master]
  - event: [pull_request, manual, deployment]
```

But since 2.4.x, I got those errors: 
![image](https://github.com/woodpecker-ci/woodpecker/assets/23737709/06efe266-774b-4b3c-b0a1-6f14ca259134)

This worked well before updating.

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"2.4.1"}
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
