### ISSUE TITLE
Woodpecker 2.4 breaks privileged steps/plugins with Kubernetes backend

### ISSUE THREAD

**Issue by everflux** [woodpecker-ci/woodpecker#3537]
This worked with WP 2.3 and Kubernetes backend:

```
  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: *repo
      tags: 8h
```

Using WP 2.4 the docker daemon does not start.

Debugging the Pod manifest I see an empty security context and the docker daemon does not start.

This works with WP 2.4.1 but is not so user friendly:

```
  publish:
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    backend_options:
      kubernetes:
        securityContext:
          privileged: true
    settings:
      repo: *repo
      tags: 8h
      daemon.debug: "true"
```

See also: https://github.com/woodpecker-ci/woodpecker/issues/3482#issuecomment-2015672185_

**Comment by zc-devs** [comment]
Comments almost useless, but...

1. I think you are talking about `2.3.x`, `2.4.x` versions.
2. One of the options should be enough. Pipeline's `privileged` takes precedence over backend's option, as I remember.
```yaml
    privileged: true
    backend_options:
      kubernetes:
        securityContext:
          privileged: true
```
