### ISSUE TITLE
Change value of "CI_COMMIT_BRANCH" for pulls to source branch

### ISSUE THREAD

**Issue by wxiaoguang** [woodpecker-ci/woodpecker#3560]
### Describe the bug

Somewhat related to " PR triggers the CI twice #2888 ".

To reproduce:

* Create a simple yaml in `main` branch:

```
steps:
  test-when:
    when: 
      branch: main
    image: ....
    commands: 
      - echo "running on CI_COMMIT_BRANCH=$CI_COMMIT_BRANCH"
```

* Create a new branch `new-branch` based on main and open a PR on Gitea
* Make some changes in `new-branch` branch
* When woodpecker receives the `pull_request_sync` event for the PR branch `new-branch`, it still runs it and considers it as `main` branch
* Expected behavior: such event should be skipped

![image](https://github.com/woodpecker-ci/woodpecker/assets/2114189/996619a0-faf2-4144-81d0-1e114559ff02)

### System Info

```shell
server & client: 2.4.1
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
