### ISSUE TITLE
Unable to start pipeline on CI agent with "complicated" label filter

### ISSUE THREAD

**Issue by rockdrilla** [woodpecker-ci/woodpecker#3571]
### Component

server, agent

### Describe the bug

I'm trying to setup CI agent with several labels but I suppose that filter accounts only last value for each label.

E.g. if `WOODPECKER_FILTER_LABELS` is set to `test_selector=a,test_selector=b` then only last part is in effect.

NB: "dedicated" CI agent (with `WOODPECKER_FILTER_LABELS=test_selector=a`) was shutdown before git push

"offending" pipeline commit: [here](https://git.krd.sh/krd/test-woodpecker-ci/commit/22ba8c11dff9d7ca4d0e515fcaafec25f7c90798)
pending pipeline: [here](https://ci.krd.sh/repos/3/pipeline/7)

simplified `.woodpecker.yml`
```yml
when:
  event: [ push, tag, manual ]

steps:

  - name: env
    image: docker.io/library/debian:bookworm-slim
    commands:
      - cat /proc/self/environ | sort -zuV | xargs -0 -r -n 1 printf '%q\n'

labels:
  test_selector: a
```

simplified `docker-compose.yml`

```yml
services:

  woodpecker:
    image: docker.io/woodpeckerci/woodpecker-server:v2.4.1
    environment:
      WOODPECKER_HOST: https://ci.krd.sh
      WOODPECKER_GITEA: "true"
      WOODPECKER_GITEA_URL: https://git.krd.sh

  woodpecker-agent-test-a:
    image: docker.io/woodpeckerci/woodpecker-agent:v2.4.1
    environment:
      WOODPECKER_SERVER: ci.krd.sh:9000
      WOODPECKER_FILTER_LABELS: "test_selector=a"

  woodpecker-agent-test-b:
    image: docker.io/woodpeckerci/woodpecker-agent:v2.4.1
    environment:
      WOODPECKER_SERVER: ci.krd.sh:9000
      WOODPECKER_FILTER_LABELS: "test_selector=b"

  woodpecker-agent-test-ab:
    image: docker.io/woodpeckerci/woodpecker-agent:v2.4.1
    environment:
      WOODPECKER_SERVER: ci.krd.sh:9000
      WOODPECKER_FILTER_LABELS: "test_selector=a,test_selector=b"
```

Probably, this issue relates to #2634 and #3483

### System Info

```shell
https://ci.krd.sh/version

{"source":"https://github.com/woodpecker-ci/woodpecker","version":"2.4.1"}
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
