### ISSUE TITLE
Persisting environment data between steps not working with debian base image

### ISSUE THREAD

**Issue by micash545** [woodpecker-ci/woodpecker#3593]
### Component

server

### Describe the bug

```
steps:
  - name: init
    image: debian
    commands:
      - echo "FOO=hello" >> envvars
      - echo "BAR=world" >> envvars

  - name: debug
    image: debian
    commands:
      - source envvars
      - echo $FOO
 ```

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"2.3.0"}
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by zc-devs** [comment]
1. Use [POSIX](https://stackoverflow.com/questions/11588583/is-the-shells-source-posix-standard) `. envvars`;
2. Or wait for #3269;
3. Or try to wrap in script:
```yaml
  - name: debug
    commands:
      - cicd/debug.sh
    image: debian
```
```sh
#!/bin/bash
source envvars
echo $FOO
```
