### ISSUE TITLE
Support for Gitlab <12.4 broken

### ISSUE THREAD

**Issue by NPCDW** [woodpecker-ci/woodpecker#3598]
### Component

server

### Describe the bug

![image](https://github.com/woodpecker-ci/woodpecker/assets/32638459/d8c2c883-5eaf-4bfd-ac30-090f33bb60de)
![image](https://github.com/woodpecker-ci/woodpecker/assets/32638459/66e10210-b5e4-452d-a0a9-f73e6f87d574)
![image](https://github.com/woodpecker-ci/woodpecker/assets/32638459/328ade80-2a66-4837-bdc6-2439f48374d1)
![image](https://github.com/woodpecker-ci/woodpecker/assets/32638459/ee16b6f6-28a3-4cb4-8ad3-5d2ca6e72c05)

Do Woodpecker CI versions v2.4.0 and v2.4.1 drop support for lower versions of GitLab?

After clicking to add a repository, the page reports an error, but no error is logged in the logs.

This configuration operates perfectly in version v2.3.0. After upgrading to version v2.4.1, issues have emerged with functionalities related to adding repositories and other repository-related functions, whereas all other functionalities continue to operate normally.

After I reverted back to version v2.3.0, everything returned to normal again.

### System Info

```json
{
    "source": "https://github.com/woodpecker-ci/woodpecker",
    "version": "2.4.1"
}
```

GitLab Community Edition 11.0.3 [aa62075](https://gitlab.com/gitlab-org/gitlab-ce/commits/aa62075)
Docker version 24.0.6, build ed223bc
Docker Compose version v2.21.0
```yaml
services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:v2.4.1
    container_name: woodpecker-server
    ports:
      - 55555:8000
      - 55559:9000
    volumes:
      - ./data:/var/lib/woodpecker/
    environment:
      - TZ=Asia/Shanghai
      - WOODPECKER_HOST=http://10.10.10.2:55555
      - WOODPECKER_ADMIN=***,***
      - WOODPECKER_GITLAB=true
      - WOODPECKER_GITLAB_URL=
      - WOODPECKER_GITLAB_CLIENT=
      - WOODPECKER_GITLAB_SECRET=
      - WOODPECKER_AGENT_SECRET=
      - WOODPECKER_AUTHENTICATE_PUBLIC_REPOS=true
      - WOODPECKER_LOG_LEVEL=trace
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
