### ISSUE TITLE
woodpecker cli parse matrix fail

### ISSUE THREAD

**Issue by micash545** [woodpecker-ci/woodpecker#3673]
### Component

cli

### Describe the bug

Woodpecker cli throws parse matrix when its not defined:
```
❯ ./woodpecker-cli exec ./test.yaml
12:50PM FTL error running cli error="parse matrix fail"
❯ cat --plain ./test.yaml
when:
  - branch: *

steps:
  build:
    image: localregistry/nodejs:latest
    pull: true
    commands:
      - pnpm i --frozen-lockfile
      - pnpm build
  deploy:
    image: localregistry/actions/rsync:latest
    pull: true
    directory: ./build
    settings:
      port:
        from_secret: ssh_port
      privatekey:
        from_secret: ssh_key
      host_key:
        from_secret: ssh_host_key
      src: .
      dest:
        from_secret: ssh_host
    when:
      event: push
```

### System Info

```shell
woodpecker-cli version 2.4.1
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
