### ISSUE TITLE
Bogusly worded lint: "Please set an event filter for all steps or the whole workflow on all items of the when block"

### ISSUE THREAD

**Issue by neuschaefer** [woodpecker-ci/woodpecker#3773]
### Component

web-ui

### Describe the bug

I have a simple workflow in which I did not specify any `when` block. Woodpecker produces the following lint, which mentions a `when` block:

![when](https://github.com/woodpecker-ci/woodpecker/assets/1021512/61253bf1-58c7-4bd6-94f5-50c299174b46)

### Steps to reproduce

```yml
steps:
  build:
    image: debian:12
    commands:
      - apt-get update && apt-get install -y git cmake ninja-build g++ gcc-arm-none-eabi python3
      - cmake -B build -G Ninja -DPICO_SDK_PATH=pico-sdk
      - ninja -C build
```

### Expected behavior

- The lint does not mention "the when block" when there is none
- The lint (or another one) may offer appropriate guidance for adding a good when block, but that's a different problem then what the lint message currently implies

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"2.5.0"}
```

### Additional context

I reworded this issue a few times, because my original goal was to clone a repo non-recursively, and it wasn't entirely clear to me from the documentation, how to do this.

I found https://github.com/woodpecker-ci/woodpecker/issues/3607, which discusses a similar issue, and I'm not sure if the `next` version of Woodpecker might perhaps fix what I described. I have not installed woodpecker-next because that would be another project of multiple hours.

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
