### ISSUE TITLE
There is no line breaks in the Step logs

### ISSUE THREAD

**Issue by zc-devs** [woodpecker-ci/woodpecker#3790]
### Component

server, web-ui

### Describe the bug

Downloaded or copy-pasted logs  do not have line breaks, appears as one line.

### Steps to reproduce

1. Install Woodpecker `2.6.0`.
2. Run pipeline
```yaml
skip_clone: true
steps:
  server:
    image: alpine
    commands:
      - echo Hello
      - echo world
```
2. See logs in UI
![Screenshot 2024-06-14 200009](https://github.com/woodpecker-ci/woodpecker/assets/127358482/21ddb602-a28d-44ab-a39e-6807e713f710)
3. Download logs
[usr-wp-test-324-server.log](https://github.com/user-attachments/files/15841307/usr-wp-test-324-server.log)
4. Copy logs from UI and paste in some text editor
5. Check, that downloaded logs and copy-pasted one are one-line text
```
+ echo HelloHello+ echo worldworld
```

### Expected behavior

1. Install Woodpecker `2.5.0`.
2. Run pipeline
```yaml
skip_clone: true
steps:
  server:
    image: alpine
    commands:
      - echo Hello
      - echo world
```
2. See logs in UI
![Screenshot 2024-06-14 195449](https://github.com/woodpecker-ci/woodpecker/assets/127358482/67052ea1-6df7-42b2-9643-71cae2a0bb67)
3. Download logs
[usr-wp-test-323-server.log](https://github.com/user-attachments/files/15841256/usr-wp-test-323-server.log)
4. Copy logs from UI and paste in some text editor
5. Check, that downloaded logs and copy-pasted one are multiple lines
```
+ echo Hello
Hello
+ echo world
world
```

### System Info

```shell
Woodpecker 2.6.0, Kubernetes.
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
