### ISSUE TITLE
Workflow-level backend options

### ISSUE THREAD

**Issue by zc-devs** [woodpecker-ci/woodpecker#3802]
### Clear and concise description of the problem

Currently, we have plenty of backend options. Consider [Kubernete](https://woodpecker-ci.org/docs/administration/backends/kubernetes#job-specific-configuration), for example.
While we can set them per-step:
```yaml
steps:
  test:
    image: golang
    commands:
      - go test
    backend_options:
      kubernetes:
        nodeSelector:
          kubernetes.io/arch: amd64
        securityContext:
          runAsNonRoot: true
  build:
    image: golang
    commands:
      - go build
    backend_options:
      kubernetes:
        nodeSelector:
          kubernetes.io/arch: amd64
        securityContext:
          runAsNonRoot: true
  package:
    image: kaniko
    commands:
      - executor
    backend_options:
      kubernetes:
        nodeSelector:
          kubernetes.io/arch: amd64
        securityContext:
          runAsNonRoot: true
```

### Suggested solution

it would be nice if we could set them per-workflow and override/refine in steps:
```yaml
backend_options:
  kubernetes:
    nodeSelector:
      kubernetes.io/arch: amd64
    securityContext:
      runAsNonRoot: true

steps:
  test:
    image: golang
    commands:
      - go test
  build:
    image: golang
    commands:
      - go build
    backend_options:
      kubernetes:
        nodeSelector:
          beta.kubernetes.io/instance-type: p3.8xlarge
  package:
    image: buildx
    commands:
      - build
```

### Additional context

It would allow to implement backend-specific custom volumes per workflow, for example.

### Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by zc-devs** [comment]
In context of duplication, either #2294 or [Advanced YAML syntax](https://woodpecker-ci.org/docs/usage/advanced-usage#advanced-yaml-syntax) (I've updated Alternatives) would work, I think.

But I thought, about some per-pipeline functionality and came up with
> It would allow to implement backend-specific custom volumes per workflow, for example.

Nor #2294, nor YAML substitution won't resolve this case.

See also #1594, #1595.

**Comment by zc-devs** [comment]
> some per-pipeline functionality

My bad. I meant file - workflow. For now volume is created per workflow anyway.

> pipeline level

This is tempting :) I think I would want it, but let's eat elephant by pieces - start from workflow and see how it is going.

**Comment by zc-devs** [comment]
> Why not? You can define the backend options as default in the workflow and it is added to all steps with https://github.com/woodpecker-ci/woodpecker/discussions/2294?

Perhaps, I'm missing something. Consider an example
```yaml
default:
  volumes:
    - storageClassName: local-ssd # K3s Local path provisioner
      resources:
        requests:
          storage: 512Mi
      mount: /mnt/local
    - storageClassName: nfs-hdd
      resources:
        requests:
          storage: 16Gi
      mount: /mnt/nfs

steps:
  one:
    commands:
      - echo "Hello" > /mnt/local/hello.txt
      - echo "world" > /mnt/nfs/world.txt
  two:
    commands:
      - cat /mnt/local/hello.txt
      - cat /mnt/nfs/world.txt
```
Would step `two` display
```
Hello
world
```
and two volumes be created (not 4)?

If yes, then #2294 completely suits.
