### ISSUE TITLE
Skip steps who depend on an failed step witch ignores failure

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#3823]
```yaml
when:
  - event: push
    branch: main

steps:
  failing-step:
    image: alpine
    commands:
      - printenv
      - exit 1
    failure: ignore
  should-not-start:
    image: alpine
    commands:
      - printenv
      - exit 1
    depends_on: 
      - failing-step
```

we should add a new failure mode: `skip_dependencies` or so ...

so we can make checks and skip things based on that ...

blocked by: #3009

**Comment by anbraten** [comment]
I don't get your request yet. Isn't your pasted config working already?

Are you talking about a "soft" depends_on that is optional if the previous step was skipped:

```yml

steps:
  should-even-start-if-prev-was-skipped:
    image: alpine
    commands:
      - printenv
      - exit 1
    depends_on: 
      - name: skipped-step
        optional: true
```

**Comment by 6543** [comment]
huh ... well yes you solution looks better!

it would be:

```yaml
when:
  - event: push
    branch: main

steps:
  failing-step:
    image: alpine
    commands:
      - printenv
      - exit 1
    failure: ignore
  should-not-start:
    image: alpine
    commands:
      - printenv
      - exit 1
    depends_on: 
      - name: failing-step
        optional: false
```
where if not set optional would be true by default (to behave backwards comp.)
