### ISSUE TITLE
`depends_on` seems to be broken on workflow level

### ISSUE THREAD

**Issue by terminalnode** [woodpecker-ci/woodpecker#3858]
### Component

agent

### Describe the bug

After updating to 2.6.0, it seems that my `Auth server tests.yml`, which has a `depends_on: [ 'Build Auth' ]` on top, is no longer awaiting `Build Auth.yml`. We have multiple workflows with workflow-level dependencies that are all experiencing similar problems.

### Steps to reproduce

1. Create a workflow file `Build Auth.yml`, give it a single step that takes a few seconds.
2. Create another workflow file `Auth server tests.yml`
3. Add `depends_on: [ 'Build Auth' ]` to the top of `Auth server tests.yml`

### Expected behavior

The `Auth server tests.yml` should wait for `Build Auth` to finish before running.

### System Info

```shell
2.6.0
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by terminalnode** [comment]
This is one example:

`Build base.yml` is executed before anything, as it should.
```yml
when:
  - ref: 'refs/heads/main'
    event: [ 'push', 'pull_request' ]
  - event: [ 'pull_request' ]

steps:
  - name: 'Build base'
    image: docker
    environment: # redacted
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    commands:
      - ./ci/docker_drone ${CI_COMMIT_SHA} stage1
      - ./ci/docker_drone ${CI_COMMIT_SHA} stage2
```

`Build Auth.yml`
```yml
depends_on: [ 'Build base' ]
when:
  - ref: 'refs/heads/main'
    event: [ 'push', 'pull_request' ]
  - event: [ 'pull_request' ]

steps:
  - name: 'Build Auth'
    image: docker
    environment: # redacted
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    commands:
      - ./ci/docker_drone ${CI_COMMIT_SHA} auth-build
```

`Auth server tests.yml`
```yml
depends_on: [ 'Build Auth' ]
when:
  - ref: 'refs/heads/main'
    event: [ 'push', 'pull_request' ]
  - event: [ 'pull_request' ]

variables:
  &when_paths [ { path: { include: ['auth-server/src/**', 'gradle/libs*.versions.toml'] } } ]

services:
  - name: viamysql
    when: *when_paths
    image: mysql
    environment: # redacted

steps:
  - name: 'Auth server tests'
    image: auth-build:${CI_COMMIT_SHA}
    environment: # redacted
    when: *when_paths
    commands:
      - ./ci/run_auth_server_tests
```
The most frustrating part about this is that it seems inconsistent, sometimet it works sometimes it doesn't.

The `docker_drone` script is just a very simple helper to build a certain stage of a docker file with the tag target:commit_sha.
```sh
#!/usr/bin/env sh
sha="$1"
target="$2"
[ -z "$sha" ] && echo 'ERROR: Missing first param (SHA)' && exit 0
[ -z "$target" ] && echo 'ERROR: Missing second param (target name)' && exit 0
docker build --target "$target" -t "$target:$sha" .
```
