### ISSUE TITLE
Clone step checkouts default branch on Pull Request event (Bitbucket)

### ISSUE THREAD

**Issue by j04n-f** [woodpecker-ci/woodpecker#3932]
### Component

server

## Goal
Run formatters and tests after pushing a new commit to a pull request.

## Forge
Bitbucket Cloud

## Issue
The clone step checkouts the default branch and uses the default branch workflow. It should checkout the pull request  branch and use the pull request workflow.

## Workflow
```yaml
when:
  event: pull_request

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      partial: false

steps:
  echo:
    image: ubuntu
    commands:
      - echo "Hello World"
    when:
      event: pull_request
```

## Logs

```shell
+ git init -b master 0s
+ Initialized empty Git repository in /woodpecker/src/**
+ git config --global --replace-all safe.directory /woodpecker/src/**
+ git remote add origin https://bitbucket.org/**
+ git fetch --no-tags --depth=1 --filter=tree:0 origin +a6b5f1dfe5ac:
fatal: couldn't find remote ref a6b5f1dfe5ac
retry in 5s
+ git fetch --no-tags --depth=1 --filter=tree:0 origin +a6b5f1dfe5ac:5s
fatal: couldn't find remote ref a6b5f1dfe5ac
retry in 5s
exit status 128
```

## Additional Information
- We enabled the Bitbucket webhook `pullrequest:updated`, it was not enabled by default. Probably because it is not selected by default when Woodpecker creates the webhook: https://github.com/woodpecker-ci/woodpecker/blob/d6e3ebf051a978702b46f67327ac7b44c761978e/server/forge/bitbucket/bitbucket.go#L316

### Steps to reproduce

1. Create a Bitbucket Cloud repository
2. Update the Bitbucket webhook: `pullrequest:updated`
3. Push a workflow to the main branch
```yaml
when:
  event: push

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      partial: false

steps:
  echo:
    image: ubuntu
    commands:
      - echo "Hello World"
    when:
      event: push
```
4. Create a branch containing a change on the workflow 
```yaml
when:
  event: pull_request

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      partial: false

steps:
  echo:
    image: ubuntu
    commands:
      - echo "Hello World"
    when:
      event: pull_request
```
5. Push the branch changes and open a pull request to the default branch

### Expected behavior

The clone step should checkout the Pull Request workflow and code instead of checking out the default branch.

### System Info

```shell
Version 2.6
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
