### ISSUE TITLE
K8S Backend - Ability to add a side container to a step (pod)

### ISSUE THREAD

**Issue by eliasscosta** [woodpecker-ci/woodpecker#3977]
### Clear and concise description of the problem

Sometimes we have a test step where they need to run inside a docker image (dind), because a few tests are written with the TestContainer library. 

To achieve it, we need to configure one step like this: 

```yaml
  allTests:
    image: docker:24.0.9
    commands:
      - apk add openjdk17
      - dockerd-entrypoint.sh --registry-mirror=http://myprivate-mirror.ior:5000 1> /dev/null 2> /dev/null &
      - ./gradlew test myTEST
    when:
      event: push
```

This example is in the easy mode, but sometimes we need to install more than one jdk or the dind image doesn't have the library in the OS packages.

### Suggested solution

The solution was to add into the `backend_options` a way to create a side container with the main step container.

```yaml
  allTests:
    image: openjdk17
    commands:
      - ./gradlew test myTEST
    when:
      event: push
    backend_options:
      kubernetes:
        container: 
          - image: docker:dind
            env: []
```

Then both containers can start and we can access the docker in the local host and execute the tests with the TestContainers.

### Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.
