### ISSUE TITLE
CI_WORKSPACE variable doesn't work with string substitution in entrypoint

### ISSUE THREAD

**Issue by june128** [woodpecker-ci/woodpecker#3982]
### Component

server, agent

### Describe the bug

Using the `CI_WORKSPACE` variable using string substitution in an entrypoint doesn't work. Other variables like e.g. `CI` do work.

### Steps to reproduce

1. Define a workflow containing the following steps:
   ```yaml
   - name: test-1
     image: debian
     entrypoint:
       - /bin/bash
       - -c
       - echo hello${CI}
   - name: test-2
     image: debian
     entrypoint:
       - /bin/bash
       - -c
       - echo hello${CI_WORKSPACE}
   ```
2. Run the workflow
3. Observe the output in the Web interface

### Expected behavior

The output being:
- for `test-1`: `hellowoodpecker`
- for `test-2`: `hello<FULLWORKSPACEPATH>`

What's actually being output:
- for `test-1`: `hellowoodpecker`
- for `test-2`: `hello`

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"2.7.0"}
```

### Additional context

Woodpecker running on NixOS. Config available [here](https://git.hamburg.ccc.de/CCCHH/nix-infra/src/branch/main/config/hosts/woodpecker).

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
