### ISSUE TITLE
Custom environment variables don't work with string substitution 

### ISSUE THREAD

**Issue by june128** [woodpecker-ci/woodpecker#3983]
### Component

server, agent

### Describe the bug

Setting custom environment variables using the `environment` key can't be used via string substitution.

### Steps to reproduce

1. Define a workflow containing the following step:
   ```yaml
   - name: test
     image: debian
     environment:
       MY_COOL_TEST_VAR: test
     commands:
       - echo "$CI $MY_COOL_TEST_VAR ${CI} ${MY_COOL_TEST_VAR}"
   ```
2. Run the workflow
3. Observe the output in the Web interface

### Expected behavior

The output being:
```
+ echo "$CI $MY_COOL_TEST_VAR test woodpecker "
woodpecker test test woodpecker 
```
What's actually being output:
```
+ echo "$CI $MY_COOL_TEST_VAR woodpecker "
woodpecker test woodpecker 
```

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"2.7.0"}
```

### Additional context

Woodpecker running on NixOS. Config available [here](https://git.hamburg.ccc.de/CCCHH/nix-infra/src/branch/main/config/hosts/woodpecker).

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by zc-devs** [comment]
[Escape it](https://woodpecker-ci.org/docs/usage/environment):
```yaml
skip_clone: true

steps:
  echo-envs:
    image: alpine
    environment:
      MY_COOL_TEST_VAR: test
    commands:
      - echo "Workspace is $$CI_WORKSPACE"
      - echo "My cool variable is $$MY_COOL_TEST_VAR"
```
```
+ echo "Workspace is $CI_WORKSPACE"
Workspace is /woodpecker/src/gitea.example.com/wp/test
+ echo "My cool variable is $MY_COOL_TEST_VAR"
My cool variable is test
```
or [use scripts](https://github.com/woodpecker-ci/woodpecker/discussions/3973#discussioncomment-10147415).
