### ISSUE TITLE
matrix with combinations AND includes

### ISSUE THREAD

**Issue by lo48576** [woodpecker-ci/woodpecker#3992]
### Clear and concise description of the problem

I want to describe `matrix` both with the combinations AND the list in the `include` field at the same time.

My main reasons to such selective `include` along with the combination is to avoid bloat of combinations.
See the example below.

### Suggested solution

Suggested solution is, the combinations and `include` are both used to generate workflows.

Example:

```yaml
matrix:
  TOOLCHAIN:
    - stable
    - beta
  PROFILE:
    - debug
    - release
  FEATURES:
    - NONE
    - foo
    - bar
    - foo+bar
  include:
    - TOOLCHAIN: oldest-supported # Versions before stable, but still supported officially.
      PROFILE: debug
      FEATURES: foo+bar # test with all major features enabled at once
    - TOOLCHAIN: nightly
      PROFILE: debug
      FEATURES: NONE # No features
    - TOOLCHAIN: nightly
      PROFILE: debug
      FEATURES: foo+bar # test with all major features at once
    - TOOLCHAIN: nightly
      PROFILE: debug
      FEATURES: foo+bar+experimental-baz # ...and also experimental feature!

steps:
  # long long steps
```

In this case, there will be 2×2×4 (=16) workflows to be generated from combinations, and additionally, plus 4 workflows to be generated from `include` (so total is 20).

### Alternative

* Write all "resolved" combinations in `include` manually.
    + This makes it hard to maintain the variables.
* Write combinations without `include`, and accept extra (unnecessary) workflows.
    + This may make tests too long. In the above example, simply putting `nightly` to `TOOLCHAIN:` will create 8 more workflows, and I need more for `TOOLCHAIN: oldest-supported` and `experimental-baz` cases!
    + This may exceed the limit of combinations ([25](https://github.com/woodpecker-ci/woodpecker/blob/ef8e03396e0da0f72212ee834f77f381744d4646/pipeline/frontend/yaml/matrix/matrix.go#L27) or something? In my test environment 27 was the maximum but I don't know why this was not 25...)
* Split the workflow YAML file into two, a combinations version and `include` version.
    + This forces the maintainer to duplicate all parts other than `matrix` (such as `clone`, `variables`, `when`, `steps`, etc.) so makes maintenance error-prone.

### Additional context

I'm not familiar with go but this part seems to be responsible:

https://github.com/woodpecker-ci/woodpecker/blob/ef8e03396e0da0f72212ee834f77f381744d4646/pipeline/frontend/yaml/matrix/matrix.go#L46-L53

Parsing both (of course ignoring `include` as a tag) and merging `calc(matrix)` and `axis` may produce the expected result?

---

BTW, the document should clarify this is not currently supported.

### Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.
