### ISSUE TITLE
Inefficient handling of verbose log output

### ISSUE THREAD

**Issue by hg** [woodpecker-ci/woodpecker#3999]
### Component

server, agent

### Describe the bug

Hello. I recently migrated some CI jobs from Drone and noticed their running time increasing from 4 seconds to about two minutes.

The reason seems to be rather inefficient handling of long job output. Moving it from PostgreSQL into JSON files (`WOODPECKER_LOG_STORE`) improved running time by ~10%, but it's still much slower than it should be.

The agent is running on an adjacent VM, there's pretty much no network latency between the server and the agent.

Disabling detailed logging reduced their running time to the same few seconds. The actual jobs run `rsync --itemize-changes` on large PHP projects (~15-20k files/ea, one line of output for each file) or running tests with very detailed logging, but it's easier to reproduce with a synthetic benchmark:

```yaml
# woodpecker
when:
  event: push

steps:
  log:
    image: alpine:3.20
    commands:
      - seq 0 50000
```

```yaml
# drone
kind: pipeline
type: docker
name: test

trigger:
  event: push

steps:
  - name: log
    image: alpine:3.20
    commands:
      - seq 0 50000
```

On my CI server, Drone runs this in less than two seconds, Woodpecker finishes in just under *five minutes*. Both are using the same VM and the same instance of Docker.

As Woodpecker is much nicer overall and is actually FOSS, I have no desire to go back. Any way we can fix this?

I don't write Go daily, so instead of profiling properly I decided to simply [check] if the bottleneck is in the storage procedure. While it helped with a synthetic benchmark:

```
BenchmarkLogAppend-16  269067   4411 ns/op   // before
BenchmarkLogAppend-16  2715338  442.3 ns/op  // after
```

the more realistic test described previously was sped up by only a few seconds.

Any thoughts? Maybe I'm doing something very wrong and missed some knob in the docs?

There was a similar problem in #2064 and it's marked as "fixed".

[check]: https://github.com/hg/woodpecker/commit/d256f2ab752978340dd1145081c4ee13c23ab9f1

---

server:

```yaml
  woodpecker:
    image: woodpeckerci/woodpecker-server
    restart: always
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_HOST=https://woodpecker.example
      - WOODPECKER_GITEA=true
      - WOODPECKER_GITEA_URL=https://gitea.example
      - WOODPECKER_GITEA_CLIENT=xxx
      - WOODPECKER_GITEA_SECRET=xxx
      - WOODPECKER_AGENT_SECRET=xxx
      - WOODPECKER_DATABASE_DRIVER=postgres
      - WOODPECKER_DATABASE_DATASOURCE=postgres://woodpecker:xxx@db:5432/woodpecker?sslmode=disable
      - WOODPECKER_LOG_STORE=file
      - WOODPECKER_LOG_STORE_FILE_PATH=/var/log/ci-logs
      - WOODPECKER_ADMIN=xxx
      - WOODPECKER_GRPC_SECRET=xxx
    networks:
      - woodpecker
      - db
    volumes:
      - ./data/woodpecker/log:/var/log/ci-logs
      - ./data/woodpecker/data:/var/lib/woodpecker
    ports:
      - 10.24.0.1:9000:9000
```

agent:

```bash
docker run --detach \
  --restart=always \
  --volume=/var/run/docker.sock:/var/run/docker.sock \
  --env=WOODPECKER_SERVER=10.24.0.1:9000 \
  --env=WOODPECKER_AGENT_SECRET=xxx \
  --name=woodpecker \
  --volume=woodpecker-agent-config:/etc/woodpecker \
  woodpeckerci/woodpecker-agent
```

### Steps to reproduce

See repro above.

### Expected behavior

Simple jobs with tens of thousands of lines of output should finish in 1-2 seconds.

### System Info

```shell
- 2.7.0, the latest `next`, and built from trunk
- both agent and server are running under Docker 20.10.24
- Debian 12 amd64
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by zc-devs** [comment]
Confirm on `next-2d039f85cb` in Kubernetes.

Pipeline:
```yaml
skip_clone: true
steps:
  log:
    image: alpine:3.20
    commands:
      - seq 0 50000
```

Pod success in few seconds and I can see end of logs in OpenLens.
Then it waits for termination about 6 minutes while Agent uploads the logs to Server. At this time logs window in UI is empty.
Then a pipeline finishes, a Pod deletes and the logs shows in the UI.


[agent.log](https://github.com/user-attachments/files/16474880/agent.log)
[pod.yaml](https://github.com/user-attachments/files/16474882/pod.yaml.txt)
[ui.jpg](https://github.com/user-attachments/assets/5c5b936c-dffa-4daf-9db2-d7ac12c58c2c)
