### ISSUE TITLE
GitHub backend: unknown error/401 bad credentials after some time

### ISSUE THREAD

**Issue by achristianson** [woodpecker-ci/woodpecker#4079]
### Component

server, web-ui

### Describe the bug

Woodpecker with GitHub works fine after fresh login, but if I go away for some time (e.g. overnight), I start getting `Unknown Error` on the UI on every page load, and sometimes "pipeline not found" errors.

## Workaround

I can work around the issue reliably by logging out and logging back into woodpecker using my GH account.

## Incompetent user acknowledgement

I acknowledge this may have something to do with a dumb configuration/mistake on my end, but if it is, I don't know what I did wrong.

### Steps to reproduce

Deploy woodpecker server with following config:

```
          server:
            env:
              WOODPECKER_HOST: "https://{{ woodpecker.host }}"
              WOODPECKER_OPEN: "false"
              WOODPECKER_ADMIN: "{{ woodpecker.admin }}"
              WOODPECKER_GITHUB: "true"
              WOODPECKER_GITHUB_CLIENT: "{{ woodpecker.github.client }}"
              WOODPECKER_GITHUB_SECRET: "{{ woodpecker.github.secret }}"
              WOODPECKER_AGENT_SECRET: "{{ woodpecker.agent.secret }}"
```

Log in to woodpecker, do successful builds, **go away for a day**.

### Expected behavior

I expect that woodpecker stays authenticated with GH, or at least has better UI indication/workflow for refreshing tokens.

### System Info

```shell
name: woodpecker
        chart_ref: woodpecker/woodpecker
```

Deployed woodpecker using latest helm chart.

# Version 2.7.0
```


### Additional context

_No response_

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
