### ISSUE TITLE
Kubernetes backend silently discards backend_options errors

### ISSUE THREAD

**Issue by meln5674** [woodpecker-ci/woodpecker#4106]
### Component

agent

### Describe the bug

At this line https://github.com/woodpecker-ci/woodpecker/blob/v2.7.1/pipeline/backend/kubernetes/kubernetes.go#L229 there is no `return err`, meaning that any errors from parsing backend_options will be silently discarded.

### Steps to reproduce

The following pipeline will demonstrate the issue

```yaml
when:
  - event: push
  - event: manual

steps:
  - name: test
    image: alpine:3.13
    commands:
      - echo "Testing"
    backend_options:
      kubernetes:
        resources:
          requests:
            cpu: 1 # This should be a string, so it won't be set
```

### Expected behavior

The error should be propagated back to the user, and the step should not run. Ideally such an error should be caught during initial pipeline validation.

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-3ce20912cd"}
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
