### ISSUE TITLE
Starting a simple stack result in "forge not configured"

### ISSUE THREAD

**Issue by rossm-mf** [woodpecker-ci/woodpecker#4191]
### Component

server

### Describe the bug

starting a simple stack gets me. I cant find any info about forge relevant to my error.

```
woodpecker-server  | {"level":"info","time":"2024-10-05T13:55:30Z","message":"log level: info"}
woodpecker-server  | {"level":"error","error":"can't setup globals: could not setup service manager: forge not configured","time":"2024-10-05T13:55:30Z","message":"error running server"}
dependency failed to start: container woodpecker-server exited (0)
```

### Steps to reproduce

docker-compose up of this

```
  woodpecker-server:
    container_name: woodpecker-server
    image: woodpeckerci/woodpecker-server:latest
    ports:
      - 8333:8000
    volumes:
      - woodpecker-config:/var/lib/woodpecker/
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_ADMIN=aname
      - WOODPECKER_HOST=http://internal_url:8000
      - WOODPECKER_AGENT_SECRET=SECRET
  woodpecker-agent:
    container_name: woodpecker-agent
    image: woodpeckerci/woodpecker-agent:latest
    depends_on:
      woodpecker-server:
        condition: service_healthy
    volumes:
      - woodpecker-agent-config:/etc/woodpecker
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WOODPECKER_SERVER=woodpecker-server:9000
      - WOODPECKER_AGENT_SECRET=SECRET
```

### Expected behavior

I would image that is a simple docker compose to start but I get an error 

### System Info

```shell
> ...:~/stack$ docker version
Client: Docker Engine - Community
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:41:00 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       41ca978
  Built:            Fri Sep 20 11:41:00 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.22
  GitCommit:        7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc:
  Version:          1.1.14
  GitCommit:        v1.1.14-0-g2c9f560
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

> ...:~/stack$ docker compose version
Docker Compose version v2.29.7
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
