### ISSUE TITLE
Bitbucket cloud does not load any repositories

### ISSUE THREAD

**Issue by ydemartino** [woodpecker-ci/woodpecker#4243]
### Component

server

### Describe the bug

I have setup bitbucket cloud and followed the instructions in the doc.
I am able to login using bitbucket OAuth 2, although the redirect takes around 30 seconds.

When I get back to the dashboard, my profile is correctly loaded but the repo list is empty.

### Steps to reproduce

1 - Setup woodpecker using docker-compose:
```
services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:latest-alpine
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - woodpecker-server-data:/var/lib/woodpecker/
    env_file: .env
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_ADMIN=*redacted*
      - WOODPECKER_ORGS=*redacted*
      - WOODPECKER_HOST=${WOODPECKER_HOST}
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
      - WOODPECKER_BITBUCKET=true
      - WOODPECKER_BITBUCKET_CLIENT=*redacted*
      - WOODPECKER_BITBUCKET_SECRET=*redacted*
      - WOODPECKER_AUTHENTICATE_PUBLIC_REPOS=true
      - WOODPECKER_LOG_LEVEL=trace
      - WOODPECKER_DEBUG_PRETTY=true
      - WOODPECKER_FORGE_TIMEOUT=30s
      - WOODPECKER_FORGE_RETRY=3

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:latest-alpine
    command: agent
    restart: unless-stopped
    depends_on:
      - woodpecker-server
    volumes:
      - woodpecker-agent-config:/etc/woodpecker
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: .env
    environment:
      - WOODPECKER_SERVER=woodpecker-server:9000
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}

volumes:
  woodpecker-server-data:
  woodpecker-agent-config:
```
2 - Login with your bitbucket account
3 - Get redirected to the repo

### Expected behavior

The page should list all the bitbucket repositories available. 

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"2.7.1"}
```

### Additional context

I'm using docker compose on a Mac. 
I saw this issue: https://github.com/woodpecker-ci/woodpecker/issues/143 but it seems it happens when trying to activate a repository.
I have setup a publicly accessible instance just to be sure.

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
