### ISSUE TITLE
Environment variable names are silently changed to snake_case

### ISSUE THREAD

**Issue by fernandrone** [woodpecker-ci/woodpecker#4265]
### Component

server

### Describe the bug

One of our pipelines runs an elasticsearch container a service. For some reason elasticsearch uses "dot case format", as can be seen in their official [docker-compose file](https://github.com/elastic/elasticsearch/blob/8.15/docs/reference/setup/install/docker/docker-compose.yml#L76-L92): 

```yaml
    environment:
      - node.name=es01
      - cluster.name=${CLUSTER_NAME}
      - cluster.initial_master_nodes=es01,es02,es03
```

This is how the service is configured in woodpecker:

```yaml
services:
  elastic:
    image: public.ecr.aws/elastic/elasticsearch:7.17.7
    environment:
      - node.name=elasticsearch
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200/tcp
      - 9300/tcp
```

However since we updated Woodpecker from 2.3.0 to 2.7.0 the variables started to be converted from "dot case" to "snake case". If we describe the pods in Kubernetes we can see:

```
    Environment:
       node_name:         elasticsearch
```

This is causing the pipeline to fail, as we can't properly set the cluster's node name and the other steps executing in this pipeline won't be able to find the elasticsearch service in the cluster.

The issue seems to be related to this function: https://github.com/qwerty287/woodpecker/blob/main/pipeline/frontend/yaml/compiler/settings/params.go#L47

```
// sanitizeParamKey formats the environment variable key.
func sanitizeParamKey(prefix string, upper bool, k string) string {
	r := strings.ReplaceAll(strings.ReplaceAll(k, ".", "_"), "-", "_")
	if upper {
		r = strings.ToUpper(r)
	}
	return prefix + r
}
```

I'm not 100% sure why it worked in 2.3.0 and stopped working after the update but I saw https://github.com/woodpecker-ci/woodpecker/issues/3515 which seems related. 

I think that https://github.com/woodpecker-ci/woodpecker/pull/3406 which also caused that issue and was introduced in 2.4.0 might have caused this issue too. And then its fix https://github.com/woodpecker-ci/woodpecker/pull/3516 only addressed the _uppercase_ element, but not the dot case to snake case conversion.

### Steps to reproduce

1. Install Woodpecker 2.7.0+ (probably reproducible starting at 2.4.0)
2. Create a pipeline using

```yaml
services:
  elastic:
    image: public.ecr.aws/elastic/elasticsearch:7.17.7
    environment:
      - node.name=elasticsearch
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    ports:
      - 9200/tcp
      - 9300/tcp
```

3. See that env vars are replaced to snake_case

### System Info

```shell
Woodpecker 2.7.0+, Kubernetes installation
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
