### ISSUE TITLE
step `directory:` is ignored

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#4314]
after updating woodpecker to the latest image

```
  build-web:
    image: *node_image
    directory: web/
    commands:
      - corepack enable
      - pnpm install --frozen-lockfile
      - pnpm build
```

the directory is ignored

I suspect it is because of #4151  ... future investigation needed :/

cc @pat-s
