### ISSUE TITLE
when.status:failure doesn't work

### ISSUE THREAD

**Issue by zc-devs** [woodpecker-ci/woodpecker#4355]
### Component

server

### Describe the bug

Step with `when.status: [failure]` doesn't run on failed pipeline, instead runs step with `when.status: [success]`.

### Steps to reproduce

1. Woodpecker + some Forge
2. Make pipeline

```yaml
# build.yaml
skip_clone: true
steps:
  build:
    image: alpine
    commands:
      - echo 'Building the app'
      - exit 1 # 0 - success, 1 - fail
```
```yaml
# notifications.yaml
skip_clone: true
depends_on: [build]
runs_on: [success, failure]
steps:
  fail-notification:
    when:
      - status: [failure]
    image: alpine
    commands:
      - echo 'Build failed'
  success-notification:
    when:
      - status: [success]
    image: alpine
    commands:
      - echo 'Build succeed'
```
3. Run manually and get wrong step execution
![Screenshot 2024-11-11 1](https://github.com/user-attachments/assets/77cad464-54ff-4aef-996a-a18d6ff5ad33)

### Expected behavior

1. `success-notification` step runs
2. `fail-notification` skips

### System Info

```shell
WP `next-f87e80381b`, `2.7.1`, Gitea, Postgres 16
```

### Additional context

https://github.com/woodpecker-ci/woodpecker/issues/4337#issuecomment-2468498847

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
