### ISSUE TITLE
Documentation: Kubernetes mounts

### ISSUE THREAD

**Issue by greenaar** [woodpecker-ci/woodpecker#4369]
### Clear and concise description of the problem

https://woodpecker-ci.org/docs/next/administration/backends/kubernetes#volumes

Make reference to 
```
    settings:
      mount:
        - "woodpecker-cache"
```

Which is no longer supported when used with things like `command:`

### Suggested solution

Removing that part, and including a sample PVC like 

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: woodpecker-cache
spec:
  storageClassName: "longhorn"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
```

Might go well to enhancing this part of the documentation.

### Alternative

Alternatively, just removing that settings part and providing a link to the kubernetes docs  (https://kubernetes.io/docs/concepts/storage/persistent-volumes/) might serve as well.

### Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.
