### ISSUE TITLE
Steps with the same name

### ISSUE THREAD

**Issue by zc-devs** [woodpecker-ci/woodpecker#4385]
### Component

other

### Describe the bug

Trying to use steps with the same name, pipeline fails or works wrong.

https://github.com/woodpecker-ci/woodpecker/pull/3411#issuecomment-2194567897:
> be aware that steps now can have the same name

### Steps to reproduce

1. Make pipeline
```yaml
skip_clone: true
steps:
  notification:
    depends_on:
      - build
    image: alpine
    commands:
      - echo 'Alright'
  build:
    image: alpine
    commands:
      - echo 'Build'
  build:
    image: alpine
    commands:
      - echo 'Test'
  package:
    image: alpine
    commands:
      - echo 'Package'
```
2. Get error in editor
![Screenshot 2024-11-16 1](https://github.com/user-attachments/assets/5a7a174d-134f-439b-a831-571ab1fda98c)
3. Run pipeline
4. Get error in UI
![Screenshot 2024-11-16 2](https://github.com/user-attachments/assets/420f965c-6216-4e87-88fa-ef2ed36c4f2e)

### Expected behavior

- pipeline fails with error like `step names must be unique`
- or pipeline runs two steps with the same name

### System Info

```shell
Woodpecker `next-75017ac7ca`, Gitea `1.22.3`, Postgres `16`, Kubernetes `v1.30.6+k3s1`
```

### Additional context

https://github.com/woodpecker-ci/woodpecker/pull/3411#issuecomment-2194567897
https://github.com/woodpecker-ci/woodpecker/pull/3411#discussion_r1844941371

I'll attach the logs

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
