### ISSUE TITLE
Last visited repos header shows repos which never have been visited

### ISSUE THREAD

**Issue by zc-devs** [woodpecker-ci/woodpecker#4426]
### Component

web-ui

### Describe the bug

I see repos, that I have never visited in the `last visited repos` header.

### Steps to reproduce

1. Woodpecker + Gitea
2. Create an or in Gitea
3. Create 2 users and put them in the org
4. Under User 1 create some repos in Gitea
5. Under User 1 enable the repos in Woodpecker
6. Under User 2 open repositories and see newly created repos in the `last visited repos` header.

### Expected behavior

Under User 2 the `last visited repos` header is empty.

### System Info

```shell
WP `next-350082cd19`, Gitea `1.22.3`, Postgres `16`, Kubernetes `v1.30.6+k3s1`
```

### Additional context

https://github.com/woodpecker-ci/woodpecker/pull/4386#issuecomment-2490781907

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by zc-devs** [comment]
I thought it was

> If you never visited a repo it shows the first 4 repos from the "general" list (probably sorted by last pipeline time)

but it is even worse.

**Comment by zc-devs** [comment]
> So this is actually not per-user, but per-browser.
> And to be honestly, your issue here seems very special. Who usually logs in with more than one account?

1. Prepare domains 
```
192.168.1.11	wp.local
192.168.1.11	gitea.local
```
2. Install Gitea
```yaml
services:
  gitea:
    image: docker.io/gitea/gitea:1.22.6
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - gtwp
    ports:
      - "3000:3000"
      - "222:22"
networks:
  gtwp:
```
3. Open Gitea in _Firefox_  in Incognito mode
4. Under administrator (`minad`) create app
![Screenshot 2024-12-21 211422](https://github.com/user-attachments/assets/39fa1a18-5765-49c9-baba-a5dc5293da9f)
5. Create user
6. Create org
7. Put user in the org with admin access
![Screenshot 2024-12-21 212844](https://github.com/user-attachments/assets/22014954-fa81-4cfc-a149-107190928cbe)
8. Create repos
![Screenshot 2024-12-21 213000](https://github.com/user-attachments/assets/d436a2e4-f48d-4adb-9956-fed18c786975)
9. Deploy Woodpecker
```yaml
  woodpecker:
    image: woodpeckerci/woodpecker-server:v3.0.0-rc1-alpine
    volumes:
      - ./woodpecker:/var/lib/woodpecker/
    networks:
      - gtwp
    ports:
      - 8000:8000
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_ADMIN=minad
      - WOODPECKER_HOST=http://wp.local:8000
      - WOODPECKER_GITEA=true
      - WOODPECKER_GITEA_URL=http://gitea.local:3000
      - WOODPECKER_GITEA_CLIENT=5803cc8d-a1c4-40f3-a8a3-ef2fe14af9d9
      - WOODPECKER_GITEA_SECRET=gto_47lv2s253i4sxujw4cnljcpe75oyzhvqs3xfwnddyjwtmgwlntka
      - WOODPECKER_LOG_LEVEL=trace

```
10. Open Woodpecker in another _Firefox_ tab
11. Login under administrator (`minad`) and activate repos
![Screenshot 2024-12-21 213109](https://github.com/user-attachments/assets/80b8d229-0179-4958-8d10-c0122f66f286)
12. Open _Chrome_ in Incognito mode
13. Login under user (`harry`) and see all (three) repos in the `last visited` block.
![Screenshot 2024-12-21 213242](https://github.com/user-attachments/assets/cfa0bf20-90f9-45be-8e17-4a0a64457693)

I didn't open a repository at all. I just logged in from _another browser_ under _another user_.
>Last visited repos header shows repos which never have been visited
