### ISSUE TITLE
Need both environment and settings for plugin appleboy/dron-ssh, but this is deprecated

### ISSUE THREAD

**Issue by smainz** [woodpecker-ci/woodpecker#4430]
### Component

server

### Describe the bug

I am using this drone plugin: https://github.com/appleboy/drone-ssh

And I need additional env vars set in my script (and the optional env var for deployment `$TAG` will override the constant `dev`) 

```
  - name: Deploy to Server
    image: appleboy/drone-ssh
    environment:
      TAG: ${TAG=dev}
    settings:
      proxy_host: jumphost.xxx.xxxxxx.xx
      proxy_username:
        from_secret: SSH_USER
      proxy_key:
        from_secret: SSH_KEY
      host: "10.1.0.5"
      username:
        from_secret: SSH_USER
      key:
        from_secret: SSH_KEY
      envs:
        - TAG
      script:
        - cd /srv/docker.nbr
        - echo "TAG=$${TAG}" > .env
        - docker-compose pull
        - docker-compose down
        - docker-compose up -d
  ``` 

How is this supposed in the futire as I get the linter warning: **Should not configure both environment and settings**

The docs of this plugin explicitly state this kind of usage. Is there differnet woodpecker plugin for the same use?

### Steps to reproduce

Should be obvious

### System Info

```shell
Woodpecker 2.7.2 from docker image
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by pat-s** [comment]
It is a Drone plugin, it won't necessarily follow WP conventions. I think as this point in time, many old drone plugins will stop to work with WP due to the recent `secrets:`/`environment:` changes.

We should highlight that most Drone plugins are not compatible anymore.

**Comment by smainz** [comment]
If this is the informed decision to give up compatibility to drone plugins this should be stated on the website.

At the moment the plugins doc page (https://woodpecker-ci.org/docs/usage/plugins/overview) points to this impressive list: https://plugins.drone.io

For this particular plugin, I need environment variable string operations on an arbitrary list of vars.

```
envs:
  - TAG
```

passes the plugins env var `TAG` to the remote host before executing the script.
The plugins env var  `TAG` is evaluated in the agent based on a variable passed to a `deplyoment` event

So in the end I will need something like:

```
- name: Deploy to Server
    image: <modified appleboy/drone-ssh plugin>
    settings:
      ...
      username:
        from_secret: SSH_USER
      key:
        from_secret: SSH_KEY
      envs:
        - TAG=${TAG=dev}
        - OTHER_VAR:
          from_secret: SOME_SECRET        
      script:
        - <commands executed on the remot host, using ${TAG} and ${OTHER_VAR}>
```
      
Can the parser handle this syntax and what would the plugin get?
