### ISSUE TITLE
dagger exampoe

### ISSUE THREAD

**Issue by mouuii** [woodpecker-ci/woodpecker#4518]
### Clear and concise description of the problem

can we  add a flagger example ? https://dagger.io/

### Suggested solution

add a yaml example

### Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by anbraten** [comment]
That would be interesting to get to work with woodpecker. Only requirement would probably be to set [privileged mode](https://woodpecker-ci.org/docs/usage/workflow-syntax#privileged-mode) for your repo.

It could look like this:

```yml
steps:
  - name: dagger
    image: docker:latest
    environment:
      DOCKER_HOST: tcp://dind:2376
    commands:
      - apk add curl
      - curl -fsSL https://dl.dagger.io/dagger/install.sh | BIN_DIR=/usr/local/bin sh

services:
  - name: dind
    image: docker:dind
    commands: dockerd-entrypoint.sh --storage-driver=vfs --tls=false
    privileged: true
```
