### ISSUE TITLE
Agent keeps restarting due to permission issue.

### ISSUE THREAD

**Issue by rubenelshof** [woodpecker-ci/woodpecker#4681]
### Component

agent

### Describe the bug

The Woodpecker agent keeps restarting because of a permissions issue with the Docker socket.
As I have updated about 15 minutes ago I suspect this is caused by #4617.

My docker compose config.
```
name: dev_woodpecker-agent

services:
  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:next
    container_name: dev_woodpecker-agent
    restart: always
    command: agent
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WOODPECKER_SERVER=<domain>
      - WOODPECKER_GRPC_SECURE=true
      - WOODPECKER_AGENT_SECRET=<secret>
      - WOODPECKER_AGENT_BACKEND=docker
      - WOODPECKER_FILTER_LABELS=hostname=<hostname>
      - WOODPECKER_HOSTNAME=<hostname>

networks:
  web:
    external: true
```

### Steps to reproduce

.

### System Info

```shell
Woodpecker version: 20323a8302
```

### Additional context

```
{"level":"error","error":"permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get \"http://%2Fvar%2Frun%2Fdocker.sock/v1.47/info\": dial unix /var/run/docker.sock: connect: permission denied","time":"2025-01-08T09:22:29Z","message":"cannot load backend engine"}
{"level":"info","time":"2025-01-08T09:22:29Z","message":"shutdown of whole agent"}
{"level":"fatal","error":"permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get \"http://%2Fvar%2Frun%2Fdocker.sock/v1.47/info\": dial unix /var/run/docker.sock: connect: permission denied","time":"2025-01-08T09:22:29Z","message":"error running agent"}
{"level":"info","time":"2025-01-08T09:22:55Z","message":"log level: info"}
{"level":"error","error":"permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get \"http://%2Fvar%2Frun%2Fdocker.sock/v1.47/info\": dial unix /var/run/docker.sock: connect: permission denied","time":"2025-01-08T09:22:55Z","message":"cannot load backend engine"}
{"level":"info","time":"2025-01-08T09:22:55Z","message":"shutdown of whole agent"}
{"level":"fatal","error":"permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get \"http://%2Fvar%2Frun%2Fdocker.sock/v1.47/info\": dial unix /var/run/docker.sock: connect: permission denied","time":"2025-01-08T09:22:55Z","message":"error running agent"}
{"level":"info","time":"2025-01-08T09:23:47Z","message":"log level: info"}
{"level":"error","error":"permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get \"http://%2Fvar%2Frun%2Fdocker.sock/v1.47/info\": dial unix /var/run/docker.sock: connect: permission denied","time":"2025-01-08T09:23:47Z","message":"cannot load backend engine"}
{"level":"info","time":"2025-01-08T09:23:47Z","message":"shutdown of whole agent"}
{"level":"fatal","error":"permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get \"http://%2Fvar%2Frun%2Fdocker.sock/v1.47/info\": dial unix /var/run/docker.sock: connect: permission denied","time":"2025-01-08T09:23:47Z","message":"error running agent"}
{"level":"info","time":"2025-01-08T09:24:47Z","message":"log level: info"}
{"level":"error","error":"permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get \"http://%2Fvar%2Frun%2Fdocker.sock/v1.47/info\": dial unix /var/run/docker.sock: connect: permission denied","time":"2025-01-08T09:24:47Z","message":"cannot load backend engine"}
{"level":"info","time":"2025-01-08T09:24:47Z","message":"shutdown of whole agent"}
{"level":"fatal","error":"permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get \"http://%2Fvar%2Frun%2Fdocker.sock/v1.47/info\": dial unix /var/run/docker.sock: connect: permission denied","time":"2025-01-08T09:24:47Z","message":"error running agent"}
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
