### ISSUE TITLE
Configuring the server via WOODPECKER_DATABASE_DATASOURCE_FILE leads to an error

### ISSUE THREAD

**Issue by danial23** [woodpecker-ci/woodpecker#4728]
### Component

server

### Describe the bug

I have a woodpecker container that I would like to connect to a postgres instance. I tried to use the environment variable `WOODPECKER_DATABASE_DATASOURCE_FILE` to set up the connection, but the server won't start:
```json
{"level":"error","error":"can't setup store: could not open datastore: parse \"postgres://woodpecker:[REDACTED]@postgres:5432/woodpecker?sslmode=disable\\n\": net/url: invalid control character in URL","time":"2025-01-17T05:16:47Z","message":"error running server"}
```
At first glance the problem seems to be an extra newline at the end of the database URL but it's not present in the file containing the URL.

### Steps to reproduce

1. Create a file named `database_url` containing a database URL
2. Run Woodpecker with `docker compose up` using a `compose.yml` similar to this:
```yaml
services:
  postgres:
    image: postgres:16
    container_name: postgres

  woodpecker-server:
    image: woodpeckerci/woodpecker-server:v2.8.3
    container_name: woodpecker-server
    secrets:
      - database_url
    environment:
      WOODPECKER_OPEN: "false"
      WOODPECKER_ADMIN: [REDACTED]
      WOODPECKER_HOST: [REDACTED]
      WOODPECKER_WEBHOOK_HOST: http://woodpecker-server:8000
      WOODPECKER_DATABASE_DRIVER: postgres
      WOODPECKER_DATABASE_DATASOURCE_FILE: /run/secrets/database_url
      WOODPECKER_FORGEJO: "true"
      WOODPECKER_FORGEJO_URL: [REDACTED]
      WOODPECKER_FORGEJO_CLIENT: [REDACTED]
      WOODPECKER_FORGEJO_SECRET: [REDACTED]
      WOODPECKER_AGENT_SECRET: [REDACTED]

secrets:
  database_url:
    file: ./database_url
```

### System Info

```shell
Woodpecker v2.8.3
Docker version 27.5.0, build a187fa5
```

### Validations

- [x] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [x] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [x] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
