### ISSUE TITLE
Set volumes in services the service get error

### ISSUE THREAD

**Issue by klinux** [woodpecker-ci/woodpecker#4759]
When I set the volumes in services, we are receiving this error in pipeline:
**name is not a valid kubernetes DNS name**

Example:

```
services:
  docker
    image: docker:dind # use 'docker:<major-version>-dind' or similar in production
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: /dind-certs
    volumes:
      - /opt/woodpeckerci/dind-certs:/dind-certs
    ports:
      - 2376
```
    
Any volumes configured, this error happens.

There some configuration that we missing here?
The repository is marked as Trusted.

Backend: Kubernetes
Woodpecker: 2.8.3 we do not test with 3.x
