### ISSUE TITLE
Adding Repository Fails

### ISSUE THREAD

**Issue by nyaaaaaaatalie** [woodpecker-ci/woodpecker#4782]
### Component

server

### Describe the bug

I am using the Docker container for Woodpecker connected to Forgejo. The Forgejo server uses an external OIDC IDP for authentication. When I add a repo, sometimes I will get the message "An unknown error has occured". In the Docker logs, I see the attached log messages and traceback. Interestingly. it seems that I can add projects that are under my user namespace; but not ones that are under an organization (despite me owning the org in Forgejo).

### Steps to reproduce

1. Start container with compose config:

```
  ci-srv:
    image: woodpeckerci/woodpecker-server:latest
    volumes:
      - ./data/ci-srv-data:/var/lib/woodpecker/
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_HOST=[redacted]
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
      - WOODPECKER_FORGEJO=true
      - WOODPECKER_FORGEJO_URL=[redacted]
      - WOODPECKER_FORGEJO_CLIENT=${WOODPECKER_FORGEJO_CLIENT}
      - WOODPECKER_FORGEJO_SECRET=${WOODPECKER_FORGEJO_SECRET}
    networks:
      - http_proxy
      - git
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_http_proxy"
      - "traefik.http.routers.ci.rule=Host(`[redacted]`)"
      - "traefik.http.routers.ci.entrypoints=websecure"
      - "traefik.http.routers.ci.tls=true"
      - "traefik.http.routers.ci.tls.certresolver=letsencrypt"
      - "traefik.http.services.ci.loadbalancer.server.port=8000"

```

2. Browse to Forgejo
3. Log in via Forgejo (and thus via my IDP)
4. Click Add Repository
5. Click Enable on any repository that is not under my user namespace.

### Expected behavior

When I click "Enable" on a repository I expect it to enable with success.

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"2.8.3"}
```

### Additional context

```
2025/01/26 22:54:56 [Recovery] 2025/01/26 - 22:54:56 panic recovered:
runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:261 (0x458ff7)
/usr/local/go/src/runtime/signal_unix.go:881 (0x458fc5)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/repo.go:149 (0xddd5dd)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:185 (0xaeeb4a)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/session/user.go:118 (0xe44f86)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:185 (0xe3d3e2)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/token/token.go:40 (0xe3d3d0)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:185 (0xaeeb4a)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/session/user.go:73 (0xe4796e)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:185 (0xaeeb4a)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/store.go:28 (0x1093dee)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:185 (0xaeeb4a)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/logger.go:37 (0x1093ea5)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:185 (0xe3d1b7)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/header/header.go:38 (0xe3d0e4)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:185 (0xe3d038)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/header/header.go:30 (0xe3d026)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:185 (0xe441e7)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/router.go:44 (0xe441d5)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:185 (0xafbfd9)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/recovery.go:102 (0xafbfc7)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:185 (0xafad71)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/gin.go:633 (0xafa7e0)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/gin.go:589 (0xafa311)
/usr/local/go/src/net/http/server.go:3142 (0x89d6ad)
/usr/local/go/src/net/http/server.go:2044 (0x898987)
/usr/local/go/src/runtime/asm_amd64.s:1695 (0x47b540)
```

### Validations

- [x] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [x] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [x] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
