### ISSUE TITLE
Unable to open Database file on fresh install

### ISSUE THREAD

**Issue by Lite5h4dow** [woodpecker-ci/woodpecker#4786]
### Component

server

### Describe the bug

error:
```json
{"level":"warn","time":"2025-01-28T14:51:39Z","message":"no sqlite3 file found, will create one at '/var/lib/woodpecker/woodpecker.sqlite'"}
{"level":"error","error":"can't setup store: could not migrate datastore: unable to open database file: no such file or directory","time":"2025-01-28T14:51:39Z","message":"error running server"}
```

it appears to try and create a sqlite file, and either fails to create it, or tries to access it before it actually creates it. ive tried both with and without persistent volumes, cant seem to get to the bottom of it

### Steps to reproduce

install woodpecker-ci with latest helm chart from `https://woodpecker-ci.org`.

server config is as follows:
```yaml
server:
  enabled: true

  statefulSet:
    replicaCount: 1
    revisionHistoryLimit: 5

  updateStrategy:
    type: RollingUpdate

  image:
    registry: docker.io
    repository: woodpeckerci/woodpecker-server
    pullPolicy: IfNotPresent
    # tag: 'latest'

  env:
    WOODPECKER_ADMIN: -redacted-
    WOODPECKER_HOST: -redacted-
    WOODPECKER_AGENT_SECRET: 'woodpecker-agent'
    WOODPECKER_BACKEND_K8S_NAMESPACE: 'git'

  extraSecretNamesForEnvFrom:
    - woodpecker-secret

  secrets:
    - name: woodpecker-secret

  persistentVolume:
    # enabled: true
    enabled: false
    # mountPath: '/var/lib/woodpecker'
    storageClass: "longhorn"

  serviceAccount:
    create: false
    annotations: {}
    name: ''
```

### Expected behavior

woodpecker server should create database and run.

### System Info

```shell
Attempting to run V3. woodpecker helm chart version 3.
```

### Additional context

i am running in Kubernetes.

seems to be the same issue as https://github.com/woodpecker-ci/woodpecker/issues/4731#issue-2796652250 
EXCEPT I'm not using the same storage system, there are no permission restrictions on the volume and they didn't state how they solved it.

### Validations

- [x] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [x] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [x] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by elAgala** [comment]
Is there any workaround for this? Going back to version 2.x.x is working for me.

**Comment by Lite5h4dow** [comment]
I have figured out a workaround (and its probably ill advised, but it got it working for me), setting the securityContext to root:
```yaml
securityContext:
  runAsGroup: 0
  runAsUser: 0
```

**Comment by jphetphoumy** [comment]
Hi @elAgala , I have found a workaround when using docker compose

When using volume with something like : 

```yaml
services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:v3.0.1
    restart: always
    ports:
      - 8000:8000
    volumes:
      - woodpecker-server-data:/var/lib/woodpecker/

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:v3.0.1
    command: agent
    restart: always
    depends_on:
      - woodpecker-server
    volumes:
      - woodpecker-agent-config:/etc/woodpecker
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  woodpecker-server-data:
  woodpecker-agent-config:
```

You can spin up the stack with

```bash
docker compose create
chown 1000:1000 /var/lib/docker/volumes/woodpecker-woodpecker-server-data
docker compose start
```

And you will have a working woodpecker stack

If you use host path instead of docker volume, do the same but change the path to your host path

If you migrate from **2.8.3** to **3.0.1**, you will need to run `chown 1000:1000` on the volume used by the server container

Hope this help !
