### ISSUE TITLE
Linter warning on using k8s secret

### ISSUE THREAD

**Issue by praveen-livspace** [woodpecker-ci/woodpecker#4787]
### Component

server

### Describe the bug

The pipeline linter currently produces a warning if a k8s secret is mounted on a step pod.
This is the pipeline def:

```
labels:
  backend: kubernetes
  platform: linux/amd64
when:
  event:
  - push
  - pull_request
  - tag
  - manual
  branch:
  - master
  - feature/*
steps:
- name: Build Container
  image: livcr.io/docker/woodpeckerci/plugin-kaniko:1.2.1
  settings:
    auto_tag: false
    dockerfile: ./Dockerfile
    enable_cache: false
    tags: master-${platform##linux/}-b916333f
  backend_options:
    kubernetes:
      secrets:
      - name: aws-secret
        key: credentials
        target:
          file: /root/.aws/credentials
matrix:
  platform:
  - linux/amd64
  - linux/arm64
```
Output of linter
```
woodpecker-cli lint wp-pipeline.yaml
⚠️  wp-pipeline.yaml has 3 warnings:
   ⚠️  steps	Must validate one and only one schema (oneOf)
   ⚠️  steps.0	Must validate at least one schema (anyOf)
   ⚠️  steps.0.backend_options.kubernetes.secrets.0.target	Must validate one and only one schema (oneOf)
```

### Steps to reproduce

See description

### Expected behavior

The linter should not generate warnings

### System Info

```shell
❯ woodpecker-cli --version
woodpecker-cli version 3.0.1
```

### Validations

- [x] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [x] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [x] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
