### ISSUE TITLE
`CI_PIPELINE_*` environment variables retrun empty at `agent 3.0.1`, especially `CI_PIPELINE_STATUS`

### ISSUE THREAD

**Issue by sinlov** [woodpecker-ci/woodpecker#4788]
### Component

agent, server

### Describe the bug

At [woodpekcer 2.8.x Built-in environment variables](https://woodpecker-ci.org/docs/usage/environment#built-in-environment-variables)

`CI_PIPELINE_STATUS` will return pipeline status (success, failure).

While testing the plugin to send notifications after pipeline failure I wanted to use CI_STEP_STATUS but it doesn't return a value.

```yaml
labels:
  backend: docker
  platform: linux/amd64

steps:
  build:
    image: alpine:3.17
    pull: false
    commands:
      - echo "CI                            $${CI}"
      - echo "CI_SYSTEM_NAME                $${CI_SYSTEM_NAME}"
      - echo "CI_SYSTEM_VERSION             $${CI_SYSTEM_VERSION}"
      - echo "CI_PIPELINE_CREATED           $${CI_PIPELINE_CREATED}"
      - echo "CI_PIPELINE_DEPLOY_TARGET     $${CI_PIPELINE_DEPLOY_TARGET}"
      - echo "CI_PIPELINE_DEPLOY_TASK       $${CI_PIPELINE_DEPLOY_TASK}"
      - echo "CI_PIPELINE_EVENT             $${CI_PIPELINE_EVENT}"
      - echo "CI_PIPELINE_FILES             $${CI_PIPELINE_FILES}"
      - echo "CI_PIPELINE_FINISHED          $${CI_PIPELINE_FINISHED}"
      - echo "CI_PIPELINE_FORGE_URL         $${CI_PIPELINE_FORGE_URL}"
      - echo "CI_PIPELINE_NUMBER            $${CI_PIPELINE_NUMBER}"
      - echo "CI_PIPELINE_PARENT            $${CI_PIPELINE_PARENT}"
      - echo "CI_PIPELINE_STARTED           $${CI_PIPELINE_STARTED}"
      - echo "CI_PIPELINE_STATUS            $${CI_PIPELINE_STATUS}"
      - echo "CI_PIPELINE_URL               $${CI_PIPELINE_URL}"
```

error environment variables
- CI_PIPELINE_FILES
- CI_PIPELINE_FINISHED
- CI_PIPELINE_STATUS

### Steps to reproduce

1. install server version `3.0.1`, and link agent `3.0.1`
2. run pipeline
3. out log

```
CI                                  woodpecker
CI_SYSTEM_NAME                      woodpecker
CI_SYSTEM_VERSION                   3.0.1
CI_PIPELINE_CREATED                 1737915912
CI_PIPELINE_DEPLOY_TARGET
CI_PIPELINE_DEPLOY_TASK
CI_PIPELINE_EVENT                   push
CI_PIPELINE_FILES                   []
CI_PIPELINE_FINISHED
CI_PIPELINE_FORGE_URL               https://...
CI_PIPELINE_NUMBER                  231
CI_PIPELINE_PARENT                  0
CI_PIPELINE_STARTED                 1737915919
CI_PIPELINE_STATUS
CI_PIPELINE_URL                     https://.....
```

### Expected behavior

old pipleine plugins use env `CI_PIPELINE_STATUS` to send or checked, if remove this env will let pipeline broken

```
CI                                  woodpecker
CI_SYSTEM_NAME                      woodpecker
CI_SYSTEM_VERSION                   3.0.1
CI_PIPELINE_CREATED                 1737915912
CI_PIPELINE_DEPLOY_TARGET
CI_PIPELINE_DEPLOY_TASK
CI_PIPELINE_EVENT                   push
CI_PIPELINE_FILES                   ["....","..."]
CI_PIPELINE_FINISHED                 1737915912
CI_PIPELINE_FORGE_URL               https://...
CI_PIPELINE_NUMBER                  231
CI_PIPELINE_PARENT                  0
CI_PIPELINE_STARTED                 1737915919
CI_PIPELINE_STATUS                  success
CI_PIPELINE_URL                     https://.....
```

### System Info

```shell
woodpekce server version `3.0.1`
woodpekce agent version `3.0.1`
```

### Additional context

run at  server version `2.8.2 `, and link agent `2.8.2 `

```
CI                                  woodpecker
CI_SYSTEM_NAME                      woodpecker
CI_SYSTEM_VERSION                   2.8.2
CI_PIPELINE_CREATED                 1737928891
CI_PIPELINE_DEPLOY_TARGET
CI_PIPELINE_DEPLOY_TASK
CI_PIPELINE_EVENT                   pull_request_closed
CI_PIPELINE_FILES                   ["....","..."]
CI_PIPELINE_FINISHED                1737928906
CI_PIPELINE_FORGE_URL               https://...
CI_PIPELINE_NUMBER                  197
CI_PIPELINE_PARENT                  0
CI_PIPELINE_STARTED                 1737928904
CI_PIPELINE_STATUS                  success
CI_PIPELINE_URL                     https://.....
```

### Validations

- [x] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [x] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [x] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
