### ISSUE TITLE
SQLite database keep getting stuck

### ISSUE THREAD

**Issue by Bigaston** [woodpecker-ci/woodpecker#4811]
### Component

server

### Describe the bug

Hello!
I'm trying to migrate from 2.8.3 to 3.0.1 and I can't. I'm always stuck at the server booting time. When I use my old data, the server says me he can't write to a read only database, and when I use and empty folder I got this error

Do you have a solution? It's a bit strange...

![Image](https://github.com/user-attachments/assets/85659f14-306f-4466-9e72-b8b2475c1e3d)

### Steps to reproduce

1. Copy this Docker-compose file
2. Launch it

```YML
services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:v3.0.1
    ports:
      - 666:8000
    volumes:
      - woodpecker-server-data:/var/lib/woodpecker/
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_HOST=https://ci.example.com
      - WOODPECKER_AGENT_SECRET=yey

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:v3.0.1
    command: agent
    restart: always
    depends_on:
      - woodpecker-server
    volumes:
      - woodpecker-agent-config:/etc/woodpecker
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WOODPECKER_SERVER=woodpecker-server:9000
      - WOODPECKER_AGENT_SECRET=yey

volumes:
  woodpecker-server-data:
  woodpecker-agent-config:
```

### System Info

```shell
Run on a debian 12 machine, with Docker
```

### Validations

- [x] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [x] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [x] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
