### ISSUE TITLE
When executing a pipeline manually I get: Missing required param "pipelineId"

### ISSUE THREAD

**Issue by BowlOfSoup** [woodpecker-ci/woodpecker#4847]
### Component

server, web-ui

### Describe the bug

When executing a pipeline manually for a repository I get the error in my console: Missing required param "pipelineId"

### Steps to reproduce

1. Connect a repository
2. Have a .woodpecker.yml file with the following content in the repo

```
when:
  - event: push
    branch: master

steps:
  - name: build
    image: docker:dind
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      IMAGE_NAME: mygitea.somdomain.nl/${CI_REPO_OWNER}/${CI_REPO_NAME}
    commands:
      - docker login mygitea.somdomain.nl -u $GITEA_USER -p $GITEA_TOKEN
      - docker build -t $IMAGE_NAME:$CI_COMMIT_SHA -f Dockerfile .
      - docker tag $IMAGE_NAME:$CI_COMMIT_SHA $IMAGE_NAME:latest
      - docker push $IMAGE_NAME:$CI_COMMIT_SHA
      - docker push $IMAGE_NAME:latest

```

3. Manually trigger the pipeline by navigating to the repo, click "Run pipeline"
4. Selecting branch "master"
5. Click "Run pipeline" 

Expected:
- Pipeline starts

Actual:
- Spinner keeps spinning, described error is in console

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"3.1.0"}
```

### Additional context

![Image](https://github.com/user-attachments/assets/aa69b5c7-ebea-46b1-9b6e-edf37ea15896)

![Image](https://github.com/user-attachments/assets/9a43d442-f627-48a7-9753-08449e70179e)

### Validations

- [x] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [x] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [x] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/versions]
