### ISSUE TITLE
Woodpecker in docker (compose) - after restart pipelines don't work anymore - could not load config from forge

### ISSUE THREAD

**Issue by BowlOfSoup** [woodpecker-ci/woodpecker#4850]
I have Woodpecker running in a Docker compose setup, together with Gitea. 

1. The server starts
2. The agent starts
3. I can login into the Woodpecker GUI and authenticate via Gitea
4. Webhook to my Gitea repo works
5. Pipeline is triggered via a push in Gitea.

But, after a down and up of my compose setup, Woodpecker stops working correctly when I refresh the page.

- A manual webhook trigger via Gitea triggers a pipeline but this errors out directly with this error: `could not load config from forge: %!w()`
- When navigating through Woodpecker I get errors like:

![Image](https://github.com/user-attachments/assets/c3bd29fe-9fc8-4e86-88d9-5506432104da)

Looks to me like the authentication back to Gitea is not working anymore. 

The server log for Woodpecker says: 
`025-02-14T21:07:38+01:00 ERR refresh oauth token of user 'itsme' failed | error=oauth2: "unauthorized_client" "unable to parse refresh token"`

Hereby my compose setup: 

```
  gitea:
    image: gitea/gitea:1.23-rootless
    container_name: gitea
    restart: unless-stopped
    environment:
      - GITEA__database__DB_TYPE=sqlite3
      - GITEA__server__ROOT_URL=https://my_gitea_domain_here
      - GITEA__server__HTTP_PORT=3000
      - GITEA__server__PROTOCOL=http
    volumes:
      - /mnt/storage/gitea/git:/var/lib/gitea/git # Store repositories on HDD
      - /mnt/storage/gitea/packages:/var/lib/gitea/packages # Store packages/images on HDD
  
      - ./volumes/gitea/data:/var/lib/gitea/data # Stores data, including database
      - ./volumes/gitea/ssh:/var/lib/gitea/ssh # Stores ssh data
      - ./volumes/gitea/config:/etc/gitea # Stores config

      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - 'my_network'
    ports:
      - "3000:3000"
      - "60022:22" # SSH for Git operations
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`my_gitea_domain_here`)"
      - "traefik.http.routers.gitea.entrypoints=websecure"
      - "traefik.http.routers.gitea.tls.certresolver=letsencrypt"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"

  woodpecker-server:
    image: woodpeckerci/woodpecker-server:v3-alpine
    container_name: woodpecker-server
    restart: unless-stopped
    depends_on:
      - gitea
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_HOST=https://my_woodpecker_domain_here
      - WOODPECKER_GITEA=true
      - WOODPECKER_GITEA_URL=https://my_gitea_domain_here
      - WOODPECKER_GITEA_CLIENT=${WOODPECKER_GITEA_CLIENT}
      - WOODPECKER_GITEA_SECRET=${WOODPECKER_GITEA_SECRET}
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
      - WOODPECKER_ADMIN=${WOODPECKER_GITEA_ADMIN_USER}
      - WOODPECKER_MAX_WORKFLOWS=5
    volumes:
      - ./volumes/woodpecker:/var/lib/woodpecker
      - /mnt/storage/woodpecker/artifacts:/artifacts
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - 'my_network'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.woodpecker.rule=Host(`my_woodpecker_domain_here`)"
      - "traefik.http.routers.woodpecker.entrypoints=websecure"
      - "traefik.http.routers.woodpecker.tls.certresolver=letsencrypt"
      - "traefik.http.services.woodpecker.loadbalancer.server.port=8000"
    ports:
      - "8000:8000"

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:v3-alpine
    container_name: woodpecker-agent
    restart: unless-stopped
    depends_on:
      - woodpecker-server
    environment:
      - WOODPECKER_SERVER=woodpecker-server:9000
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
      - WOODPECKER_MAX_PROCS=2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - 'my_network'
```
