### ISSUE TITLE
forgejo: fatal: could not read Username for '***': No such device or address

### ISSUE THREAD

**Issue by patrickuhlmann** [woodpecker-ci/woodpecker#4876]
### Component

server

### Describe the bug

My setup is a bunch of docker compose stacks:
- forgejo
- woodpecker server + 1 agent
- a renovate job

Under normal operation everything works fine. However when I execute renovate it sometimes create a large number of pull requests. This leads to a queue of jobs as they are executed one by one. After a while every job fails cloning with this error message:
```
+ git config --global http.sslCAInfo /opt/***.crt
+ git init --object-format sha1 -b renovate/docker-28.x
Initialized empty Git repository in /woodpecker/src/forgejo.***.ch/***/***/.git/
+ git config --global --replace-all safe.directory /woodpecker/src/forgejo.***.ch/***/***
+ git remote add origin https://forgejo.***.ch/***/***.git
+ git fetch --no-tags --depth=1 --filter=tree:0 origin +***:
fatal: could not read Username for 'https://forgejo.***.ch': No such device or address
exit status 128
```
And in forgejo I see the following error
```

2025/02/21 23:56:18 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/v1/repos/***/***/statuses/*** for 172.16.1.1:0, 201 Created in 14.3ms @ repo/status.go:21(repo.NewCommitStatus)
2025/02/21 23:56:22 ...eb/routing/logger.go:102:func1() [I] router: completed GET /***/***.git/info/refs?service=git-upload-pack for 172.16.1.1:0, 401 Unauthorized in 0.1ms @ web/githttp.go:15(web.requireSignIn)
2025/02/21 23:56:22 ...rvices/auth/basic.go:131:Verify() [E] UserSignIn: user's password is invalid [uid: 1, name: patrick]
2025/02/21 23:56:22 routers/web/web.go:124:func7() [E] Failed to verify user: user's password is invalid [uid: 1, name: patrick]
```

It seems that it has issues after a while to authenticate to forgejo. Also I don't know why it is doing a get for git-upload-pack. When I execute just one build or a bunch of builds it is never a problem. Also if I wait until all builds are failed and when I click "Restart" for one build, it will run without any problem.

Anyone has an idea what might happen? Could there be a problem with the authentication against forgejo when the build is delayed/queued for a while (e. g. already authenticating before it is queued, credential invalid when it is actually executed half an hour later)

### Steps to reproduce

Unsure if it can be reproduced everywhere but for me:
* 1. Run Renovate which a bunch of repositories in need of dependency updates
* 2. Observe woodpecker as 100 builds are queued. It will run the first 10 or so successfully and then fail every build

### Expected behavior

It should successfully run all builds, even if it takes 10 hours until the last one is executed.

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"3.1.0"}
```

### Additional context

Here an example of a build file:
```
clone:
  git:
    image: woodpeckerci/plugin-git:latest@sha256:b6d40eaba0ee4274d11c96cc0e053557e6cb024fa56d26c25419c2b4dd6fbfe8
    environment:
      PLUGIN_LFS: false
      PLUGIN_CUSTOM_SSL_PATH: /opt/***.crt
    volumes:
      - /data/CA/***.crt:/opt/***.crt

steps:
  lint:
    image: docker:27.3.1-cli@sha256:328eb399a065780c2cebe9224de003aa14084cf69efae882ac27430f921819b7
    commands:
    - docker compose config --quiet
    when:
      event: [ push, pull_request, cron, manual ]
  notify:
    image: deblan/woodpecker-email@sha256:7111a0ef37708e50e4d1340579abfc0f4424584869f852f7541b67a9e5521c2f
    settings:
      dsn:
        from_secret: EMAIL_DSN
      from:
        address:
          from_secret: EMAIL_FROM_ADDRESS
      recipients:
        from_secret: EMAIL_RECIPIENTS
      recipients_only: true
    when:
      status: [ failure ]
      event: [ push, pull_request, cron, manual ]
```
I also enabled all the Trusted options

![Image](https://github.com/user-attachments/assets/52ba2bc6-c779-4e2a-8b10-bd93f2402849)

### Validations

- [x] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [x] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [x] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/versions]
