### ISSUE TITLE
Console parsing input text for colored html link

### ISSUE THREAD

**Issue by cduchenoy** [woodpecker-ci/woodpecker#4907]
### Component

web-ui

### Describe the bug

Text parsing of an http link printed in color on the output console adds a span tag to the HTML

![Image](https://github.com/user-attachments/assets/116b6da7-8f0b-4c88-bedc-d001c8e06785)

### Steps to reproduce

- Example pipeline

```yaml
  - name: test
    image: alpine:3.21
    commands:
      - NOCOLOR='\\033[0m'
      - BLUE='\\033[0;34m'
      - echo -e "$${BLUE}https://docs.astral.sh/ruff/rules/pytest-fixture-positional-args/$${NOCOLOR}"
      - echo "https://docs.astral.sh/ruff/rules/pytest-fixture-positional-args"
```

### System Info

```shell
{
source: "https://github.com/woodpecker-ci/woodpecker",
version: "3.0.1"
}
```

### Validations

- [x] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [x] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [x] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/versions]
