### ISSUE TITLE
Cannot enable new repos after upgrading from v3.1.0 to v3.2.0. Duplicate entry for key 'UQE_orgs_name'

### ISSUE THREAD

**Issue by DHandspikerWade** [woodpecker-ci/woodpecker#4918]
### Component

server

### Describe the bug

After upgrading to 3.2.0, I am no longer able to enable new repos in the server dashboard. Attempting results in a error notification and the message "Error 1062 (23000): Duplicate entry 'devin' for key 'UQE_orgs_name'" being written to the server logs with "devin" being admin and only user.  Also happens in the current `next` version.

Rolling back to 3.1.0, repos can be enabled without issue. 

![Image](https://github.com/user-attachments/assets/e5880058-8783-4820-8653-433dcfd7d39f)

### Steps to reproduce

1. Navigate to the `/repos` page.
2. Click the "Add repository" button.
3. Click "Enable" on any listed repository not currently enabled. 
4. Receive error message

### Expected behavior

I should be able to enable a repo without error. 

### System Info

```shell
{
  "source": "https://github.com/woodpecker-ci/woodpecker",
  "version": "next-1232ceb794"
}
```

### Additional context

- Reproducible with `woodpeckerci/woodpecker-server:v3.2.0` and `woodpeckerci/woodpecker-server:next-1232ceb794` container images.
- Running in a K3S cluster
- Gitea forge  version 1.23.3
- MariaDB database

Server debug log: [server.debug.log](https://github.com/user-attachments/files/19040797/server.debug.log)

Kubernetes Manifest: 

```
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: woodpecker-server
  namespace: woodpecker
  labels:
    app.kubernetes.io/name: woodpecker
    app.kubernetes.io/component: server
spec:
  serviceName: woodpecker-server-headless
  revisionHistoryLimit: 2
  replicas: 1
  minReadySeconds: 20
  selector:
    matchLabels:
      app.kubernetes.io/name: woodpecker
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: woodpecker
        app.kubernetes.io/component: server
    spec:
      priorityClassName: please-keep-running
      restartPolicy: Always
      terminationGracePeriodSeconds: 100
      containers:
      - name: server
        image: woodpeckerci/woodpecker-server:v3.2.0
        imagePullPolicy: IfNotPresent
        env:
          - name: WOODPECKER_DATABASE_DRIVER
            value: mysql
          - name: WOODPECKER_DATABASE_DATASOURCE
            valueFrom:
              secretKeyRef:
                key: dsn
                name: woodpecker-server
          - name: WOODPECKER_HOST
            valueFrom:
              secretKeyRef:
                key: host
                name: woodpecker-server
          - name: WOODPECKER_ADMIN
            value: devin
          - name: WOODPECKER_GITEA
            value: "true"
          - name: WOODPECKER_GITEA_URL
            valueFrom:
              secretKeyRef:
                key: gitea_url
                name: woodpecker-server
          - name: WOODPECKER_GITEA_CLIENT
            valueFrom:
              secretKeyRef:
                key: gitea_client
                name: woodpecker-server
          - name: WOODPECKER_GITEA_SECRET
            valueFrom:
              secretKeyRef:
                key: gittea_key
                name: woodpecker-server
          - name: WOODPECKER_PLUGINS_PRIVILEGED
            value: woodpeckerci/plugin-docker-buildx
          - name: WOODPECKER_LOG_LEVEL
            value: debug
        resources:
          requests:
            cpu: "50m"
            memory: 400Mi
          limits:
            cpu: "1"
            memory: 1Gi
        ports:
          - name: http
            containerPort: 8000
            protocol: TCP
          - name: grpc
            containerPort: 9000
            protocol: TCP
        volumeMounts:
          - mountPath: /var/lib/woodpecker/
            name: config
        livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: woodpecker-config-pvc
```

### Validations

- [x] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [x] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [x] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/versions]
