### ISSUE TITLE
Fresh run with docker results in "unable to open database file"

### ISSUE THREAD

**Issue by Deishelon** [woodpecker-ci/woodpecker#4939]
### Component

server

### Describe the bug

Trying out woodpecker, my docker-compose file:
```
services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:v3
    ports:
      - 8000:8000
    volumes:
      - woodpecker-server-data:/var/lib/woodpecker/
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_HOST=http://192.168.10.162:8000

volumes:
  woodpecker-server-data:
```

When running with `docker compose up`, I get the following:
```
~/projects/foss/woodpecker$ docker compose up
[+] Running 1/1
 ✔ Container woodpecker-woodpecker-server-1  Created                                                                                                                                                                        0.1s 
Attaching to woodpecker-server-1
woodpecker-server-1  | {"level":"info","time":"2025-03-07T05:42:55Z","message":"log level: info"}
woodpecker-server-1  | {"level":"warn","time":"2025-03-07T05:42:55Z","message":"no sqlite3 file found, will create one at '/var/lib/woodpecker/woodpecker.sqlite'"}
woodpecker-server-1  | {"level":"error","error":"can't setup store: could not migrate datastore: unable to open database file: no such file or directory","time":"2025-03-07T05:42:55Z","message":"error running server"}
woodpecker-server-1 exited with code 0
~/projects/foss/woodpecker$ 
```

Also, I doubled checked the volume dir, and there is no files there:
```
root@[REDACTED]:/var/lib/docker/volumes/woodpecker_woodpecker-server-data/_data# ls -la
total 0
drwxr-xr-x. 1 root root  0 Mar  5 04:50 .
drwx-----x. 1 root root 10 Mar  7 18:37 ..
root@[REDACTED]:/var/lib/docker/volumes/woodpecker_woodpecker-server-data/_data# 
```

### Steps to reproduce

1. Woodperker with docker (configuration from docs) & agent entry removed. (only service)
2. `docker compose up`
3. Observe the error

### System Info

```shell
Docker version 28.0.1, build 068a01e
```

### Additional context

**However**, when running with `woodpeckerci/woodpecker-server:v3-alpine` image - this issue goes away.

### Validations

- [x] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [x] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [x] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/versions]
