### ISSUE TITLE
Make the docker image wait for the PostgreSQL / MySQL database to be up

### ISSUE THREAD

**Issue by erdnaxeli** [woodpecker-ci/woodpecker#4955]
### Clear and concise description of the problem

The current docker image (`woodpeckerci/woodpecker-server:latest`) crash if the db is not accessible:

```
"level":"error","error":"can't setup store: could not migrate datastore: dial tcp [::1]:5432: connect: connection refused","time":"2025-03-14T05:16:11Z","message":"error running server"}
```

This is problematic if you use k8s or another tool (like podman-kube) that does not implement some dependency between containers, and does not wait for the db to be up before starting woodpecker.

### Suggested solution

I suggest to change the entrypoint to use a shell script that would check the db is up before starting Woodpecker. This script would need to handle all the db supported:
* SQLite: nothing to check, start Woodpecker right away
* PostgreSQL / MySQL: check that the db accepts connections before starting Woodpecker

The script could timeout after some time (at least a few minutes), to not maintain the container up forever.

### Validations

- [x] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/versions]
- [x] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [x] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by zc-devs** [comment]
> This is problematic if you use k8s

Works like a charm

```yaml
...
      initContainers:
      - args:
        - tcp
        - postgres.database.svc.cluster.local:5432
        - --backoff-policy
        - exponential
        - --backoff-exponential-max-interval
        - 20s
        - --timeout
        - 600s
        - --
        - echo
        - Services are up
        image: docker.io/atkrad/wait4x:2.14.2
        name: wait4
        resources:
          limits:
            cpu: 100m
            memory: 8Mi
          requests:
            cpu: 20m
            memory: 4Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 65534
          runAsNonRoot: true
          runAsUser: 65534
          seccompProfile:
            type: RuntimeDefault
```
