### ISSUE TITLE
woodpeckerci/plugin-docker-buildx doesn't support kubernetes secrets

### ISSUE THREAD

**Issue by joeky888** [woodpecker-ci/woodpecker#5020]
### Component

agent

### Describe the bug

I have this config in my k8s woodpecker secrets

```yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: woodpecker-secrets
data:
  aws_region: xxx
  aws_access_key_id: xxxxxxxxxx
  aws_secret_access_key: xxxxxxxxxxxxx
```

And I have 2 steps in the woodpecker CI. 

The first step is fine, but the second step gives me error: `secret "aws_access_key_id" not found`

### Steps to reproduce

```yaml
steps:
  - name: debug # This one is okay
    image: alpine
    commands:
      - echo $$aws_region
      - echo $$aws_access_key_id
      - echo $$aws_secret_access_key
    backend_options:
      kubernetes:
        secrets:
          - name: woodpecker-secrets
    when:
      branch:
        - dev
      event:
        - push

  - name: push to ecr # This on gives me error: secret "aws_access_key_id" not found
    image: woodpeckerci/plugin-docker-buildx
    settings:
      registry: <MY_REGISTRY>
      dockerfile: ./dockerfile
      repo: <MY_REPO>
      aws_region:
        from_secret: aws_region
      tags:
        - dev
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
    backend_options:
      kubernetes:
        secrets:
          - name: woodpecker-secrets
        resources:
          requests:
            memory: 500Mi
            cpu: 1000m
          limits:
            memory: 1000Mi
            cpu: 2000m
    when:
      branch:
        - dev
      event:
        - push

```

### Expected behavior

The second step should be fine, so it seems like the plugin doesn't support kubernetes secrets.

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"3.4.0"}
```

### Additional context

k3s cluster (v1.31.6+k3s1) Ubuntu 24.04.1 LTS. 1 server node and 2 agent nodes

### Validations

- [x] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [x] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [x] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/versions]

**Comment by joeky888** [comment]
In case someone is looking for this in the future. 

The only way to add secrets right now is through woodpecker ui or cli. While it is definitely doable for few repos, in my case I have to add so many repositories one by one.

So I decided to make a small helm chart, let's call it woodpecker-secrets in the same namespace along with other woodpecker charts.

job.yaml

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: woodpecker-cli
spec:
  template:
    spec:
      containers:
      - name: woodpecker-cli
        image: woodpeckerci/woodpecker-cli:next-alpine
        env:
        - name: WOODPECKER_SERVER
          value: {{ .Values.woodpecker.server }}
        - name: WOODPECKER_TOKEN
          value: {{ .Values.woodpecker.token }}
        command:
        - sh
        - -c
        - |
          {{- range $index, $repo := $.Values.repos }}
          {{- range $secret_key, $secret_val := $.Values.secrets }}
          woodpecker-cli repo secret rm --repo {{ $repo }} --name {{ $repo }} || echo ok
          woodpecker-cli repo secret add --repo {{ $repo }} --name {{ $secret_key }} --value {{ $secret_val }} || echo ok
          {{- end }}
          {{- end }}
      restartPolicy: Never
  backoffLimit: 1
```

values.yaml

```yaml
woodpecker:
  server: http://woodpecker-server
  token:  xxxxxxx # Copy this from your woodpecker ui -> User Settings ->  CLI & API

secrets:
  aws_region: xxx
  aws_access_key_id: xxxxxxxxxx
  aws_secret_access_key: xxxxxxxxxxxxx

repos:
- my-org/my-repo1
- my-org/my-repo2
```

**Comment by xoxys** [comment]
Thanks for the cool example! If some secrets are shared across repos, you can also use global or org-wide secrets (just in case you did not know already).

**Comment by zc-devs** [comment]
@joeky888, you could try

```yaml
steps:
  - name: push to ecr
    image: woodpeckerci/plugin-docker-buildx
    settings:
      registry: <MY_REGISTRY>
      dockerfile: ./dockerfile
      repo: <MY_REPO>
      tags:
        - dev
    backend_options:
      kubernetes:
        secrets:
          - name: woodpecker-secrets
            key: aws-region
            target:
              env: PLUGIN_AWS_REGION
          - name: woodpecker-secrets
            key: aws_access_key_id
            target:
              env: PLUGIN_AWS_ACCESS_KEY_ID
          - name: woodpecker-secrets
            key: aws_secret_access_key
            target:
              env: PLUGIN_AWS_SECRET_ACCESS_KEY
```
