### ISSUE TITLE
Broken clone path directory

### ISSUE THREAD

**Issue by lafriks** [woodpecker-ci/woodpecker#5045]
### Component

server

### Describe the bug

When specifying clone path relative to workspace behavior has broken in latest `next` version and does not work as it would be expected.

Most probably broken by #5023

Works fine downgrading to v3.4.0

### Steps to reproduce

Example pipeline:
```yaml
clone:
  - name: clone
    image: woodpeckerci/plugin-git:2.6.2

  - name: clone-other
    image: woodpeckerci/plugin-git:2.6.2
    settings:
      remote: https://github.com/lafriks/test.git
      path: relative/path/other
      ref: ${CI_COMMIT_REF}
      depth: 1

steps:
  - name: test
    image: alpine:latest
    commands:
     - ls -la .
```

### Expected behavior

To clone main repo and other repo in subdirectory `relative/path/other`

### System Info

```shell
next
```

### Validations

- [x] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [x] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [x] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/versions]
