### ISSUE TITLE
Reloading repositories from gitea does not work

### ISSUE THREAD

**Issue by plafue** [woodpecker-ci/woodpecker#508]
### Component

server

### Describe the bug

Clicking "reload repositories" in the UI displays a success message ("Repository list reloaded") but the list remains empty. Checking the response from the server shows that it is always an empty array.

This can be reproduced with the docker compose below. Just register a user and add woodpecker as an authorized OAuth2 application (and adjust the compose file along the way).

### System Info

```shell
`{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-ca8e215c"}`
```
```yaml
version: "3"

networks:
  gitea:
    external: false

services:
  gitea:
    image: gitea/gitea:1.15.6
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:latest
    ports:
      - 8000:8000
    volumes:
      - ./woodpecker:/var/lib/woodpecker/
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_HOST=http://localhost:8000
      - WOODPECKER_GITEA=true
      - WOODPECKER_GITEA_PRIVATE_MODE=true
      - WOODPECKER_GITEA_URL=http://${IP_FOR_LOCALHOST}:3000
      - WOODPECKER_GITEA_CLIENT=${WOODPECKER_GITEA_CLIENT}
      - WOODPECKER_GITEA_SECRET=${WOODPECKER_GITEA_SECRET}
      - WOODPECKER_AGENT_SECRET=1234567890123456789012345678901234567890
```

### Additional context

Gitea logs show that `/api/v1/user/repos?limit=50&page=1` is called by woodpecker sucessfully. Also subsequent calls to each repository (`GET /api/v1/repos/{user/org}/{repository}`) are logged by gitea as processed successfully with a `200`.

Woodpeckers sqlite DB remains "empty" (contains only a record in the `user` table and the migrations run in the `migrations` table) after clicking "reload repositories".

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy).
