### ISSUE TITLE
Allow global environment variable expansion in matrix:include definitions

### ISSUE THREAD

**Issue by louiskeen** [woodpecker-ci/woodpecker#5106]
### Clear and concise description of the problem

Global environment variables in the `matrix:include` section are not expanded. Encountered when trying to configure [preview branches for a static site](
https://codeberg.org/loukeen/hugo-deploy/src/branch/test-pr-5/.woodpecker/hugo.yaml) using a configuration such as:

```yaml
matrix:
  include:
    - STAGE: release
      BRANCH: pages
    - STAGE: preview
      BRANCH: preview-${CI_COMMIT_BRANCH}

steps:
  - name: test-var
    image: alpine
    commands:
      - echo BRANCH=$$BRANCH
```

Which, in the "preview" arm of the matrix will print

```
BRANCH=preview-${CI_COMMIT_BRANCH}
```

printing the uninterpolated string. 

### Suggested solution

Instead, it would be wonderful if these variables got expanded so that this step printed

```
BRANCH=preview-branch_name
```

### Additional context

Initially asked if this was expected behavior in the matrix chat and was referred here to report it as an issue. Discussion suggested that this could be supported behavior.

### Validations

- [x] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/versions]
- [x] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [x] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.
