### ISSUE TITLE
`Detach` action doesn't play nicely with Kubernetes backend

### ISSUE THREAD

**Issue by perfectra1n** [woodpecker-ci/woodpecker#5124]
### Component

agent

### Describe the bug

When using the Kubernetes backend, and then running a pipeline that requests for `detach`:
```yaml
steps:
  server:
    image: node:22-alpine
    detach: true
    commands:
      - cd /woodpecker/playwright-tests/server-work/server
      - npm run db:reset
      - exec npm run dev
  ```

The following error shows up in the logs:
```json
{"level":"info","time":"2025-04-25T20:50:02Z","message":"starting Woodpecker agent with version '3.5.2' and backend 'kubernetes' using platform 'linux/amd64' running up to 1 pipelines in parallel"}                                                                      
{"level":"error","error":"rpc error: code = Unknown desc = workflow finished with error Service \"wp-svc-01jsqbepk0ykj9emkhf5mwxeak-server\" is invalid: spec.ports: Required value","time":"2025-04-25T20:50:33Z","message":"grpc error: wait(): code: Unknown"}          
{"level":"warn","repo":"AtvikSecurity/pentracker","pipeline":"959","workflow_id":"1968","error":"rpc error: code = Unknown desc = workflow finished with error Service \"wp-svc-01jsqbepk0ykj9emkhf5mwxeak-server\" is invalid: spec.ports: Required value","time":"2025-04-25T20:50:33Z","message":"cancel signal received"}
```

Then appending the `ports` value to the pipeline:
```yaml
steps:
  server:
    image: node:22-alpine
    detach: true
    commands:
      - cd /woodpecker/playwright-tests/server-work/server
      - npm run db:reset
      - npx ts-node src/scripts/create-test-user.ts
      - exec npm run dev
    ports:
      - 5001
```

The following linter error shows up:
![Image](https://github.com/user-attachments/assets/87268125-dfa9-439e-a181-79659d0de1cc)

So, definitely a chicken and the egg type problem...

### Steps to reproduce

Explained above

### System Info

```shell
Version 3.5.2 for both the server and agent.
```

### Validations

- [x] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [x] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [x] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/versions]
