### ISSUE TITLE
Plugin plugin-docker-buildx v6 removes keys from build-arg

### ISSUE THREAD

**Issue by joeky888** [woodpecker-ci/woodpecker#5145]
### Component

other

### Describe the bug

```yaml
steps:
  - name: push to ecr dev
    image: woodpeckerci/plugin-docker-buildx:6.0.0
    settings:
      mtu: 1500
      registry: <registry>
      dockerfile: ./Dockerfile
      build_args:
        WWWGROUP: 1000
        SUPERVISORD_GO_OS: Linux_ARM64
      repo: <repo>
      aws_region: <region>
      tags:
        - dev
      aws_access_key_id: <key>
      aws_secret_access_key: <secret>
    backend_options:
      kubernetes:
        resources:
          requests:
            memory: 1200Mi
            cpu: 1200m
          limits:
            memory: 1500Mi
            cpu: 1600m
    when:
      branch:
        - develop
      event:
        - push
```

### Steps to reproduce

This yaml produces docker args `--build-arg 1000 --build-arg Linux_ARM64`.

### Expected behavior

It should produce docker args `--build-arg WWWGROUP=1000 --build-arg SUPERVISORD_GO_OS=Linux_ARM64`.

### System Info

```shell
Woodpecker helm chart 3.1.0

woodpeckerci/plugin-docker-buildx v6.0.0
```

### Additional context

Workaround:

```yaml
steps:
  - name: push to ecr dev
    image: woodpeckerci/plugin-docker-buildx:6.0.0
    settings:
      mtu: 1500
      registry: <registry>
      dockerfile: ./Dockerfile
     build_args:
        WWWGROUP: WWWGROUP=1000
        SUPERVISORD_GO_OS: SUPERVISORD_GO_OS=Linux_ARM64
      repo: <repo>
      aws_region: <region>
      tags:
        - dev
      aws_access_key_id: <key>
      aws_secret_access_key: <secret>
    backend_options:
      kubernetes:
        resources:
          requests:
            memory: 1200Mi
            cpu: 1200m
          limits:
            memory: 1500Mi
            cpu: 1600m
    when:
      branch:
        - develop
      event:
        - push
```

This workaround produces `--build-arg WWWGROUP=1000 --build-arg SUPERVISORD_GO_OS=Linux_ARM64`, lol.

### Validations

- [x] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [x] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [x] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/versions]
