### ISSUE TITLE
Can't Log into Woodpecker

### ISSUE THREAD

**Issue by xSTUDDSx** [woodpecker-ci/woodpecker#519]
I have Woodpecker setup with Gitea and have established the Client and Secret. When I click login on Woodpecker, I get directed to Gitea and I login, however, after Authorizing I get dumped back to Woodpecker's main login page with this URL...

- https://woodpecker.mydomain.com/do-login?url=/repos

I can't seem to get into Woodpecker at all. There are no errors in the logs of the server, but I do see this error in the log of the agent.

`{"level":"error","error":"rpc error: code = Unavailable desc = connection closed before server preface received","time":"2021-11-19T14:47:03Z","message":"grpc error: done(): code: Unavailable: rpc error: code = Unavailable desc = connection closed before server preface received"}`

Here is my docker-compose...

```yml
version: '3'

networks:
  reverse-proxy:
    external:
      name: reverse-proxy

services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:latest
    container_name: woodpecker-server
    networks:
      - reverse-proxy
    ports:
      - 8000:8000
    volumes:
      - woodpecker-server-data:/var/lib/woodpecker/
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_HOST=https://woodpecker.mydomain.com
      - WOODPECKER_GITEA=true
      - WOODPECKER_GITEA_URL=https://gitea.mydomain.com
      - WOODPECKER_GITEA_CLIENT=<GITEA_CLIENT>
      - WOODPECKER_GITEA_SECRET=<GITEA_SECRET>
      - WOODPECKER_AGENT_SECRET=<AGENT_SECRET>

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:latest
    container_name: woodpecker-agent
    command: agent
    restart: always
    depends_on:
      - woodpecker-server
    networks:
      - reverse-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WOODPECKER_SERVER=woodpecker-server:8000
      - WOODPECKER_AGENT_SECRET=<AGENT_SECRET>

volumes:
  woodpecker-server-data:
```
