### ISSUE TITLE
Environment variable is not visible in appleboy/drone-ssh script

### ISSUE THREAD

**Issue by dziany-druid** [woodpecker-ci/woodpecker#5220]
### Component

server

### Describe the bug

Environment variable is not visible in appleboy/drone-ssh script section if configured according to the documentation https://woodpecker-ci.org/docs/usage/secrets

### Steps to reproduce

1. Create pipeline like this:

```yml
when:
  branch:
    - 'main'
  event:
    - 'manual'

steps:
  - name: 'backup database'
    image: 'appleboy/drone-ssh'
    settings:
      command_timeout: '2m'
      host:
        - 'your host'
      username: 'your username'
      key:
        from_secret: 'ssh_key'
      DATABASE_PASSWORD:
        from_secret: 'database_password'
      envs:
        - 'DATABASE_PASSWORD'
      script:
        - 'echo -e "password=\"$DATABASE_PASSWORD\""'
```

You will see password=“” in the console which indicates that the DATABASE_PASSWORD variable is not available.

2. Create pipeline like this:

```yml
steps:
  - name: 'backup database'
    image: 'appleboy/drone-ssh'
    environment:
      DATABASE_PASSWORD:
        from_secret: 'database_password'
    settings:
      command_timeout: '2m'
      host:
        - 'your host'
      username: 'your username'
      key:
        from_secret: 'ssh_key'
      envs:
        - 'DATABASE_PASSWORD'
      script:
        - 'echo -e "password=\"$DATABASE_PASSWORD\""'
```

You will see password=“********” in the console which indicates that the DATABASE_PASSWORD variable is available. However linter shows warnings:

![Image](https://github.com/user-attachments/assets/dc8b3d25-7bc8-44b8-a641-e85d7e5ba155)

### Expected behavior

No warnings shown by linter.

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"3.6.0"}
```

### Validations

- [x] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [x] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [x] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/versions]
