### ISSUE TITLE
运行woodpecker流水线后 server报错 panic: Write called after Handler finished

### ISSUE THREAD

**Issue by worldofchu** [woodpecker-ci/woodpecker#5262]
### Component

server

### Describe the bug

运行woodpecker流水线后
server报错

```
panic: Write called after Handler finished

goroutine 206 [running]:
net/http.(*http2responseWriter).write(0x41827f?, 0x1488540?, {0x0?, 0xc000116e01?, 0x478bda?}, {0x170555e?, 0x41827f?})
        /usr/local/go/src/net/http/h2_bundle.go:7130 +0x13f
net/http.(*http2responseWriter).WriteString(0x240d130?, {0x170555e?, 0xb54d36?})
        /usr/local/go/src/net/http/h2_bundle.go:7123 +0x28
io.WriteString({0x7f87160b6bc0, 0xc000596f08}, {0x170555e?, 0x18?})
        /usr/local/go/src/io/io.go:316 +0x54
github.com/gin-gonic/gin.(*responseWriter).WriteString(0xc000e42400, {0x170555e, 0x18})
        /woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/response_writer.go:90 +0x89
io.WriteString({0x7f87160b6b80, 0xc000e42400}, {0x170555e?, 0x18?})
        /usr/local/go/src/io/io.go:316 +0x54
go.woodpecker-ci.org/woodpecker/v3/server/api.LogStreamSSE.func2()
        /woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/stream.go:253 +0x18a
created by go.woodpecker-ci.org/woodpecker/v3/server/api.LogStreamSSE in goroutine 205
        /woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/stream.go:222 +0x8c5
```

### Steps to reproduce

78","message":"grpc error: wait(): code: Unavailable"}

```yml
services:
  woodpecker-server:
    user: root
    image: woodpeckerci/woodpecker-server:v3.7.0
    networks:
      - woodpecker-net
    ports:
      - 6080:6080
      - 6443:6443
      - 9000:9000
      - 9001:9001
    volumes:
      - woodpecker-server-data:/var/lib/woodpecker/
      - /mnt/disksdb/woodpeckerdata/certs/woodpecker.key:/etc/woodpecker/certs/woodpecker.key
      - /mnt/disksdb/woodpeckerdata/certs/woodpecker.crt:/etc/woodpecker/certs/woodpecker.crt
    environment:
      - WOODPECKER_OPEN=false
      - WOODPECKER_SERVER_ADDR=:6080
      - WOODPECKER_SERVER_ADDR_TLS=:6443
      - WOODPECKER_GRPC_ADDR=:9000
      - WOODPECKER_METRICS_SERVER_ADDR=:9001
      - WOODPECKER_ADMIN=gitea
      - WOODPECKER_PLUGINS_PRIVILEGED=true
      - WOODPECKER_SERVER_CERT=/etc/woodpecker/certs/woodpecker.crt
      - WOODPECKER_SERVER_KEY=/etc/woodpecker/certs/woodpecker.key
      - WOODPECKER_HOST=https://192.168.1.35:6443
      - WOODPECKER_GITEA=true
      - WOODPECKER_GITEA_URL=https://192.168.1.34:3443
      - WOODPECKER_GITEA_CLIENT=d16bfdf5-0bb9-42bf-97d6-c07ce6d15fae
      - WOODPECKER_GITEA_SECRET=gto_py3vy4zedpfem7s3z3botjgtxymsgtoru6eebcpcuw5tu3ln2o4q
      - WOODPECKER_GITEA_SKIP_VERIFY=true
      - WOODPECKER_GRPC_SECRET=8161ca1de82229be5a5f158b0e4736d0
      - WOODPECKER_AGENT_SECRET=8161ca1de82229be5a5f158b0e4736d0
      - WOODPECKER_DEFAULT_CLONE_PLUGIN=woodpeckerci/plugin-git:2.6.5
      - WOODPECKER_PLUGINS_TRUSTED_CLONE=woodpeckerci/*
      - WOODPECKER_LOG_LEVEL=debug
      - WOODPECKER_DATABASE_DRIVER=postgres
      - WOODPECKER_DATABASE_DATASOURCE=postgres://woodpecker:woodpecker%40123@192.168.1.51:5432/woodpeckerdb?sslmode=disable

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:v3.7.0
    networks:
      - woodpecker-net
    command: agent
    restart: always
    depends_on:
      - woodpecker-server
    volumes:
      - woodpecker-agent-config:/etc/woodpecker
      - /var/run/docker.sock:/var/run/docker.sock 
      - /usr/local/share/ca-certificates/nexus.pb.com.crt:/usr/local/share/ca-certificates/nexus.pb.com.crt:ro
      - /etc/docker/daemon.json:/etc/docker/daemon.json:ro
    environment:
      - WOODPECKER_PLUGINS_TRUSTED_CLONE=woodpeckerci/*
      - WOODPECKER_GITEA_SKIP_VERIFY=true
      - WOODPECKER_SERVER=woodpecker-server:9000
      - WOODPECKER_GRPC_SECRET=8161ca1de82229be5a5f158b0e4736d0
      - WOODPECKER_AGENT_SECRET=8161ca1de82229be5a5f158b0e4736d0
      - WOODPECKER_BACKEND=docker
      - WOODPECKER_BACKEND_DOCKER_NETWORK=woodpecker-net
      - SSL_CERT_DIR=/usr/local/share/ca-certificates/
      - WOODPECKER_DOCKER_CONFIG=/etc/docker/config.json
      - WOODPECKER_LOG_LEVEL=debug
      - WOODPECKER_MAX_WORKERS=2

volumes:
  woodpecker-server-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/disksdb/woodpeckerdata/storage
  woodpecker-agent-config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/disksdb/woodpeckerdata/config

networks:
  woodpecker-net:
    driver: bridge
    name: woodpecker-net
```

----

```yml
when:
  - event: push
    branch: main
clone:
  git:
    image: woodpeckerci/plugin-git:2.6.5
    settings:
      skip-verify: true
steps:
  - name: a-test-step
    image: alpine:latest
    commands:
      - echo "Testing ..."
```

### System Info

```shell
debian12  dockercompose  woodpeckerv3.7.0
```

### Validations

- [x] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [x] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [x] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/versions]
