### ISSUE TITLE
Lists of changed files of pull-requests are empty

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#555]
### Component

server

### Describe the bug

```yml
pipeline:
  build:
    image: node:14-alpine
    commands:
      - cd docs/
      - yarn install --frozen-lockfile
      - yarn build
    when:
      event: [push, pull_request]
      path: "docs/**"
```

Step is executed although no file in `docs/**` has been changed.

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-7931bc78"}
```

### Additional context

```shell
https://ci.woodpecker-ci.org/woodpecker-ci/woodpecker/build/1317
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy).
