### ISSUE TITLE
Breaking changes before releasing 0.16.0

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#567]
from #393

- pipeline config changes
  - [ ] remove support for `root.pipeline.[step].commands` string values in favor of array lists -> need more discussion
  - [ ] move `root.platform`, `root.branches`, `root.labels`,  `root.runs_on`,  `root.depends_on` to `root.when.xxx` to match step filters #283
  - [ ] make `root.when` and `root.pipeline.[step].when` an array of the current with items using the current settings to allow ORs
        -> non breaking
  - [ ] remove `root.Cache` and functionality in favor of plugins? -> need more discussion

**Comment by LamaAni** [comment]
Hi, whats the ETA on 0.16?

**Comment by 6543** [comment]
This is an opensource project, work is done in free time. So we can only guess when v1.0.0 will be released. This can happen in 2Months or in 5 ...

**Comment by LamaAni** [comment]
Hum. Thank you. Though I was asking when for for the 0.16.0, or the root.when feature, which I understand is the next candidate. That would be good for me. 

In any case, I would resort to building from source and PR back anything I got.

**Comment by LamaAni** [comment]
Hi Looks GOOD!

**Comment by LamaAni** [comment]
Can we change pipeline to steps?

**Comment by 6543** [comment]
we can but it would break **all** existing configs, what's the benefit? 

you can add it to #829 as comment, but for now I don't see a benefit - if it would technically improve a ting or make something possible that was not before it should be considered - but just for the sake of taste we should not break things - call it backwards compatibility

**Comment by anbraten** [comment]
> All types should echo the yaml structure, and no/minimal "special" handling.
> (For example when is list. Always).

I really like that idea of having just one way of doing things. Having the option to use arrays or just a single string confuses be quite often and makes things like json-schema a hell to write.

**Comment by LamaAni** [comment]
It would. When we are following the yaml config we can do the following things:
1. Add default definition to a server, E.G. Allow a "default pipeline" that will be merged.
2. Easier for new people to understand. 
3. Allow anchors to be used in the yaml config anywhere -> leads to more configurable yaml.

In general, the idea of version is good since it allows one to slowly migrate to a more "readable" yaml. Following standards, IMO, is the best way to expand use. 

Finally, Once proper yaml exists, we can in general start considering dynamic pipelines.

**Comment by LamaAni** [comment]
Oh another thing, one can see an example of over complication by not following yaml standards in the Containers unmarshel,
```golang
	for i, n := range value.Content {
		if i%2 == 1 {
			container := Container{}
			err := n.Decode(&container)
			if err != nil {
				return err
			}

			if container.Name == "" {
				container.Name = fmt.Sprintf("%v", value.Content[i-1].Value)
			}
			c.Containers = append(c.Containers, &container)
		}
	}
```
Instead of
```yaml
containers := []*Container{}
err := value.Decode(&containers)
```

Which complicates the code and causes errors. Makes things harder to manage or write.

**Comment by anbraten** [comment]
To be able to have multiple parser (for different versions) in Woodpecker I would like to do some changes to the parsing (exp. creating a clean interface what needs to be inserted and whats the output). I already started that a bit in #802.

**Comment by silverwind** [comment]
Two points from me:

1. Allow to define steps in array format (as in OP), to avoid undefined dict key iteration problems with YAML parsers. https://github.com/woodpecker-ci/woodpecker/issues/771#issuecomment-1282942401.
2. Support parallelism inside a pipeline via a [DAG](https://en.wikipedia.org/wiki/Directed_acyclic_graph). This requires a way to define step dependencies which can then allow the runner to build said DAG.

**Comment by 6543** [comment]
1. is already resolved

**Comment by gapodo** [comment]
Things that to mind would be:
* an and/or/not wrapper around conditions (recursive) to allow for more complex conditionals.
* an `ignoremessage` (best case array) in any item / by itself (or am I overlooking something that would allow for this currently)
* a `forceMessage` allowing to completely disable the `when:` or parts of the `when:` (could be a `not.ignoremessage` with some `and:` `or:` usage)

Use-cases would be highly conditional pipelines (possibly controlled via Commit message), which would allow for easy sub-builds (i.e. when developing woodpecker, only build OCI-images for the agent and server with the default image, so no binaries, no docks, no alpine,...)

```
when:
  or:
    branch:
      includes: [ release/*, main]
    tag:
      includes: [ v0.* ]
  and:
    path:
      includes: [ **.md ]
    not:
      ignoremessage: [ "no docs" ]
```

Also since v2 is a "breaking" version I would like to try and get as much of the major refractoring / syntax changing done as possible to not break the schema soon to add new features.

**Comment by remram44** [comment]
You can just have the job decide what is appropriate for it to do. The job runs actual code, recreating so much of it in the config is probably not necessary.

**Comment by gapodo** [comment]
The reason I'm trying to declare the conditions in the pipeline are:
* Reduction of code duplication (else every plugin or container+commands would need to implement the full control structure)
* Ease of handling, the N deep conditional structure is much easier to parse from the pipeline file, than from the env
* Ease of access to parameters (it's easier/"safer*" to access them in the pipeline rather than parsing them from env)
* Single binary images (distroless), which do not run commands but only a single (mostly statically linked) binary, with supplied parameters
* Declarative setup, the pipeline does the conditionals not even starting the container (also reduces unnecessary image pulls, which for java, npm and a few others can be hundreds of MB, or even 2.5G)

* By safer, I mean less error-prone when parsing values, etc. I'm a Linux guy so fairly used to shell commands, globboing, parameter expansion, control-chars in strings,... but that's not true for everyone

**Comment by gapodo** [comment]
Another thing that came to mind would be using an `apiVersion` and `kind` annotation (similar to what Kubernetes does) instead of the `version` annotation, allowing for other types (e.g. reusable steps) to be stored alongside and recognized accordingly (would be a next step, but this would allow for a non-breaking addition in the future).

build.yml
```yaml
apiVersion: woodpecker-ci.org/v2
kind: pipeline

steps:
  - name: ReusableLinter
    include: ./lint.yml
```

lint.yml
```yaml
apiVersion: woodpecker-ci.org/v2
kind: step

step:
  image: myLinter
  commands:
    - linter lint .
```

The include is just an example on how this could be useful in the future, for now it would just be the `apiVersion` and `kind` (which would also allow us to be immune against "other" `yaml` or `yml` files in the same directory, as we could simply filter on the `apiVersion` and `kind`

I'm NOT proposing formatting the files to allow for a CRD (Kubernetes Custom Resource Definition), though this would also be an idea that could be taken into account while restructuring (if we want to possibly enable closer integration with a Kubernetes based backend), as it would allow the Server to just create a CRD and hand it over to the agent when using the Kubernetes backend. It would require adding a `metadata` section with at least a name and namespace (could be optional for "normal" use) and move the pipeline or step definition into a `spec` section (nothing in the root except apiVersion, kind, metadata and spec)

**Comment by gapodo** [comment]
Another thing that may be helpful esp. when building plugins might be to add on option to hand over the `frontend.Metadata` or a specific abstraction as serialized JSON (possibly in a file) to allow easy loading of those settings ("skipping" the to env and back) using esp. go where we can reuse the definitions already set by woodpecker itself.

**Comment by anbraten** [comment]
@gapodo FYI: for complex conditions you should already be able to use: https://woodpecker-ci.org/docs/next/usage/pipeline-syntax#evaluate

**Comment by gapodo** [comment]
I've seen evaluate, but it might be a bit convoluted compared to a structured conditional (but yes it would work, it's just not easily lint-able that way).

**Comment by gapodo** [comment]
Another thing (should I open FRs for these ideas?) would be some kind of `badge_groups[].name` in the step, allowing to collect success-statuses of various parts of the pipeline, previously I would have said just abuse the `group` (i.e. showing the Status as: Linting: success, Binary Builds: success, Container Builds: failing).

This might be augmented with something like `globalStatusEnabled` and `badge_groups[].statusEnabled` to allow one to ignore the return of a step for the overall or badge success status.

```yaml
apiVersion: woodpecker-ci.org/v2
kind: pipeline

steps:
  - name: Lint
    badge_groups:
      - name: Lint
      - name: ContainerBuild
      - name: BinaryBuild
      - name: Docs
        statusEnabled: false

  - name: ContainerBuild-debian
    badge_groups:
      - name: ContainerBuild

  - name: ContainerBuild-alpine
    badge_groups:
      - name: ContainerBuild

  - name: BinaryBuild
    badge_groups:
      - name: BinaryBuild

  - name: DocsBuild
    badge_groups:
      - name: DocsBuild

  - name: notify
    globalStatusEnabled: false
    badge_groups:
      - name: Notification
```

I've left out images,... just to show the basic idea. This would give us 5 specific badges + the global one, where the global one ignores the notify step (we've built successfully but not notified).
