### ISSUE TITLE
create a matrix room for chat/support

### ISSUE THREAD

**Issue by fariszr** [woodpecker-ci/woodpecker#640]
currently when clicking on questions and support it redirects you to discord.

i created a temp account, but it required my phone number, for just creating an empty account.
i suggest creating a matrix room like codeberg with a bridge to discord.

so we users don't have to deal with discord bad privacy.

**Comment by fariszr** [comment]
you can also use github discussions

**Comment by fariszr** [comment]
my question was:

how to add an ssh key from a secret ? it doesn't work like drone:

## pipeline

```
pipeline:
  push:
    image: alpine:latest
    commands:
      - apk add --no-cache openssh
      - eval `ssh-agent -s`
      - echo "${ssh_priv12_key}" | ssh-add -
      - mkdir -p ~/.ssh
      - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      - git config --global user.name "org-Bot"
      - git config --global user.email "$${BOT_EMAIL}"
      - git remote set-url origin ssh://git@codeberg.org/xxx/xxx
      - git checkout pages
      - git add dev
      - git commit -m "upload latest dev build"
    secrets: [bot_email, ssh_priv12_key]
```

it stops at the 3rd command `Error loading key "(stdin)": invalid format`
