### ISSUE TITLE
Allow multiple when filters

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#686]
Make `root.when` and `root.pipeline.[step].when` an array, so a user could  current options using the current settings to allow ORs

current:
```yml
when:
  branch: main
  event: push
```

new:
```yml
when:
  - branch: main
    event: push
  - event: pull_request
    path: "src/*"
```
