### ISSUE TITLE
global pipeline filter should behave on multi-pipeline same

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#688]
at the moment, if only "some" pipelines in multi pipelines are skiped, there proc tree is still build but never exec (as intended)

example: 
`.build.yml`
```yml
# These checks already get performed on the feature branches
branches:
  exclude: [ main, dev ]

pipeline:
  ...
```
`.lint.yml`
```yml
branches:
  exclude: [ main, dev ]

pipeline:
  lint:
    ...
```
`.publish.yml`
```yml
branches: [main, dev]

pipeline:
  dev:
    image: plugins/docker
    ...
```
-> https://git.rustybever.be/Chewing_Bever/vieter/commit/b5224e8a63de54c122f178bf0052a4029953c4cc

# Expect:
`.lint` & `.build`  should not show up in woodpecker
