### ISSUE TITLE
Setting AWS Key and secret in value does not work

### ISSUE THREAD

**Issue by jasonrichardsmith** [woodpecker-ci/woodpecker#706]
I have been testing woodpecker ci at codeberg.  The S3 plugin did not work like this:
```
pipeline:
  upload:
    image: woodpeckerci/plugin-s3
    secrets: [aws_access_key_id, aws_secret_access_key]
    bucket: my-bucket-name
    access_key: $aws_access_key_id
    secret_key: $aws_secret_access_key
    source: public/**/*
    target: /target/location
```
But it does when you just leave the values as env vars:
```
pipeline:
  upload:
    image: woodpeckerci/plugin-s3
    secrets: [aws_access_key_id, aws_secret_access_key]
    bucket: my-bucket-name
    source: public/**/*
    target: /target/location
```

**Comment by anbraten** [comment]
Could you try:

```
pipeline:
  upload:
    image: woodpeckerci/plugin-s3
    secrets: [aws_access_key_id, aws_secret_access_key]
    settings:
      bucket: my-bucket-name
      access_key:
        secret: aws_access_key_id
      secret_key:
        secret: aws_secret_access_key
      source: public/**/*
      target: /target/location
```
