### ISSUE TITLE
Add condition to run pipeline only on agents with a specific backend

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#708]
@ambroisie:

> I would really like to be able to select which backend is used on a pipeline basis instead, like one can on Drone.

maybe something like:

```yml
labels:
  backend: local

pipeline:
  [...]
```

## To be able to do this we can add auto-generated labels for agents such as:

- backend type (local, docker, ...)
- arch
- os
