### ISSUE TITLE
Step cancelled without reason

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#806]
I am trying to build and publish Docker image using Dockerfile. I have a repository in Gitea. I am getting a "The step has been cancelled" error for the clone step. Please find the screenshot below.  

![image](https://user-images.githubusercontent.com/633479/155831533-155b99f3-0df7-4a36-963f-cd6403f210b5.png)

Here is my pipeline

```
pipeline:
  publish:
    image: plugins/docker
    group: docker
    secrets: [ docker_username, docker_password ]
    settings:
      repo: dockerregistry/reponame
      dockerfile: Dockerfile
      tag: latest
    when:
      branch: master
      event: push
```

Am I missing or doing anything wrong?

_Originally posted by @rajaseg in https://github.com/woodpecker-ci/woodpecker/issues/795#issuecomment-1051652122_

**Comment by anbraten** [comment]
@rajaseg I have created this issue for you as it seemed to no be related to the original issue. Hope thats fine for you.

**Comment by 6543** [comment]
@rajaseg whitch architecture/system your agents do run under?

**Comment by rajaseg** [comment]
> @rajaseg whitch architecture/system your agents do run under?

@6543 I am running woodpecker server and Agent using docker-compose in swarm environment on Ubuntu Server 20.04 LTS

docker-compose.yml
```
version: "3.7"

services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:latest
    volumes:
      - /localvolume:/var/lib/woodpecker/
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_HOST=https://woodpecker.example.com
      - WOODPECKER_GITEA=true
      - WOODPECKER_GITEA_CLIENT=client id
      - WOODPECKER_GITEA_SECRET=secret
      - WOODPECKER_GITEA_URL=https://gitea.example.com
      - WOODPECKER_AGENT_SECRET=agent secret
    networks:
      - caddy
    ports:
      - "8000:8000"
    deploy:
      placement:
        constraints: [node.role == worker]
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:latest
    command: agent
    depends_on:
      - woodpecker-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WOODPECKER_SERVER=woodpecker-server:9000
      - WOODPECKER_AGENT_SECRET=agent secret
      - WOODPECKER_MAX_PROCS=10
    networks:
      - caddy
    deploy:
      placement:
        constraints: [node.role == worker]
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
volumes:
  localvolume:
    driver: "local"
networks:
  caddy:
    external: true
```
Docker Version
```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:06 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
Docker Compose Version
```
docker-compose version 1.26.0, build d4451659
```
