### ISSUE TITLE
Broken / incomplete implementation of from_secrets

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#840]
Currently the docs suggest following code to set a setting with a secret:

```diff
pipeline:
  docker:
    image: my-plugin
    settings:
+     token:
+       from_secret: secret_token
```

But this is missing that you still need to add `secrets` to the step:

```diff
pipeline:
  docker:
    image: my-plugin
    settings:
      token:
        from_secret: secret_token
    secrets:
      - secret_token
```

Best would be to not need to redefine `secrets` with values used with `from_secrets`, but that would require a lot of refactoring.

The easiest and best for now could be to throw an error if a `from_secrets` is used but not defined in secrets and add a hint to the docs to not forget it.

**Comment by jolheiser** [comment]
Admittedly I haven't looked if something changed, but when I made the PR you didn't need to redefine anything.

**Comment by jolheiser** [comment]
I currently have working pipelines that don't define `secrets` anywhere. If this not longer works, it's a regression.

**Comment by anbraten** [comment]
Weird. Im am currently trying to get this step to work:

```yml
pipeline:
  build:
    image: alpine
    commands:
      - mkdir -p docs/build/
      - echo "Hello world" > dist/index.html

  deploy-preview:
    image: woodpeckerci/plugin-surge-preview:next
    settings:
      path: "docs/build/"
      surge_token:
        from_secret: SURGE_TOKEN
      forge_type: github
      forge_url: "https://github.com"
      forge_repo_token:
        from_secret: GITHUB_TOKEN_SURGE
```

And my secrets look like:

![Screenshot from 2022-03-17 21-23-43](https://user-images.githubusercontent.com/6918444/158889132-bc6288a2-1d93-4a96-b7ff-f7f2061ac2d8.png)
![Screenshot from 2022-03-17 21-23-28](https://user-images.githubusercontent.com/6918444/158889134-2aca82bb-bb3d-4faf-ba1a-28e6c4cb331b.png)

But in the debugger the env variables passed to the docker container only contain: `PLUGIN_PATH=docs/build/` and `PLUGIN_SURGE_TOKEN=`.

**Comment by jolheiser** [comment]
That is strange...any errors?
Looks like not even all the settings are getting injected.

My pipeline has
```yaml
pipeline:
...
  release-main:
    image: ...
    settings:
      base: ...
      token:
        from_secret: gitea_token
      files:
        - "..."
        - "..."
```
And it has been working for me.
