### ISSUE TITLE
Add retry / onerror directive to pipelines

### ISSUE THREAD

**Issue by fnetX** [woodpecker-ci/woodpecker#884]
### Clear and concise description of the problem

Sometimes it happens that pipelines fail not because of a fault in the changeset, but because of external circumstances (network failures etc).

Especially for prepare pipelines that just set up an environment and are not supposed to check the actual change, doing an automatic retry could be desirable.

Especially with #767 it would be a problem if a failed prepare pipeline is then cached for a while (probably failed pipelines shouldn't be cached, but still) ...

### Suggested solution

Add a `retry`, or `onerror`, `onfail` directive that can take different values for retry policies, e.g.

- none: default behaviour, no retry
- retry: rebuild the step, optionally with a number specified, e.g. retry(3) = retry 3 times, or retry:2 (only twice)
- fast-retry: only retry if the pipeline failed fast, e.g. due to dependency cloning, but not when it was already running long (ideally with a threshold in seconds)
- skip: report as failure, but run the following pipeline anyway (e.g. to see if the project builds even when the lint step fails)
- ignore: mark the step as failed in the Woodpecker UI, but ignore it for the final report and continue with next pipeline (if all other pipelines succeed, report as successful)

I think this could be a great feature for Woodpecker CI.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by anbraten** [comment]
There was a setting added for `failure` https://woodpecker-ci.org/docs/next/usage/pipeline-syntax#failure. The retry logic would probably be best implemented by the script / tool. Exp jest, vitest, playwright have integrated retry logics and for go sth like https://pkg.go.dev/github.com/hashicorp/consul/sdk/testutil/retry could be used.

**Comment by zc-devs** [comment]
It would be nice to have such a feature.
```yaml
# Environments
# SKIP_IMAGE=true|false - skip building image
# SKIP_PUBLISH_QUAY=true|false - skip publishing in Quay
# SKIP_PUBLISH_GHCR=true|false - skip publishing in GitHub

variables:
  - &kaniko_image "gcr.io/kaniko-project/executor:v1.22.0-debug"
  - &skopeo_image "quay.io/containers/skopeo:v1.15.0"
  - &app_version "28.0.5"

steps:
  set-env:
    image: debian:bookworm-slim
    environment:
      APP_VERSION: *app_version
    commands:
      - .cicd/set-env.sh
    retry: 2
  image:
    when:
      evaluate: 'SKIP_IMAGE != "true"'
    image: *kaniko_image
    commands:
      - .cicd/set-docker-auth.sh
      - .cicd/build.sh
    retry: 3
  publish-quay:
    when:
      evaluate: 'SKIP_PUBLISH_QUAY != "true"'
    image: *skopeo_image
    commands:
      - skopeo copy --dest-creds="$QUAY_CREDS" "docker://$SRC_IMAGE" "docker://$DST_IMAGE"
    retry: 3
  publish-ghcr:
    when:
      evaluate: 'SKIP_PUBLISH_GHCR != "true"'
    image: *skopeo_image
    commands:
      - skopeo copy --dest-creds="$GHCR_CREDS" "docker://$SRC_IMAGE" "docker://$DST_IMAGE"
    retry: 3
```

If some step fails wit network error, for example step `publish-ghcr` with level=fatal msg="writing blob: uploading layer chunked: received unexpected HTTP status: 502 Bad Gateway", I have to manually rerun pipeline with
```
SKIP_IMAGE=true
SKIP_PUBLISH_QUAY=true
```

More steps there are, more failed step is close to the end - more annoying manual run becomes.
