### ISSUE TITLE
Allow the usage of environment variables in filters

### ISSUE THREAD

**Issue by x80486** [woodpecker-ci/woodpecker#963]
### Clear and concise description of the problem

I'm used (from `GitLab CI`) to be able to provide some some references in filters; for instance:

```yaml
default:
  image: docker.io/docker/compose:alpine-1.29.2

stages:
  - verify

validate:
  stage: verify
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_MERGE_REQUEST_ID
  script:
    - docker-compose config --quiet
```

While the filters in `Woodpecker CI` are slightly different, they achieve (almost) the same results, so it would be great to be able to use environment variables in these as well.

```yaml
pipeline:
  validate:
    commands:
      - docker-compose config --quiet
    group: verify
    image: docker.io/docker/compose:alpine-1.29.2
    when:
      branch: ${CI_REPO_DEFAULT_BRANCH}
```

### Suggested solution

Just to be able to refer to environment variables in filters — expanded by default :wink:

### Alternative

N/A

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.
